// Generated by scripts/build-detail-data.mjs — edit the copy here directly;
// re-running the generator overwrites this file.
import type { Faq } from "./types";

/**
 * Deeper per-area copy layered onto AreaHubContent. Area hubs were the
 * thinnest of the three core templates; these fields carry the housing
 * detail that makes each of the 25 pages worth reading on its own.
 */
export type AreaDetail = {
  /** Named streets and sub-neighbourhoods, and the stock on them. */
  streets: string;
  /** Recurring building types and what they mean for interior work. */
  buildings: string;
  /** Parking, loading, skips and access specifics. */
  access: string;
  /** Additional hand-written questions, merged after the existing faqs. */
  extraFaqs: Faq[];
};

export const areaDetail: Record<string, AreaDetail> = {
  "archway": {
    streets: "Archway is organised by its gyratory and by the climb away from it. The shops, buses and flats over shops belong to Junction Road and Holloway Road; the quieter housing begins where the ground rises. Highgate Hill and Dartmouth Park Hill are the two ascents, and bay-fronted Victorian terraces fill the streets off them — St John's Way, Hargrave Road and Hargrave Park among them [VERIFY the extent of Victorian stock street by street] — with raised ground floors and short front gardens. Archway Road runs north as the A1 toward Highgate. Close to the gyratory the fabric is later: post-war blocks, infill and mixed tenure, which behave nothing like a converted house.",
    buildings: "The characteristic building is a two- or three-storey London stock brick terrace with a closet wing at the rear. The wing held the original scullery and outside WC; today it usually holds the kitchen, with a bathroom on the half-landing above or carved out of the smallest bedroom. Most of these houses were split into flats decades ago, and the split is the issue: stud partitions run past joists rather than under them, services are boxed in wherever there was room, and separation between flats is thin. Opening a floor for a new bathroom typically exposes that earlier work before it exposes anything Victorian. Falls to the rear are common, so nothing is assumed level until it is checked.",
    access: "Nothing stands on the gyratory, and Holloway Road and Archway Road are main routes where standing is restricted [VERIFY red-route status and hours for the frontage]. The practical base is a residential side street, with a suspended bay or a skip licensed by Islington. Those streets slope, so a skip needs level standing and a scaffold needs proper setting out rather than adjustment on the day. Whittington Hospital traffic keeps Highgate Hill busy, and the CPZ leaves little casual space by mid-morning [VERIFY zone and hours].",
    extraFaqs: [
      {
        q: "Our flat was converted from a house years ago — what usually turns up when the bathroom comes out?",
        a: "Three things, most of the time. Waste runs laid at too shallow a fall to reach the stack; a floor build-up that hides a previous leak rather than a repair; and partitions sitting on boards instead of on structure. None of it is unusual for a conversion of that era. We open up, record what is there, and set out the correction before it becomes a surprise mid-job.",
      },
      {
        q: "Can a flat above a shop on Junction Road be refurbished while the shop stays open?",
        a: "Usually, with conditions. Everything goes up a single street door and a narrow stair, so loads are broken down and timed around the shop's trading. Noisy work is programmed rather than run continuously, and waste comes out the same way it went in. Extract has to terminate on a rear or flank elevation, because there is rarely a route to the front [VERIFY the demise and any lease restriction on hours].",
      },
    ],
  },
  "belsize-park": {
    streets: "Two grains meet here. Belsize Lane, Belsize Terrace and Belsize Crescent form the Village: small frontages, a triangle of shops, and houses that step straight onto narrow pavements. Out from it, Belsize Park Gardens, Belsize Avenue, Belsize Square and Lancaster Grove run wide, with paired stucco villas set behind front steps and lightwells. Haverstock Hill and England's Lane carry the shops and the flats above them. On the eastern slope, Parkhill Road, Upper Park Road and Lawn Road bring later blocks in among the Victorian stock, the Isokon building on Lawn Road among them [VERIFY its architect, date and listing grade]. Ornan Road and Howitt Road sit between the two, mostly converted.",
    buildings: "The characteristic building is a stucco-fronted villa with a raised ground floor, a lightwell and a lower-ground floor that held the original kitchen. Principal rooms are tall, with deep cornices, ceiling roses and chimney breasts on both flank walls, which is why so many kitchen layouts here are really decisions about what to do with a breast and its flue. Plaster is lime on lath above ground level and often patched in gypsum since. Where houses were laterally converted, services cross what were once two separate buildings, and a waste run can leave one original property and enter another. Inserted bathrooms frequently have no external wall at all; the extract route then decides the layout.",
    access: "Front steps and lightwells decide how much can be carried in one lift: on a raised-ground-floor villa everything comes up half a storey before it reaches the hall. The wide avenues take a skip reasonably well; the Village triangle does not, and loading there is measured in minutes rather than hours. Haverstock Hill is a main road with restrictions that differ from the side streets [VERIFY whether the frontage sits on a red route]. Camden licenses skips and scaffolding, and controlled parking applies throughout [VERIFY the zone].",
    extraFaqs: [
      {
        q: "Can the chimney breast come out to make room for the kitchen?",
        a: "Not by us. Taking out a breast is structural work and sits with Hampstead Renovations, not with a refurbishment programme. In practice we design around it: the breast becomes the cooker position or a full-height run of tall units, and the alcoves take the worktop. In a converted villa the flue above may still serve another flat, which is a further reason to leave it standing.",
      },
      {
        q: "Our stucco front is cracked and flaking. Is that decorating work?",
        a: "Painting previously painted stucco is decorating; cutting out and re-running the mouldings is a repair specification, and either can need consent inside the conservation area [VERIFY the boundary and any Article 4 for the address]. The coating matters as much as the colour, since a film that will not let the render dry out is what has caused most of the flaking we find.",
      },
    ],
  },
  "crouch-end": {
    streets: "Everything here is measured from the clock tower. Tottenham Lane runs east toward Hornsey, Crouch Hill and Crouch End Hill climb and fall to the south, and Park Road heads north-east past Priory Park [VERIFY these road names and the park's position]. The Broadway itself is shops with flats over them. Behind it the streets tighten into uniform Victorian terraces, and Middle Lane, Weston Park and the roads off Ferme Park Road are the conversion heartland [VERIFY these street names]. Higher ground toward Highgate carries larger Edwardian semis; toward Stroud Green the terraces get narrower and later. House size is the distinction that matters on site, because it decided how many flats the building was cut into.",
    buildings: "Bay-fronted Victorian terraces and larger Edwardian semis, most of them divided into two or three flats. The tell is the hall: geometric tiles, an original arch, then a modern fire door where the flat begins. Cornices, roses and panelled doors survive on the upper floors more often than at garden level. Kitchens in garden flats sit in the old rear return; upper-flat bathrooms are usually a former box room or a slice taken off a bedroom, which is why a bathroom so often sits directly over a neighbour's bed. Joists rarely run the way a new layout wants and stacks are shared, so drainage and acoustics settle the plan before the tiling is discussed.",
    access: "The Broadway is a bus corridor, so daytime loading there is a poor default and the residential streets take the vans instead. Parking is a patchwork: some roads controlled, some not, and the difference is street by street [VERIFY the current Haringey CPZ zones and hours]. Skips need a Haringey licence and, on the hill roads, chocking and lighting. In a converted house the shared front door and stair are the real bottleneck, and protection of the common parts goes in before the first load.",
    extraFaqs: [
      {
        q: "The flat above ours has its bathroom over our bedroom. Can that be improved?",
        a: "It is the standard consequence of converting a Victorian house, and it can be improved when that bathroom is being replaced anyway. Pipework is clipped and lagged rather than left to drum against joists, wastes are laid to a proper fall on resilient supports, and a floating floor build-up is specified where the depth allows. The gain is real but partial, and we say so before starting.",
      },
      {
        q: "Can the original tiled hall floor survive a flat refurbishment?",
        a: "Usually, if it is protected from the first day rather than the last. Geometric hall tiles are thin, bedded on lime and unforgiving of a dropped tool, so the hall is boarded before any material comes through. Loose tiles are lifted and re-bedded, and missing ones matched where a match exists. We would rather repair the original floor than cover it with a new one.",
      },
    ],
  },
  "dartmouth-park": {
    streets: "Dartmouth Park Hill climbs from Kentish Town toward Highgate and divides the neighbourhood into two grains. West of it, Croftdown Road, Twisden Road, Laurier Road and the streets running down to Parliament Hill Fields are tighter bay-fronted terraces on a regular grid [VERIFY the individual street names against Camden's conservation-area appraisal]. East and higher, Dartmouth Park Road and Dartmouth Park Avenue hold larger semi-detached and detached villas, several still in single-family use. Highgate Road carries the buses and the flats above shops; Swain's Lane runs up past the cemetery to the Village. York Rise anchors a pocket of inter-war flats that behaves nothing like the villas around it [VERIFY the estate's date and ownership].",
    buildings: "Most of the houses share one section: a half-basement or lower-ground floor cut into the slope, a raised entrance reached by steps, and two principal rooms per floor above. That section drives most of the work. The kitchen normally sits in the lower-ground rear, where the party and rear walls are retaining ground on the uphill side, so damp management, floor levels and a workable extract route are settled before a layout is drawn. Bathrooms are usually later insertions above the back addition, on shallow joists that were never sized for stone. Lime plaster on brick, lath-and-plaster ceilings, pine boards and horned sashes are the standing fabric, and previous refits have often buried services in them.",
    access: "Gradient governs the handling here. Material comes off the tail lift onto a slope, so drops are staged rather than tipped, and a skip needs a level bearing wherever it sits. Steps up to the raised front door, with a lightwell beside them, mean baths and carcasses are walked round to a side or rear entrance where one exists. Highgate Road is a bus corridor and a poor unloading point; the residential streets are permit-held by early morning [VERIFY the zone code and hours].",
    extraFaqs: [
      {
        q: "Our kitchen is at lower-ground level and the back wall holds the slope. What does that change?",
        a: "It changes the order of work. The wall retaining ground on the uphill side is surveyed before anything is specified, and the floor build-up, damp management and the extract route out to a permitted position are settled first. Cabinetry and services then follow the room as it actually is. We will not fit a new kitchen over a moisture problem and decorate the evidence away.",
      },
      {
        q: "Can the bathroom above the back addition take a stone or tiled floor?",
        a: "Sometimes, and the joists decide it. Back-addition bathrooms in these houses sit on shallow spans that were sized for boards and a bath, not for a bedded stone floor. We check span, deflection and the existing waste run before a finish is chosen, and where the floor will not take the weight we specify a lighter build-up instead [VERIFY any structural input needed on the specific house].",
      },
    ],
  },
  "east-finchley": {
    streets: "The High Road runs the length of the neighbourhood, with flats over the shops and the station and Cherry Tree Wood halfway along. East of it, the streets climbing toward Fortis Green and Muswell Hill are Edwardian bay-fronted terraces and semis. West, toward the Suburb boundary, plots widen: Creighton Avenue and the roads off East End Road hold inter-war semis and detached houses on generous frontages, and The Bishops Avenue sits at the far edge on a different scale altogether [VERIFY which of these addresses fall inside N2 rather than the Suburb]. The cemetery frontages and the streets nearest the North Circular are quieter and later again.",
    buildings: "Two plans dominate. The Edwardian terrace gives a front bay, a rear reception and a narrow outrigger holding the original scullery, with the bathroom added above it or carved out of the small bedroom. The inter-war semi gives a wider frontage, a kitchen in the rear corner on a solid concrete floor, and a bathroom over the hall with a side window. Fabric is hard wall plaster rather than lime in the later houses, softwood casements, and steel casements where they survive, with picture rails and tiled fireplaces where nobody has stripped them. Most kitchens here are on their second or third refit, which usually means concealed pipework of unknown age behind the units.",
    access: "Where there is a hardstanding, the tail lift can work off the highway entirely and a skip can stand on the drive — that changes the method more than any licence does. Where there is not, Barnet issues the permit. The High Road is the exception: bus lanes, timed loading restrictions [VERIFY the hours] and school traffic make a mid-morning drop unwise there. Scaffolding on a semi is agreed with the attached neighbour before it goes up, because the standards land on a shared boundary.",
    extraFaqs: [
      {
        q: "Can you open up the wall between the kitchen and the dining room in an inter-war semi?",
        a: "No. Forming or widening a structural opening is not part of light refurbishment, and that work sits with Hampstead Renovations. What we do is work within the openings that exist: a new kitchen in the rear corner, the services re-run, the solid floor levelled and finished, and the two rooms decorated as one scheme so they read together. We will say at survey which of the two you need.",
      },
      {
        q: "The bathroom is over the hall and it is small. What can actually change?",
        a: "Layout, within the drainage. The WC in these houses usually sits against the wall carrying the soil stack, and moving it takes more room than it gains. Fittings, floor and wall build-up, a properly ducted extract and the position of the door are where the space is found. On a suspended timber floor we set out the waterproofing and the falls before any tiling is ordered.",
      },
    ],
  },
  "frognal": {
    streets: "The name covers more than one road. Frognal itself climbs from Finchley Road to the village, with Frognal Lane, Frognal Gardens, Frognal Rise and Frognal Way branching from it. West of that sit the Redington Frognal streets — Redington Road, Templewood Avenue, Ferncroft Avenue, Heath Drive and Platt's Lane — later, wider, and largely detached and semi-detached red brick [VERIFY the Camden conservation area covering these roads]. East, toward Swiss Cottage, Fitzjohn's Avenue, Arkwright Road and Maresfield Gardens carry tall late-Victorian houses that divide into unusually large flats. Mansion blocks gather at the Finchley Road end. University College School sits on the hill in the middle of all of it.",
    buildings: "Frognal's recurring type is a tall red-brick villa with gables, terracotta dressings and a staircase generous enough to have survived every subsequent change. Ceilings on the raised ground and first floors are high; the top storey, built for staff, is not, and its joists are shallower. Division into flats has left kitchens in former bedrooms and service wings, and bathrooms in dressing rooms and box rooms, which is why a single internal soil chase often serves the whole building. Lath and lime survive behind later skim in the older sections. Original panelled doors, moulded architraves and shutter boxes are usually still there, and are worth repairing rather than replacing on a decoration job.",
    access: "The gradient does most of the work. Loading is easier than in the village, but a long-wheelbase van on Frognal or Redington Road wants a flat spot for the tail-lift, and sack trucks do not behave on a slope. Front gardens are deep, so add the carry from kerb to door. Camden issues the skip and scaffold licences; a skip on a hill needs chocking and a level base [VERIFY the CPZ zone and hours]. School traffic on the hill is heavy at each end of the day.",
    extraFaqs: [
      {
        q: "We are on the top floor of a converted Frognal house — can a new bathroom drain properly?",
        a: "It depends on the distance to the stack and the depth available in the floor. Top storeys in these houses were built for staff, with shallower joists and less room for a fall, so the drainage sets the layout before anything else does. Where gravity will not reach, a pumped waste is a considered decision with the freeholder, not a default [VERIFY the lease and the stack position].",
      },
      {
        q: "Some houses near Frognal Way look modern rather than Victorian — does that change anything?",
        a: "It can. A small number of twentieth-century houses on and around Frognal Way are individually listed, and the listing usually protects the very things a refurbishment touches: window sections, built-in joinery, floor finishes and the openness of the plan. They are not forgiving of standard replacements. We read the list entry first and specify against what is actually there [VERIFY the address and grade with Camden].",
      },
    ],
  },
  "golders-green": {
    streets: "Golders Green Road carries the shops from the station up toward Temple Fortune, and the residential streets hang off it. Immediately behind are Hodford Road, Wentworth Road and Rotherwick Road: close-set Edwardian and early inter-war semis and short terraces with bay fronts and tiled paths [VERIFY the road names for the address]. Hoop Lane, with the cemetery and crematorium along it, divides that grain from the streets running toward the Suburb boundary. West of the station, out along North End Road toward West Heath and Golders Hill Park, plots widen and detached houses appear. The parades on the main roads carry flats above the shops, with purpose-built blocks at the junctions. Garages and hardstandings are ordinary here in a way they are not in the Camden conversions.",
    buildings: "Inside the standard house, the back of the plan is the interesting part. A rear projection once held a scullery and a larder beside the kitchen, and those small rooms are why so many kitchens here have already been combined once. The survey therefore establishes what the dividing wall carries before any layout is drawn: opening a structural wall is not our work and sits with Hampstead Renovations. Bathrooms are upstairs over the hall or the return, on suspended timber floors that flex under a filled bath. Casements, leaded lights, picture rails and panelled doors survive in patches rather than throughout. Ground floors are timber over a ventilated void, so the air bricks matter more than they look.",
    access: "Driveways change the arithmetic. Where a skip can stand wholly on private ground no highway licence is needed and a van unloads off the carriageway [VERIFY Barnet's current requirement]; where it cannot, Barnet licenses both skip and scaffold. On the crescents behind the main road, cars stand both sides and a long wheelbase will not turn, so material crosses the front garden rather than reversing to the door. Scaffolding to a side return usually needs the neighbour's agreement as well as the council's, and is asked for early.",
    extraFaqs: [
      {
        q: "Can the old scullery wall come out to make one kitchen?",
        a: "Sometimes. Where it is a stud partition doing nothing but dividing two rooms, taking it down and making good is ordinary work for us. Where it carries floor or roof load, or a beam would be needed, that is structural and belongs with Hampstead Renovations rather than with this service. We establish which it is at survey and say so.",
      },
      {
        q: "Will you work around Shabbat and the festivals?",
        a: "Yes. Friday finishing times shorten considerably through the winter, and the autumn festivals take out working days in blocks. Both go into the programme at the outset rather than being discovered halfway through, and deliveries are booked around them. Tell us at survey how you want the site left before each break and that becomes part of the method.",
      },
    ],
  },
  "hampstead": {
    streets: "The village core is Heath Street, Hampstead High Street and the lanes running off them — Flask Walk, Perrin's Court, Holly Hill, New End — where frontages are narrow and buildings sit hard on the pavement. Church Row holds a Georgian terrace [VERIFY the build dates]; Downshire Hill and Keats Grove run instead to detached and semi-detached villas behind front gardens. Well Walk, Willow Road and East Heath Road face open ground. West of the core, Redington Road and Templewood Avenue are a later and larger-plotted grain of Edwardian and Arts and Crafts houses [VERIFY the Redington Frognal conservation-area name and boundary]. Rosslyn Hill and Fitzjohn's Avenue carry mansion blocks and converted villas on the approach from Belsize.",
    buildings: "Three fabrics recur. The Georgian and early-Victorian terraces have lime plaster on riven lath, panelled shutters in splayed reveals, box sashes and wide softwood boards; walls are rarely square, so a fitted run is scribed rather than dropped in. The later villas give taller principal rooms, deeper cornices and heavier joinery, with kitchens historically at lower-ground or rear-closet level and bathrooms formed afterwards out of dressing rooms and landings. Mansion flats on the approaches keep compact original service rooms. Almost every interior has been altered at least twice, often with a gypsum skim over lime and chipboard over the boards, so early work is largely finding out what is still original and what is only holding a previous fit-out up.",
    access: "Nothing here is a straightforward drop. Heath Street and the High Street carry through traffic and shoppers, so material arrives on the lanes behind and is carried in. Many lanes have no off-street parking and no room for a long-wheelbase van, and some sections are footway only [VERIFY the restriction on the specific lane]. Camden licenses skips and scaffolding; a scaffold on a narrow village pavement can need a footway licence too [VERIFY]. Controlled parking applies across the village [VERIFY the CPZ code and hours].",
    extraFaqs: [
      {
        q: "We have lime plaster on lath. Does all of it have to come off?",
        a: "Usually not. Sound lime plaster that has only lost its key in patches can be re-fixed and made good in like materials; a hard gypsum skim across the whole wall is quicker but it changes how the wall behaves and cracks along the laths later. We open a small area, test adhesion and specify repair or replacement wall by wall rather than room by room.",
      },
      {
        q: "The floors slope and the walls are out of true. Will a fitted kitchen work?",
        a: "It will, provided the survey measures the fall instead of assuming a level floor. In village houses of this age we set the run off the worst corner, pack and level the carcasses, and scribe end panels and worktops to the wall. Skirting, cornice and tiling are then cut to the same reference, so nothing in the finished room reads as an obvious wedge.",
      },
    ],
  },
  "hampstead-garden-suburb": {
    streets: "The Suburb is read in sections rather than in single streets. The early cottage groups around Asmuns Place, Hampstead Way and Willifield Way are small terraces set to greens [VERIFY these street names and the building sequence]. Central Square and the roads about it, including Erskine Hill and Meadway, carry the larger and more formal houses [VERIFY]. Toward the Heath Extension the plots widen again on the western roads [VERIFY]. Beyond the arterial road the later inter-war streets are recognisably Suburb in idiom without always falling inside the same boundaries, which is why the Trust map and the conservation-area map are both checked before anything is said about consent.",
    buildings: "Roughcast render over brick, steep tiled roofs, tall chimneys and small-pane casements, many of them leaded. Inside, the cottages have low eaves that cut into the upper rooms, narrow stairs, a rear scullery that became the kitchen, and a single bathroom placed over the hall or the stair. Larger houses give better proportions on the same fabric. Kitchens and bathrooms have nearly all been replaced at least once; the window openings, the chimney positions and the roof pitch have not, and those are what a new layout has to obey. Gypsum skim and vinyl paint applied over lime-based walls is a common inherited problem, because the wall was built to dry outwards.",
    access: "Closes, greens and grass verges are not loading bays, and hedges, walls and hardstandings sit under Trust control as well as Barnet's [VERIFY the current Trust guidelines for the item]. Skips go on the drive where there is one and are licensed from Barnet where there is not. Turning heads on the closes are tight for a long van, so deliveries are sized to the street. Scaffolding to a front elevation may need Trust consent alongside the Barnet licence [VERIFY].",
    extraFaqs: [
      {
        q: "Our kitchen windows are small leaded casements. Can we still get a usable layout?",
        a: "Yes, but the design starts from the opening rather than from a showroom plan. Low sills limit where worktops and tall units can sit, and daylight has to be supplemented properly rather than left to one ceiling fitting. Enlarging an opening is not an internal decision here: it needs Barnet consent and, where the Scheme of Management applies, separate Trust consent [VERIFY for the property].",
      },
      {
        q: "We have damp patches on an external wall. Will redecorating solve it?",
        a: "No, and painting over it usually makes the wall worse. Roughcast render on a solid wall is meant to let moisture move outwards; gypsum skim and vinyl paint applied inside stop it doing so. We investigate the source before specifying anything and use breathable finishes where the construction calls for them. Repairing the render itself is external work, under Barnet and Trust control [VERIFY].",
      },
    ],
  },
  "hampstead-heath": {
    streets: "The Heath edge is three pockets rather than one neighbourhood. Around South End Green, late-Victorian terraces climb South Hill Park, Parliament Hill, Nassington Road and Tanza Road — red brick, gabled, stepped up the slope toward the ponds [VERIFY build dates street by street]. West of the ponds the fabric is earlier and lighter: Downshire Hill, Keats Grove and Willow Road hold stucco and stock-brick villas set back behind front gardens. The Vale of Health is separate again, a pocket of cottages and later houses inside the Heath itself, reached by one lane off East Heath Road. Well Walk and Christchurch Hill make the transition up into the village.",
    buildings: "Two plans recur. The terraces above South End Green are three storeys over a semi-basement, with a closet wing at the back: the kitchen now sits either in that wing or in the lower-ground room, and the bathroom is usually on the half-landing above it. The villas nearer Downshire Hill are shallower and more generous, with lime plaster on lath, shutter boxes, wide boards and sashes that have been painted shut more than once. Most have had a rear kitchen enlarged at some point by a previous owner. That earlier work, not the original fabric, is usually what a survey has to correct — falls to the rear, boxed services, and extract routed to whichever wall was nearest.",
    access: "Vehicles are the constraint here, not the rooms. The Vale of Health is reached by a single lane with no turning space, so materials are transferred to a small van or barrowed in. On East Heath Road and the Parliament Hill streets, a skip or scaffold on a Heath frontage needs a Camden licence and is seen from open ground, so placement is agreed before it is ordered. Pond Street carries hospital traffic, and fine weekends fill South End Green [VERIFY current parking controls and hours on the street].",
    extraFaqs: [
      {
        q: "Does a house on Downshire Hill or Keats Grove need listed-building consent for internal work?",
        a: "It can. Several of the early houses on those streets are individually listed, and listing covers the interior as well as the elevation [VERIFY the entry for the address]. Chimneypieces, staircases, panelled doors and the plan form itself can all be caught, where a conservation area alone would only reach the outside. We check the list entry before a layout is drawn, not after.",
      },
      {
        q: "The house is cut into the slope down to the Heath — does that affect a kitchen at lower-ground level?",
        a: "Usually yes. Where a rear or side wall is retaining ground, the room behaves differently from a basement that is open on both sides: moisture arrives through the structure rather than through the air, and no amount of extract fixes it on its own. We survey the wall as found, establish where water is coming from, and specify the build-up accordingly before any units are ordered.",
      },
    ],
  },
  "highgate": {
    streets: "The Village sits on the plateau: South Grove, Pond Square, the High Street and The Grove, where Georgian frontages meet the pavement directly. West of it the ground falls away through Highgate West Hill, Millfield Lane and Fitzroy Park, large houses on wooded plots looking toward the ponds. Going the other way, North Road and Southwood Lane mix eighteenth-century cottages with later terraces, and the Highpoint blocks stand further up North Hill [VERIFY the street and the listing grade]. Cholmeley Park and the streets dropping toward Archway Road are Victorian and Edwardian, with a higher proportion converted. Holly Lodge is separate again, mock-Tudor flats on their own layout [VERIFY the estate's dates].",
    buildings: "A Village house is often listed, which makes internal work a matter of consent rather than preference: panelled reveals, box sashes set behind their frames, closed-string stairs and lime plaster are the fabric, and replacing them instead of repairing them is not a neutral decision [VERIFY the listing for the address]. The slope does the rest. Houses on the hills are built into the ground, so a room level with the garden at the back can be half a storey down at the front, and drainage falls the way the land does. Kitchens began as service rooms at the lower rear and have usually been moved once already. In the inter-war flats, floors are solid and the riser fixes the plan.",
    access: "Gradient decides the vehicle here. Swain's Lane and Highgate West Hill are not roads to reverse a long wheelbase down, and Village parking is short-stay. Licensing splits with the boundary: a skip on a Camden street and one a few streets away in Haringey are separate applications [VERIFY which side the address falls]. School traffic on North Road and Highgate Hill concentrates twice a day in term time [VERIFY the schools and their hours]. A scaffold near a protected tree involves the tree officer first.",
    extraFaqs: [
      {
        q: "The house is listed. Does that really reach as far as a new bathroom?",
        a: "It can. Listed status covers the interior as well as the elevations, so moving a partition, cutting joists for a waste run, or taking out a chimneypiece or a length of original skirting may each need listed building consent [VERIFY the listing and its extent]. Fittings can generally be renewed. Which parts of the room are original is the first thing to establish.",
      },
      {
        q: "The kitchen is at the lower rear and the garden sits above floor level. What does that mean?",
        a: "That wall is holding back ground, and it will behave like it. Before cabinets are chosen we want to know how the wall was built, whether anything has been tanked before, and where the room's air comes from. Resolving that is separate work from the kitchen and far cheaper done first. Alterations to a retaining wall sit with Hampstead Renovations.",
      },
    ],
  },
  "kensal-rise": {
    streets: "Chamberlayne Road takes the shops, the buses and the flats above them, and the residential streets come off it in a regular comb. College Road, Clifford Gardens, Bathurst Gardens and Wrentham Avenue are the type: two-storey bay-fronted terraces of the 1890s and 1900s, built as a speculative grid and now a mix of whole houses and conversions [VERIFY the individual street names and their dates]. Toward the cemetery and the Harrow Road the terraces give way to later blocks and a wider mix of periods. Nothing here is villa scale — the whole neighbourhood was built to one modest, repeating pattern, which is why a survey of one house tells you a great deal about the next.",
    buildings: "One section repeats down every street: a bay-fronted front room, a middle room, a single-storey back addition that was the scullery, and two or three bedrooms over. Many have since gained a rear extension, a loft conversion or both [VERIFY on the individual house], so the fabric a survey meets is layered — original stock brick and lath and plaster at the front, someone else's blockwork, flat roof and re-routed waste at the back. Kitchens sit in the extended rear; bathrooms are either over the back addition or upstairs in the old box room. Shallow joists, tiled hall floors and original front sashes are what survives and what gets protected.",
    access: "There is no back way in. These terraces have no side alley, so every bath, carcass and bag of waste travels through the front door, over the original tiled path and hall, and up a stair that turns. Boarding for path, hall and stair goes in on day one. On-street, the side roads are parked to capacity by the morning commute, so a suspended bay is arranged rather than assumed [VERIFY the zone hours], and waste is bagged out where a skip cannot be licensed.",
    extraFaqs: [
      {
        q: "Our house already has a rear extension and a loft conversion. Does that make a kitchen refit simpler or harder?",
        a: "Neither by default, but it changes what we check. Work built by somebody else is surveyed as found: where the waste actually runs, whether the flat roof has drained properly into the existing gully, how the extension floor meets the original level, and what the last fitter concealed. We record all of that before ordering, so the programme is not rewritten in week two.",
      },
      {
        q: "Can the original tiled hall path and floor survive a full refurbishment?",
        a: "Usually, if it is protected from the first delivery rather than the first breakage. Encaustic tiles in these halls are laid on lime and sand and crack under point loads, so we board over them and route heavy items with that in mind. Missing or loose tiles are lifted and reset where matches can be found; where they cannot, we say so rather than substituting something close.",
      },
    ],
  },
  "kentish-town": {
    streets: "Kentish Town Road and Fortess Road carry the traffic; the housing is on what runs off them. Leighton Road, Lady Margaret Road and the streets toward Torriano are broad early- and mid-Victorian terraces [VERIFY these street names]. Kelly Street is a cottage terrace of quite a different scale [VERIFY]. West of the high street, Prince of Wales Road and Malden Road run toward Queen's Crescent and Gospel Oak, where Victorian fabric is interrupted by post-war blocks and later infill. Highgate Road rises north-east toward Dartmouth Park and the houses grow with it. Former workshops and yards behind the street frontages have been turned into flats, which is a stock type Hampstead simply does not have.",
    buildings: "Two grains sit side by side. The early terraces are stock brick with stucco door surrounds, a lower-ground floor behind a front area and a raised ground floor above; the later ones are bay-fronted with a rear return. Lower-ground rooms are where kitchens usually end up, with restricted head height, a solid or part-solid floor, and a light well doing all the ventilation work. Bathrooms are half-landing rooms carved out at some point in the last century. Lath and lime survives behind boxing more often than the previous refit suggested, and shower trays laid over springy timber are a recurring find.",
    access: "Camden permit bays fill by mid-morning and the high street is no place to leave a skip, so a bay is usually suspended and licensed rather than found [VERIFY the current Camden suspension and skip-licence process]. Queen's Crescent market days close part of that street [VERIFY the market days]. Where the kitchen is at lower ground, material goes down a narrow area stair rather than through the house, and the front area is boarded before the first delivery arrives.",
    extraFaqs: [
      {
        q: "Our kitchen is at lower ground, off the front light well. How is extract handled?",
        a: "Carefully, because the obvious route is often the wrong one. A grille punched through a front elevation is visible from the street and may need consent in a conservation area [VERIFY the designation for the address]. Where a rear or light-well route works, that is preferred, with ducting sized so the fan moves air instead of just making noise. Recirculation is a fallback, not a plan.",
      },
      {
        q: "The floors in our terrace slope noticeably. Do you level them?",
        a: "We measure them and tell you the range before anything is ordered. Settlement over the life of a Victorian terrace is not a defect to be chased out of the house. Where tiles or a rigid floor are going down the deck has to be flat, so we pack or use a levelling compound and adjust door heights and skirtings to suit. Where boards are being kept, the fall usually stays.",
      },
    ],
  },
  "kilburn": {
    streets: "The High Road runs north into Shoot-up Hill, and the neighbourhood changes as you cross it. On the Camden side, Priory Road, Iverson Road and the streets toward West Hampstead are steady Victorian terraces, some stuccoed as they approach Belsize Road [VERIFY these street names]. West of the High Road, Willesden Lane and the roads toward Brondesbury and Kilburn Park mix large Victorian houses, inter-war blocks and post-war estate housing, and South Kilburn regeneration has redrawn parts of it again [VERIFY the current phase]. Quex Road and Messina Avenue sit between the two [VERIFY]. Above the High Road shops there is a whole residential layer with its own street doors and stairs.",
    buildings: "Three storeys over a lower ground, stucco at the base and brick above, is the Camden-side pattern; the Brent side carries more red brick and more purpose-built flats. What defines the interiors is subdivision. Many of these houses were cut into small flats through the twentieth century, so a kitchen occupies a former bedroom, a bathroom occupies a former cupboard, and the waste crosses a floor inside a boxed duct to reach the stack. Original cornice and joinery survive in patches, usually in the front rooms. The first hour of a survey goes on separating original structure from later stud, because it changes layout, acoustics and drainage all at once.",
    access: "Two boroughs, so the skip licence follows the address rather than the neighbourhood name. The High Road is a bus and delivery route and a poor default for a skip or a loading stop [VERIFY the current red-route and loading restrictions on it]. Flats above shops usually have one narrow street door and a long stair, and working over a trading business means agreed hours and a written method for deliveries. Side streets are controlled on both sides, under different permit rules [VERIFY the zones].",
    extraFaqs: [
      {
        q: "Our flat was subdivided years ago. How do you tell original walls from later partitions?",
        a: "By opening up in a controlled way and reading the evidence: the direction of the joists, whether the plaster is lime on lath or plasterboard, how the wall meets the cornice, and where the stack actually runs. That tells us what can move within a light refurbishment. If a wall turns out to carry load we stop and say so, because structural work sits with Hampstead Renovations.",
      },
      {
        q: "We are above a shop on the High Road. Can work happen during trading hours?",
        a: "Some of it. Noisy operations such as lifting floors, cutting tiles and breaking out are scheduled around the business below and agreed in writing with the freeholder or the tenant first. Everything arrives through one street door and up a stair, so deliveries are broken into carryable loads rather than dropped on the pavement as a pallet and left there.",
      },
    ],
  },
  "maida-vale": {
    streets: "The neighbourhood divides on materials. South and west, around Warwick Avenue, Warrington Crescent, Randolph Crescent and Clifton Gardens, the building is cream Italianate stucco — tall terraces and paired villas, most long since divided into flats [VERIFY the mid-nineteenth-century build dates]. Further north, along Elgin Avenue, Lauderdale Road, Delaware Road, Ashworth Road and Biddulph Road, the palette turns to red brick and terracotta and the purpose-built blocks take over [VERIFY the individual block names]. Clifton Road and Formosa Street carry the shops. Blomfield Road and Maida Avenue face the canal, and Shirland Road runs off toward the Harrow Road end, where the stock mixes again.",
    buildings: "A mansion flat of this period is planned around a corridor: principal rooms to the front, a kitchen and small back room off what was the service stair, bathroom and separate WC off the hall. Risers sit in ducts serving every flat in the column, so a layout is really an argument about how far a waste run can travel before it loses fall. Floors between flats are usually timber joists, which is why a bathroom here needs a full waterproofing system and an acoustic layer rather than a mat under the tiles. The stucco houses behave differently — lower-ground kitchens, lightwells, taller rooms — and their fabric is lime plaster and softwood joinery throughout.",
    access: "The wide avenues take a skip and a scaffold more easily than most of our patch, provided the licence is in place and a bay is suspended [VERIFY the Westminster process and the CPZ hours for the street]. The constraint is inside the building: polished common parts, one shared front door and a lift with a stated load, so protection boards and agreed delivery windows come before any material arrives. Canal-side streets have limited turning, and a towpath frontage is not a delivery route [VERIFY].",
    extraFaqs: [
      {
        q: "Can we lay stone or porcelain over the original timber floors?",
        a: "That depends on deflection and on the lease. Timber joists move, so stone or large-format porcelain needs an uncoupling layer or a rigid overboard, and the added weight has to be considered before anything is ordered. Many leases in these blocks also restrict hard flooring in favour of carpet, or require a specified acoustic underlay [VERIFY the clause in your own lease].",
      },
      {
        q: "Where can a kitchen extract actually go in a mansion block?",
        a: "Rarely anywhere new. Cutting a fresh grille through a principal elevation is both a planning question inside the conservation area and a freeholder question, so the practical options are an existing vent or duct, a route to a lightwell or rear elevation, or a recirculating hood with proper carbon filtration. We establish which is available at survey, not after the units are ordered [VERIFY the duct route in your block].",
      },
    ],
  },
  "muswell-hill": {
    streets: "The Broadway is the hinge: Edwardian parades with flats above, and ground that falls away from it in every direction. Behind the parade the wide red-brick avenues people picture when they say Muswell Hill run off it in a set [VERIFY the street names such as Queens Avenue, Princes Avenue and Dukes Avenue, and the Edmondson attribution]. North-west, Fortis Green and Fortis Green Road hold late-Victorian villas alongside later semis [VERIFY]. Colney Hatch Lane runs north and Alexandra Park Road east toward the park [VERIFY both]. Muswell Hill Road drops south past Highgate Wood into a different grain again, and the Rookfield Estate off it is a small planned pocket with its own character [VERIFY].",
    buildings: "Red brick with roughcast gables and terracotta dressings is the standard local recipe, and inside it means deep bays, wide halls with dado and picture rails, and a chimney breast in nearly every room. The original kitchen was a rear scullery off a return; in most houses that wall came down years ago, so what we inherit is a long rear space with two floor build-ups and a junction where damp likes to bridge. Bathrooms usually sit over the return or in a rear bedroom. Plaster is lime on lath under later gypsum patches, sashes and casements carry decades of paint on the beads, and boards have been cut about for pipe runs more than once.",
    access: "There is no Underground station, so residents keep cars and the permit bays fill early [VERIFY the Haringey CPZ zone and hours]. Gradient does the rest: a long-wheelbase van on a steep side street is a poor plan, and material is better split into smaller drops. Skip placement is licensed by Haringey and is mostly a question of finding level ground. Behind the parade, off-street drives are more common here than on the inner-Camden streets, and where a house has one it settles the delivery problem early.",
    extraFaqs: [
      {
        q: "Our house already has a rear extension. Can you re-fit the kitchen inside it?",
        a: "Yes, and it is a common brief here, because so much of the Edwardian stock was extended decades ago. We survey the existing structure first: the floor build-up either side of the original rear wall, the damp detail at that junction, the roof insulation, and where services currently run. Those findings set the layout. We do not form new openings or alter structure, and that work sits with Hampstead Renovations.",
      },
      {
        q: "Do you work in the flats above the Broadway parades?",
        a: "Yes, though the method differs from a house on the slope. Access is a shared street door and stair over a trading business, so delivery times and noisy operations are agreed in advance. Extract normally has to reach a rear light well rather than the parade elevation, and the conservation area applies to the frontage [VERIFY the boundary for the building]. Floors between flats are separating floors, so acoustic detail matters.",
      },
    ],
  },
  "primrose-hill": {
    streets: "Regent's Park Road bends through the middle and sets the pattern, shops and stucco at the southern end, plainer stock brick as it climbs. Off it, Chalcot Square, Chalcot Road and Fitzroy Road run three and four storeys over a lower ground floor, most of them long since split into flats. Gloucester Avenue takes the eastern edge beside the railway. North of the slope the scale changes again: Elsworthy Road and King Henry's Road hold detached and semi-detached houses on wider plots, a good number still in single occupation. The terraces looking onto the hill itself carry the most publicly visible frontages in the neighbourhood [VERIFY which elevations face open space at the address].",
    buildings: "The house that repeats is a mid-nineteenth-century terrace: stock brick over a stuccoed ground floor, four levels including a lower ground that opens to a front area, and a closet wing at the back. Survival is uneven. Lime plaster, run cornices, counterweighted sashes and boarded floors are common on the upper storeys, while the lower ground is almost always the most altered part of the house. Kitchens sit down there with retained earth behind at least one wall, which is why a re-fit starts with moisture and ventilation and only then with cabinets. Bathrooms are usually in the closet wing on a half-landing. Previous work has often put gypsum and impermeable paint onto walls that need to breathe.",
    access: "Entry is either up a flight from the pavement or down into a front area, so materials are carried rather than wheeled. The streets are narrow, largely single-file, and under Camden control with residents' permits [VERIFY the zone letter]. Fine weekends bring visitor traffic onto the slope, which makes Saturday deliveries unproductive. Skips need a Camden licence, and neighbours told before the lorry arrives; a front scaffold generally has to bridge the area railings rather than stand on them.",
    extraFaqs: [
      {
        q: "There are vaults under the front pavement. Can they be brought into the kitchen?",
        a: "Rarely as habitable space, and never as a casual extra. Pavement vaults are unheated, poorly ventilated and often damp, and the pavement above is highway rather than yours [VERIFY ownership and any licence for the address]. Cleaned out, dried and lit, they make useful storage. Opening them up structurally is not our work and sits with Hampstead Renovations.",
      },
      {
        q: "Does repainting the stucco front need permission here?",
        a: "Not always, but this is not an area where permitted development can be assumed. Camden's controls on this conservation area reach further than the national default, and colour, finish and the condition of the render beneath all matter to the street [VERIFY what the direction removes for your address]. We establish the position before external decoration is specified.",
      },
    ],
  },
  "queens-park": {
    streets: "North and east of the park the streets run as a regular comb, Chevening Road, Kingswood Avenue, Milman Road and their neighbours, bay-fronted terraces of two and three storeys with tiled paths and modest rear gardens [VERIFY the road names for the address]. Salusbury Road cuts across with shops and flats above them; Harvist Road takes the southern edge beside the railway. Across the borough line the pattern is entirely different: the Estate is a tight grid of low brick cottages on streets lettered in sequence, Alperton through to Peach [VERIFY the full run and the Estate's boundary], built to one design rather than plot by plot. Brondesbury Park, to the north-east, is later and wider, with detached and semi-detached houses.",
    buildings: "Brent-side houses follow one plan with little variation: a bay-fronted terrace with a rear back-addition, the kitchen at ground level and the bathroom directly above it, both narrow, both served by a soil stack on the outside rear wall. That stacking is why a bathroom re-fit here is also a question about the kitchen ceiling below it. Walls are lath and plaster on lime, floors are suspended timber over a ventilated void, and the chimney breasts are usually still in place. Estate cottages are smaller-boned: lower ceilings, tighter stairs, decorative brick and joinery worth the trouble of keeping, and some hold two dwellings behind what reads from the street as a single house [VERIFY the arrangement on the property].",
    access: "One neighbourhood, two parking regimes: Brent's controlled hours and Westminster's do not match, and a bay suspension arranged with one council is no use on the other [VERIFY the zones and hours either side of the boundary]. Skip and scaffold licences split the same way. Salusbury Road narrows around the station, and the Sunday market draws traffic to its middle stretch [VERIFY the market's day and location]. On the Estate, houses meet the pavement directly, so a skip takes a bay and the bay is suspended in advance.",
    extraFaqs: [
      {
        q: "The bathroom is directly above the kitchen. What does that change?",
        a: "The sequence and the waterproofing. A tray or a bath on a suspended timber floor moves, so the wet area is built to a documented system and the joints are detailed for that movement rather than trusted to sealant. It also puts the kitchen below out of use for part of the work, and any old staining on that ceiling is worth showing us before we start.",
      },
      {
        q: "Where can a cooker hood vent to in a back-addition kitchen?",
        a: "Usually straight through the rear wall on the shortest run, with a grille chosen to suit the elevation rather than whatever arrives in the box. Long ducts through the house lose performance and collect grease. Where the rear elevation falls inside a conservation-area audit, the grille position is worth settling first [VERIFY which designation applies to the address].",
      },
    ],
  },
  "regents-park": {
    streets: "The Outer Circle carries the names that define this address: Cumberland Terrace, Chester Terrace, York Terrace, Cornwall Terrace, Hanover Terrace and Sussex Place are compositions facing the park rather than ordinary streets [VERIFY listing grade and terrace name for the property]. Park Square and Park Crescent close the southern end at Marylebone Road. Behind that line the grain drops away sharply. Albany Street is a working corridor, and east of it the Regent's Park Estate — Munster Square, Cumberland Market, Clarence Gardens — is post-war Camden housing on an entirely different plan [VERIFY the estate boundary and its build period]. Park Village East and Park Village West hold smaller stuccoed villas between the two.",
    buildings: "A terrace house on the park is deep, narrow and vertical: service rooms in the basement, a raised ground floor, full-height sashes and shutters to the principal room on the first floor, and progressively lower ceilings above. Where such a house has been divided, kitchens have landed in former service or dressing rooms and bathrooms in the light-well end of the plan, so wastes travel further than anyone would design from scratch. Stucco outside means lime and soft render behind the paint; inside, cornices, chimneypieces and staircases are frequently part of the listing. Wet rooms sit over decorated ceilings that belong to someone else. Sequencing and protection therefore matter as much as the fit-out itself.",
    access: "There is often no kerb to work from. Terrace frontages give onto the Outer Circle, which is a park road with its own vehicle rules and gate hours [VERIFY Royal Parks access arrangements for the frontage], and material is then carried across a front area and down or up steps. Where a Westminster licence for a skip or scaffold is possible at all, the listed elevation behind it sets the standard. In the blocks, the service entrance, the goods lift and the porter's hours decide the day.",
    extraFaqs: [
      {
        q: "Does an internal kitchen or bathroom in a listed terrace need listed-building consent?",
        a: "Often, yes. Listing applies to the whole building, so removing a partition, altering a chimneypiece, cutting a cornice or forming a new opening for services can require consent even though nothing changes on the elevation. Consent is separate from planning and separate again from freeholder or estate approval. We establish which of the three apply before drawings go anywhere [VERIFY the list entry and the freeholder for the building].",
      },
      {
        q: "Can a van stand on the Outer Circle while a kitchen is unloaded?",
        a: "Not as an assumption. The Outer Circle is a park road rather than an ordinary borough street, with its own controls on standing, and gates that are not open at all hours [VERIFY the arrangements that apply to your frontage]. Deliveries are booked into a window, split into loads two people can carry, and scheduled so the vehicle is not sitting there once it is empty.",
      },
    ],
  },
  "south-hampstead": {
    streets: "The core is the grid of 'Gardens' streets between Finchley Road and West End Lane — Compayne, Canfield, Greencroft, Fairhazel, Aberdare and Goldhurst Terrace — tall red-brick and stucco houses of the 1880s and 1890s, most now three or four flats each [VERIFY the dates and the conservation-area boundary]. Priory Road and Broadhurst Gardens fall away to the west. Belsize Road is the mixed-use edge, with post-war estate housing behind it. Along Loudoun Road and Alexandra Road the character changes twice over: villa-scale houses on one side, and the listed Alexandra Road Estate terracing down beside the railway cutting [VERIFY its listing grade and architect].",
    buildings: "Two building types sit side by side. The converted house — four or five storeys over a basement, sliced horizontally into flats — gives tall front rooms on the lower floors, much lower ceilings under the roof, deep cornices in one room and none in the next, and floors that pass sound straight down. Lime plaster, horned sashes and pitch-pine boards survive unevenly through it. The purpose-built blocks give the opposite: consistent room heights, services in the shafts they were built with, and a plan that has barely moved. In both, a flat's wet rooms serve, and are served by, other people's leases, so acoustic build-up and stack capacity are settled before finishes.",
    access: "Converted houses here have no lift. Material for a fourth-floor flat goes up a common stair shared with other households, past original tiling and a shared front door, so protection and delivery timing are agreed with the managing agent or freeholder in advance. The railway cutting stops several streets from connecting through, which matters once a long vehicle is committed. Finchley Road is a main-road frontage with its own loading rules [VERIFY the highway authority and restrictions]; scaffolding to a five-storey elevation needs a licence and the neighbours told.",
    extraFaqs: [
      {
        q: "Our bathroom drains into a stack shared with the flats above and below. Can it be moved?",
        a: "Sometimes, and the answer comes from the stack rather than the plan. A shared soil pipe fixes where a WC can sit and what fall a new run needs, and cutting into it affects flats that are not yours. We survey the existing run, set out what is achievable within it, and put the proposal to the freeholder or managing agent before any first fix begins [VERIFY the lease terms].",
      },
      {
        q: "What can be done about sound transfer between the flats in a converted house?",
        a: "Within a refurbishment, a fair amount. Lifting a floor is the one chance to add an acoustic layer under the boards, and the same applies to a resilient build-up under a new bathroom or kitchen floor. Hard finishes laid straight onto old boards make the problem worse. We set out what the lease requires, what the floor depth allows, and what the result will realistically be.",
      },
    ],
  },
  "st-johns-wood": {
    streets: "Hamilton Terrace, Carlton Hill and Abercorn Place hold the widest villas, set back behind gardens and mostly still houses. Elm Tree Road, Melina Place and Alma Square are smaller, quieter pockets of early building near Lord's [VERIFY the dates and the Eyre estate history]. The High Street, Circus Road and Charlbert Street give the shops and the flats over them. Wellington Road, Prince Albert Road and Grove End Road are lined with the large purpose-built blocks, several of them inter-war rather than Victorian. Boundary Road and Loudoun Road, at the Camden edge, change character again toward later flats. The mews tucked behind these streets are a separate stock entirely [VERIFY the named mews for the address].",
    buildings: "Two building families sit side by side. The villas are brick and stucco with generous halls, panelled doors, tall first-floor sashes and rear kitchens added at some later date, so their plaster is lime in the original rooms and gypsum in the additions. The mansion flats are the more disciplined problem: brick cross-walls that look like partitions and are not, original risers that fix where a sink and a soil pipe can sit, a compact kitchen near the old service stair, and bathrooms stacked one above another through the block. Parquet halls and heavy architraves are common and usually worth keeping. In both types the useful first question is which walls and which ducts can actually move.",
    access: "Work in the blocks is booked rather than simply started: porters set delivery windows, lift use and where a skip may stand, and those conditions are usually tighter than the council's [VERIFY the building's own rules]. Wellington Road carries through traffic and stopping on it is not a loading plan [VERIFY whether it is a red route]. Westminster issues the skip and scaffold licences and controls the bays. On the villa streets a driveway helps, though Lord's event days still change what can reach the door.",
    extraFaqs: [
      {
        q: "Can the wall between the kitchen and the dining room come out?",
        a: "Only once it is established what the wall does. In these blocks the internal cross-walls carry load, and often the flat above as well, so forming an opening is structural work: that sits with Hampstead Renovations and, in a block, with the freeholder's own approval process. Where the wall turns out to be a later stud partition, removing it is straightforward and we will say so at survey.",
      },
      {
        q: "Can a bathroom move to a different room in the flat?",
        a: "Sometimes, but the original stacks run vertically through the whole building and there is rarely a second one to use. Moving a WC off that line means a pumped or macerating solution, a floor build-up to gain the fall, and a written case for the managing agent. We would usually rather improve the bathroom where it stands than argue for a position the building was never planned for.",
      },
    ],
  },
  "swiss-cottage": {
    streets: "The neighbourhood turns around the junction where Finchley Road meets Avenue Road, College Crescent and Adelaide Road. North-east of it, Fitzjohn's Avenue climbs toward Hampstead in tall red brick and stucco, most of it divided into flats a century ago, with Maresfield Gardens and Netherhall Gardens running off at a similar scale [VERIFY whether the address is treated as Swiss Cottage or Frognal]. Avenue Road is the opposite grain: wide plots, detached houses and later blocks set back behind gates. South and west, Belsize Road and the streets toward Boundary Road drop to smaller terraces and post-war blocks [VERIFY the estate names on Adelaide Road]. Above the Finchley Road parades sit flats reached by a street door between shopfronts.",
    buildings: "Two fabrics dominate here and they behave nothing alike. The divided villas are load-bearing brick with lath-and-plaster ceilings, boarded floors and counterweighted sashes; a kitchen usually occupies a former rear bedroom, so its waste finds a stack that was never asked to serve three separate flats. The inter-war and post-war blocks are framed, with solid floors that offer no void to bury a pipe in, windows in metal frames on some estates [VERIFY the original glazing on the block], and bathrooms in the middle of the plan with no outside wall to reach. Earlier refits in both have generally boxed the services in and skimmed over movement rather than correcting it, which is why we open up enough to see the truth before a layout is agreed.",
    access: "Finchley Road through the junction is a Transport for London route, so a frontage there is no place to stand a van or a skip [VERIFY the highway authority for the address]. Side streets sit under Camden controlled parking, with little slack in the working day [VERIFY the zone and hours]. Blocks impose their own delivery bays, lift bookings and working hours; kitchen runs are measured against the lift car before anything is ordered. Camden licenses skips and scaffolding off the main road.",
    extraFaqs: [
      {
        q: "Our flat has an internal bathroom with no window. Can it still be re-fitted?",
        a: "Yes, provided the existing duct is found and kept. In a purpose-built block the mechanical extract runs into a shared shaft, so the replacement fan has to suit that shaft rather than a short run to daylight. Cutting a new opening through an external wall is a freeholder matter and usually a planning one as well [VERIFY the lease and the elevation].",
      },
      {
        q: "The floors are solid concrete. Does that decide where the sink can go?",
        a: "It narrows the options considerably. Without a void under the boards there is nowhere to run a waste at a fall, so a moved sink means a raised plinth, a boxed run along the wall, or a pump. We measure the existing fall from the stack before drawing anything, and we say plainly when a plan cannot be served.",
      },
    ],
  },
  "temple-fortune": {
    streets: "Finchley Road is the public face: a continuous parade of shops with flats above, running north from Golders Green toward Henlys Corner and the North Circular. The gateway buildings at the parade were put up as the western entrance to Hampstead Garden Suburb, which is why the architecture there does not match the housing behind it [VERIFY the buildings' names and dates]. East of the road, Temple Fortune Lane and Hampstead Way rise into the Suburb and change regime entirely. West and south, toward Bridge Lane and Golders Green, the streets are ordinary Barnet housing: inter-war semi-detached and detached brick, bay windows, tiled paths and driveways. Two halves, one postcode, very little in common.",
    buildings: "The inter-war semi has a plan that repeats street after street: front reception, rear dining room, a small kitchen at the back with a side door and a larder, and the bathroom directly above the kitchen. That stacking is useful — the waste is already where it needs to be — but the rear wall, the boiler flue and the side passage set the limits of any new layout. Ground floors are suspended timber over a ventilated void; upper floors are timber too, and both move. Many of these houses have already had the kitchen opened into the dining room and the windows replaced. Matching inter-war skirting profiles and plaster texture is the part of making good people underestimate.",
    access: "Here a skip can often go on the drive rather than the road. Most houses behind the parade have off-street parking, so the highway licence is needed only when the skip or scaffold stands on public ground [VERIFY Barnet's current requirement]. Where it does go on the drive, we check the crossover, the drainage gully and what the surface will carry. On the parade itself, loading is squeezed between bus traffic and shop deliveries, and material for a flat above goes up one narrow stair.",
    extraFaqs: [
      {
        q: "Is the kitchen layout in an inter-war semi fixed by the original plan?",
        a: "Not fixed, but shaped by it. The rear wall, the side door, the boiler flue and the bathroom waste dropping through from above all sit where they sit, and moving any of them has a cost in disruption rather than in drawing. Most workable layouts here keep the wet services on the existing wall and use the width gained from the old larder. We measure before we design.",
      },
      {
        q: "Can working days be set around Shabbat and the festival calendar?",
        a: "Yes. Working days, Friday finishing times and whether Saturdays are used at all are agreed with the household before the programme is fixed, not adjusted once trades are booked. The same applies to festival weeks. It is easier to build the calendar into the sequence at the start than to lose a fitting slot later, so we ask at the survey rather than assume.",
      },
    ],
  },
  "tufnell-park": {
    streets: "Tufnell Park Road is the spine, and the paired villas along it, along Dalmeny Avenue, Anson Road and Carleton Road, are the reason people know the name: stuccoed at ground floor, set back behind front gardens, almost all now two or three flats [VERIFY the individual street names and their conservation-area status]. North and east the grain tightens into plainer two-storey terraces on the streets running toward Junction Road. Brecknock Road and Fortess Road mark the Camden side [VERIFY the borough line on these roads]; Holloway begins where the villas stop and post-war blocks take over. The parade at the station is small — this is a residential neighbourhood with a tube stop, not a high street.",
    buildings: "The villa plan repeats: a side entrance on a half-landing stair, two rooms deep on each floor, and a two-storey closet wing at the back. Conversions have taken that plan and pushed a kitchen into whatever room had a rear wall — often the closet wing, sometimes a former bedroom with no waste anywhere near it. Bathrooms cluster on the half-landings, one above the other, feeding a single external stack. Cornices, ceiling roses, four-panel doors and softwood boards survive in patches; so do the later partitions that created the flats. Any new layout is checked against the stack, the neighbour's ceiling below and what the lease actually permits.",
    access: "Two boroughs: the licence follows the frontage rather than the name. Tufnell Park Road carries buses and is not a loading bay, so vans go onto the side streets, which are permit-held and full by mid-morning [VERIFY the zone codes and hours either side of the borough line]. Few front gardens will take a skip, so it sits on the carriageway with a suspended bay. In a converted villa the route in is a shared front door, a tiled hall and a common stair — all protected before the first delivery.",
    extraFaqs: [
      {
        q: "The upstairs flat's kitchen is in a former bedroom. Can it be moved or improved?",
        a: "Usually improved rather than moved. A kitchen in a former bedroom has no original waste and no natural extract path, so the questions are where the waste can reach a stack at a workable fall, where ducting can leave the building without landing on a controlled elevation, and how much noise the floor passes to the flat below. We answer those before drawing units.",
      },
      {
        q: "What happens to the original cornices and ceiling roses in a refurbishment?",
        a: "They stay, unless they are beyond repair. In these villas the plaster mouldings are usually the only original feature the conversion left intact, so they are protected, cleaned back where paint has clogged the profile, and made good in lime or fibrous plaster rather than filled with a modern compound. Where a section is missing we say what can be matched and what cannot.",
      },
    ],
  },
  "west-hampstead": {
    streets: "West End Lane runs the length of the neighbourhood, but the housing changes with each turning off it. North of Mill Lane the streets named after Greek figures — Achilles, Agamemnon, Ulysses — are small bay-fronted terraces on tight plots [VERIFY the local name used for that group]. Around Fortune Green Road and Hillfield Road the terraces are a little larger and more consistently Edwardian. East of the Lane, Compayne Gardens, Canfield Gardens and Broadhurst Gardens are a different scale altogether: wide red-brick and stucco houses, almost all divided into flats, running toward South Hampstead. South of the station, Iverson Road follows the railway toward Kilburn and the grain tightens again.",
    buildings: "The recurring unit is a bay-fronted terrace with a rear closet wing: two rooms deep at the front, a narrow return behind, and a half-landing bathroom sitting over it. In a converted house that bathroom is directly above someone else's ceiling, so isolation and a documented waterproofing detail matter more than the tile choice. Kitchens take the return, which gives one window, one external wall and a single rear stack to work to. Suspended timber floors, lath ceilings, picture rails and front-bay sashes are the usual original fabric. Most conversions belong to a later phase of stud partitions and boxed services [VERIFY the conversion date for the building], and those boxings often hide the only usable run for new waste.",
    access: "Most terraces here have no side return and no rear gate, so units, baths and waste all pass through the front door and up a shared staircase; protecting the hall and stair is written into the method rather than added afterwards. West End Lane is a poor loading position at any hour, given the three stations. Side streets are permit-controlled and full by mid-morning [VERIFY the CPZ zone and hours], so skips stand on a side street under a Camden licence, with a bay suspension where one is needed [VERIFY].",
    extraFaqs: [
      {
        q: "Our bathroom is on the half-landing, over the flat below. What does that change?",
        a: "Two things. The floor build-up has to carry an acoustic layer as well as a waterproofing system, because the neighbour's ceiling is the underside of your shower tray. And the waste has to reach the rear stack at a fall that a half-landing rarely offers, so tray height and layout are settled by the drainage before any fitting is chosen.",
      },
      {
        q: "Could the kitchen move to the front room?",
        a: "Sometimes, though it is a larger job than it looks. The soil and waste stack is at the back of these terraces, so a front kitchen means a long concealed run under the floor, and extract then has to leave through the elevation most likely to be controlled. We would rather rework the return properly than push services the length of a flat [VERIFY any conservation-area or Article 4 control on the frontage].",
      },
    ],
  },
};
