// Generated by scripts/build-detail-data.mjs — edit the copy here directly;
// re-running the generator overwrites this file.
import type { ComboDetailMap } from "./combo-detail";

export const bathroomDetail: ComboDetailMap = {
  "belsize-park": {
    scopeNotes: [
      "Two rooms account for most of the bathroom work here. One is an ensuite or shower room inserted into a former bedroom in a converted house, where a chimney breast and a long waste branch set the plan. The other is a compact bathroom in an avenue mansion flat on the block's original riser. Both cover strip-out, waterproofing, wastes, electrics, tiling, sanitaryware, extract and decoration; concealing the branch in a tall room is the detail that takes the thought.",
      "Removing a chimney breast to square the room off is not part of it. Breasts carry stacks above and their removal is structural, which puts it with Hampstead Renovations. Nor do we take a lateral conversion as licence to run a waste through a neighbouring demise, or treat a stucco front as a convenient place to end a duct. Where the honest answer is that the room cannot hold a shower without a pump, that is said before the drawing is finished.",
    ],
    processNote: "Paperwork comes before plaster here. Conservation status and any Article 4 are checked against the address, because a duct that must reach a rear elevation changes the layout and not merely the finish. In the avenue blocks the managing agent's licence runs in parallel, and the room is not opened until it is granted. Village streets then set the vehicle and the drop, and the common stair is protected before anything is carried up.",
    consent: "Two consents can apply and they come from different places. Camden controls the exterior: the Belsize Conservation Area covers much of the neighbourhood and Article 4 directions apply to parts of it, so a grille or a duct terminating on stucco is a planning question [VERIFY the boundary and the direction for the address]. Inside, the lease decides. In laterally converted houses the demise often crosses what was once a party wall, so the lease plan is worth reading before a waste moves; the licence to alter is granted by the freeholder or managing agent, not by the council.",
    extraFaqs: [
      {
        q: "Who has to approve an ensuite in a Belsize Park flat before work starts?",
        a: "If the flat is leasehold, the freeholder or managing agent does, through a licence to alter, and that usually needs a layout and a method statement. We can prepare both; the decision remains theirs. Camden comes into it only where the outside of the building changes — a new duct or grille on a controlled elevation. Interior work within the existing room normally sits outside planning. [VERIFY the designation on the address.]",
      },
      {
        q: "There is a chimney breast in the middle of the proposed shower room — what happens to it?",
        a: "It stays. The breast is scribed to and worked around: sanitaryware is set out from it, and the alcoves either side usually make the most sensible positions for a shower or storage. Removing a breast is structural work and not something this service does. Old flues behind the plaster can also draw damp air, so the survey checks whether the opening needs sealing or venting.",
      },
      {
        q: "Do the high ceilings in Belsize rooms make a bathroom easier or harder?",
        a: "Harder, on balance. Height gives room to run a waste at a fall, but the boxing that hides it is at eye level in a tall room and every joint shows. Tiling to a high ceiling also needs access equipment written into the programme, and cornice at that height is fragile. The advantage is real ventilation volume; the cost is that nothing sloppy can hide.",
      },
    ],
  },
  "crouch-end": {
    scopeNotes: [
      "The room is normally a bathroom in a converted house: a half-landing or a back-addition room in an upper flat, with another household directly beneath it and a stair shared with them. Everything follows from that. Floor build-up over a neighbour's ceiling, the position of the single stack the whole house drains into, and where a fan can discharge without pointing at a rear window decide the layout well before finishes are chosen.",
      "Two things are excluded on purpose. We do not cut openings through walls to widen the room, and we do not build or extend a rear addition to make space for one — that work sits with Hampstead Renovations. Nor is the shared stair a site route by default. Protection for the tiled hall, working hours and a drop point on a side street are agreed with the other flats first, not claimed afterwards.",
    ],
    processNote: "In a converted house the lead-in is mostly other people. Consent may rest with a freeholder who is also the neighbour downstairs, a skip needs a Haringey licence on a residential street rather than the Broadway, and the other flats need to know which days are noisy. Those answers set the order: protection to the stair and hall goes in first, breaking-out is grouped into a stated window in the working day, and the room is not opened until the licence and the delivery slot line up.",
    consent: "Conservation designation here bears on the outside of the building, not on a bathroom inside it. Re-fitting an existing room is generally not development, so most of what we do needs no application. A grille, a new soil pipe or a window change on a designated frontage is a different matter, and that consent is Haringey's. [VERIFY whether the address sits inside the boundary and whether an Article 4 applies.] Separately, most upper flats in these converted houses are leasehold: an alteration to shared drainage needs the freeholder's written permission, which is theirs to give, not ours.",
    extraFaqs: [
      {
        q: "What makes one Crouch End bathroom cost more than another?",
        a: "There is no price list on this site. The variables are the ones the survey finds: how far the waste has to travel to reach the house stack, whether the floor needs building up before it can be waterproofed, whether extract needs a new duct route, and the amount of protection a shared hall and stair require. We visit, then write a proposal against a defined scope. 020 7101 3168.",
      },
      {
        q: "The flat below is occupied all day — how is that handled?",
        a: "By agreement rather than apology. Before anything comes out we tell the household below which days involve breaking out, keep the water off for stated periods rather than open-ended ones, and test wastes before the floor is closed. If a connection sits in their ceiling void we ask for access properly and make good what we open. Their ceiling is the first place a bad joint shows.",
      },
      {
        q: "Our bathroom is in the back addition and it is cold and out of square. Can it be squared up?",
        a: "Within the finish, yes; by moving the walls, no. Back-addition rooms in these houses are rarely square and rarely well insulated, so we scribe boards and tiling to what is there and, where floor and wall depth allow, improve the build-up while the room is open. What we will not do is take out or rebuild the wall to correct the geometry.",
      },
    ],
  },
  "golders-green": {
    scopeNotes: [
      "On the Barnet streets the room is nearly always a first-floor family bathroom in a house built between about 1905 and 1935: an original window, a tiled dado behind later boarding, and often a separate WC on the other side of a partition. It sits on suspended timber over a bedroom or a hall. What the survey answers first is what the floor and the joist direction will accept once a fall is introduced under a tray.",
      "Combining that bathroom with the WC next door is not automatically ours to do, and nor is forming a shower room in a bedroom or altering the front elevation. Much of the inter-war stock is cavity-built, so a new duct through an external wall is a detail to get right rather than a hole to punch. On the designated streets near Golders Hill Park a window or a grille becomes a Barnet application [VERIFY the map]. Openings sit with Hampstead Renovations.",
    ],
    processNote: "Two things let the sequence run more cleanly here than in a Camden flat, and one does not. Off-street parking means the strip-out skip and the material drop can often be arranged on the property rather than licensed on the highway, so the front end is shorter. Occupied family houses are the offsetting factor: with the household in residence, the WC provision, the dust route through the landing and the hours are agreed before anything comes out, and second fix is sequenced to give the room back in one piece.",
    consent: "Most of this stock is undesignated, which changes the paperwork rather than the standard. A bathroom renewed inside an existing room is not a planning matter in Barnet. The elevation is different: a replacement bathroom window in an altered design, a new soil vent pipe or a grille on a front wall can all run into permitted-development limits, and on the designated streets around Golders Hill Park into conservation control [VERIFY Barnet's map]. Ownership rarely arises in the houses; in the mansion flats a licence to alter from the freeholder does. Trust rules apply only inside the Hampstead Garden Suburb boundary [VERIFY].",
    extraFaqs: [
      {
        q: "We have two bathrooms. Should they be done together or one after the other?",
        a: "Together is usually shorter overall and means one set of protection, one strip-out and one making-good. One after the other keeps a working bathroom in the house throughout. Which suits you depends on how many people are in residence and whether the two rooms share a waste run. We set both sequences out in the proposal with their programme implications, and you choose.",
      },
      {
        q: "Can the bathroom and the separate WC next door be made one room?",
        a: "Often, but it is answered at survey rather than on the phone. If the dividing wall is a later stud taking no load, removing it is straightforward and the two wastes are usually close enough to rationalise. If it carries anything above, the work is structural and sits with Hampstead Renovations, not with us. We look at what is above that wall before we answer.",
      },
      {
        q: "Does a cavity wall change how the extract is done?",
        a: "Yes. Much of the inter-war stock here is cavity-built, and a fan duct that stops short in the cavity puts warm, wet air into the wall rather than outside. The duct is sleeved through to a terminal on the face, insulated where it crosses a cold void, and set to fall outward. It is easy to get right at first fix and disruptive to put right afterwards.",
      },
    ],
  },
  "hampstead": {
    scopeNotes: [
      "A Hampstead instruction is usually a room already in use: a family bathroom in a village house, or a stacked bathroom in a converted one. It runs from strip-out back to a substrate that can be waterproofed, then falls, wastes, electrics, tiling, sanitaryware, extract and the decoration of the room itself. What decides the work is what the room adjoins — lime plaster, original joinery and a principal stair that has to survive the strip-out and the carry.",
      "It does not include forming new rooms, moving walls or opening up a plan. Village houses tempt people toward knocking a bathroom into a bedroom; that is structural work, and it sits with Hampstead Renovations rather than here. We also do not assume a new grille can land on a front that Camden controls, or that a bath can be carried up an original stair until it has been measured against the turn.",
    ],
    processNote: "The lead-in here carries the checks rather than the site. Listing and conservation status are confirmed from Camden's map before anything is ordered, because a grille position can change the layout. Where the flat is leasehold, the freeholder's paperwork starts then too. On site, the carry is planned before the room is opened: a village lane takes a timed vehicle, and the stair and hall are protected first. Materials are dated before the only bathroom in the house is stripped.",
    consent: "Listing is the first question in the village, not the conservation area. Where a house is listed, internal alterations can require listed building consent in their own right: the listing covers plan form, joinery and panelling, not only the front elevation. Unlisted properties in the Hampstead Conservation Area are controlled on the outside instead, so a new grille or duct terminal is where Camden's interest begins, while a bathroom renewed inside its existing walls usually falls outside planning. Camden grants those consents; a freeholder grants a licence to alter. [VERIFY listing and boundary on the address.]",
    extraFaqs: [
      {
        q: "How long does a bathroom in a Hampstead conversion take from the day you start?",
        a: "Once the room is open, a single bathroom is measured in weeks rather than months. The variables sit before that: confirming listing and conservation status, a freeholder's paperwork where the lease calls for it, and firm delivery dates for tiles and brassware. Whether the house has a second bathroom changes how the programme is written more than the size of the room does.",
      },
      {
        q: "Our village bathroom has an original sash — does it still need mechanical extract?",
        a: "Usually, yes. An opening window is not a substitute for a fan with a route to outside, and in this stock the sash is often painted shut or too small to clear steam from a shower. The window itself stays and is treated as joinery, not as a ventilation strategy. Replacing it is a conservation-area matter and a separate conversation. [VERIFY the designation on the address.]",
      },
      {
        q: "What happens to the lime plaster and joinery around a Hampstead bathroom?",
        a: "Inside the wet zone it comes off, because a waterproofing system needs a substrate it can bond to and old lime is not it. Outside that zone, sound plaster and original architraves stay and are made good rather than stripped for convenience. Where a bathroom sits off a principal landing, the door, the frame and the floor beyond it are protected for the whole programme.",
      },
    ],
  },
  "hampstead-garden-suburb": {
    scopeNotes: [
      "In the Suburb the fabric behind the tiles is rarely original. Bathrooms here have almost all been re-fitted since the houses were built, so a strip-out uncovers somebody's later work in a room that was never planned around a shower. Cottage bathrooms are tight, often under a ceiling that follows the roof, and ventilation decides the layout: one small casement is not an extract route, and a duct has to leave the house somewhere the outside will accept.",
      "The envelope is not ours to change, and that is the whole boundary here. No new window, no rooflight, no soil pipe on an elevation and no opening between rooms to make a larger bathroom — the last of those is structural and sits with Hampstead Renovations. Nor do we assume a place to park. Closes and greens were designed as settings, not as service yards, so the delivery point and the carry are agreed before anything is ordered.",
    ],
    processNote: "One question governs the order of everything here: does any part of the scheme reach the outside of the house. Extract is usually the only candidate, so its route is settled at the start rather than left to first fix. If it stays internal, the programme runs like any other fit-out. If it does not, the Trust and Barnet run in the background while materials are dated, and the room is not opened until both answers exist. Deliveries are planned for a close, not a kerb.",
    consent: "Two separate permissions cover the outside of a Suburb house, and neither covers a bathroom that stays inside a room. Barnet decides planning, including anything the Article 4 direction has taken out of permitted development. The Hampstead Garden Suburb Trust decides consent under its Scheme of Management, which is a property arrangement rather than a planning one, and it applies to properties within its own boundary. So a grille, a pipe or a window can need both, in writing, before work starts. [VERIFY the Trust boundary and current guidance for the specific item.]",
    extraFaqs: [
      {
        q: "What determines the cost of a bathroom in a Suburb house?",
        a: "We publish no prices, because a cottage bathroom under a roof slope and a family bathroom in a free-standing house are not the same piece of work. What moves it is the state of the floor once boards are up, whether the waste can serve the layout you want, whether extract can stay internal, and how much making-good the room needs. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "Does the Article 4 direction affect anything inside the house?",
        a: "Not in itself. Article 4 removes permitted-development rights, and permitted development is about the outside — extensions, roof changes, alterations to the elevations. A bathroom re-fitted within an existing room is not development at all. The moment the work reaches a wall, a roof slope or a window, the direction becomes relevant again, and we check it before opening up rather than afterwards. [VERIFY the current direction with Barnet.]",
      },
      {
        q: "We are in a terraced group of cottages around a close. Does that change how you work?",
        a: "It changes noise and access more than method. Party walls in a grouped cottage carry sound, so breaking out is kept to stated hours and neighbours are told in advance. Vehicles cannot sit where a delivery lorry would elsewhere, so materials come in smaller loads with a planned carry. Inside the room, the floor, the waterproofing and the extract are judged exactly as they would be in a larger house.",
      },
    ],
  },
  "highgate": {
    scopeNotes: [
      "The room we are usually given in Highgate is a first-floor bathroom in a house that has been added to over a century: a former dressing room off the principal bedroom, or a half-landing room over the return. What decides the job is rarely the fixture list. It is the water system — many of these houses are still gravity-fed from a roof tank [VERIFY on the property] — and the cast-iron stack on the rear wall that everything discharges into.",
      "What the instruction stops short of is anything that changes that rear elevation or the plan around it. We do not replace or re-route the external stack, take out a chimney breast to square the room, or form a bathroom where none has existed. In a split-borough conservation area, external pipework and a new grille are consented items [VERIFY with the correct borough], and the access to reach them may sit under a protected tree. Structural work is Hampstead Renovations' side.",
    ],
    processNote: "Before anything is ordered we settle which authority the address answers to, because that decides the skip and scaffold application and how long it takes. That check runs alongside the water-system reading: if the house is on a stored cold-water supply, the shower specification and any pressure work have to be resolved at layout stage, not discovered at second fix. Deliveries are the last variable. A bath crate reaches a village house or a slope villa by a carry we walk beforehand.",
    consent: "Two questions, answered separately. Planning and conservation are the council's, and in Highgate that means establishing whether the address falls to Camden, Haringey or Islington before an application is drafted; a renewed bathroom inside an existing room is not normally an application at all, while a grille, an external waste or a window is. Ownership is the other question: in a converted villa the freeholder or agent grants the licence to alter, and that is who consents to a waste moving through a shared void — not the borough. [VERIFY the authority, designation and tenure for the property.]",
    extraFaqs: [
      {
        q: "Who has to say yes before a Highgate bathroom starts?",
        a: "It depends what you are changing. Inside an existing room, usually nobody beyond you — a like-for-like renovation is not normally a planning matter. Move a waste through a shared void in a converted villa and the freeholder or managing agent grants a licence to alter. Touch the elevation with a grille or external pipework and the borough is involved, which here means confirming whether that is Camden, Haringey or Islington. [VERIFY.]",
      },
      {
        q: "The house has a tank in the loft. Will a new shower work properly?",
        a: "Not on its own. A stored, gravity-fed supply gives you the head the tank height allows, and in a village house that can be modest for a first-floor shower. The options are a pump, a change of hot-water arrangement, or a shower chosen for the pressure that exists. We measure at survey and put the honest answer in the specification rather than at handover. [VERIFY the system on the property.]",
      },
      {
        q: "Is the old cast-iron soil stack replaced as part of the work?",
        a: "Not by default. On these rear elevations it is an external, visible component in a conservation area, and swapping it for plastic is a change to the building's appearance as well as a plumbing decision. We connect to it where it is sound, report it where it is not, and say what consent a replacement would need before it is priced. [VERIFY the designation for the address.]",
      },
    ],
  },
  "kentish-town": {
    scopeNotes: [
      "Kentish Town instructions divide by floor level rather than by house type. Upstairs it is a stacked half-landing room draining to a rear-elevation soil pipe that was added long after the house was built, often serving more than one flat. Downstairs it is a lower-ground room where moisture in the structure has to be settled before any waterproofing is worth putting down. In a converted workshop the floor may be solid rather than timber, which changes the detail, not the requirement.",
      "The instruction stops at the fabric. No wall comes out to enlarge a cramped half-landing, no doorway is cut into the bedroom next door, and nothing is done to the rear addition's structure — all of that sits with Hampstead Renovations. Nor do we take on a wider damp problem as part of a bathroom. If the survey finds a source outside the room, it is reported as its own item rather than buried under tanking and a tiled finish.",
    ],
    processNote: "The sequence here bends around moisture and around neighbours. In a lower-ground room readings are taken and a source identified before a waterproofing specification is written, because the substrate decides the system and the system decides the tile. Above ground the variable is the shared hallway: Camden's skip licence, the carry past other front doors and the working hours are agreed with the building before the room is opened. Materials are dated after those two answers, not before.",
    consent: "Two different permissions get confused here. Camden grants planning and conservation-area consent, and its designations run street by street through Kentish Town and up toward Dartmouth Park, so the frontage matters and the interior usually does not. [VERIFY the named area for the address.] The freeholder or managing agent grants a licence to alter, and in a converted terrace that is the permission that actually bites: a rear soil pipe, or a waste that also serves the flat above, is shared fabric, and altering it is not a private decision.",
    extraFaqs: [
      {
        q: "Do I need my freeholder's permission for a bathroom in a converted flat?",
        a: "For a like-for-like re-fit within the room, often not, though many leases require notice. For anything that moves a waste, cuts a new duct or touches the rear soil pipe, almost certainly. We can prepare drawings and a method statement for a licence to alter, but the permission is the freeholder's or the managing agent's to grant. We do not start strip-out while that sits outstanding.",
      },
      {
        q: "There is a shower room in the lower ground that smells damp. Is that a bathroom job?",
        a: "Partly. The room can be rebuilt, but the smell is usually telling you about the structure behind it rather than the seals in front of it. We take readings, look for the source and set that out as a separate item with its own decision. Waterproofing installed over a wet wall traps the problem and fails later. We would rather say so before you choose tiles.",
      },
      {
        q: "Half the street is Victorian terrace and half is a later infill block — does that change the bathroom?",
        a: "It changes the floor and the drainage, which is most of the job. A Victorian conversion gives timber joists over a neighbour and a waste run added later on the back wall. A later infill block usually gives a solid floor, a designed riser and a managing agent with rules about hours and common parts. The finish can look identical; the method behind it is not.",
      },
    ],
  },
  "kilburn": {
    scopeNotes: [
      "What decides a Kilburn bathroom is what sits under the floor and who else uses it. In a Victorian conversion east of the High Road that is joists and a waste added to the back wall. In a purpose-built block west of it that is more often a solid floor and a boxed riser that is not ours to open. Above a shop it is a commercial ceiling, a narrow stair, and an extract route with nowhere obvious to go.",
      "It is a fit-out, not a conversion of the building. We do not open the riser casing in a block, cut into a shop's ceiling, alter a shopfront, or take a wall out to gain a shower enclosure; that last one sits with Hampstead Renovations. We also make no promise about the drop until the borough is confirmed and the stair measured. A bath that will not turn on a half-landing is found at survey, not on delivery day.",
    ],
    processNote: "Everything in the lead-in starts with an address check. Camden or Brent decides whose skip licence and whose conservation map apply, and that answer arrives before any date is offered. Where the flat sits over a shop, access is negotiated with the occupier below and the noisy work is placed away from their trading hours. In a managed block the agent sets hours and the lift rules. Only then is the strip-out week fixed, because the room should not be open while an access agreement is still being written.",
    consent: "Kilburn needs the council settled before anything else, because Camden and Brent run separate conservation maps and separate licensing, and designation here covers selected streets rather than the neighbourhood. [VERIFY both maps for the address.] Inside an existing room, a bathroom is usually not a planning matter for either. The moment a duct or a soil pipe reaches the outside wall of a building with a shop below, two consents can be in play: the council's, if the frontage is designated, and the freeholder's licence to alter. The freeholder grants that, not us.",
    extraFaqs: [
      {
        q: "Does a flat above a shop take longer than one on a residential street?",
        a: "Usually, though the difference sits in the lead-in rather than the trades. Access has to be agreed with the business below, deliveries have to fit around their trading, and every item goes up a narrow stair rather than through a front door with a hall. The wet work is much the same. We put the negotiated dates in the programme so the room is not open waiting for permission to carry a bath up.",
      },
      {
        q: "My block has a boxed riser in the bathroom. Can it be moved or opened up?",
        a: "Not by us on our own decision. A riser serves other flats, so opening the casing or changing what connects to it is the building's business and needs the managing agent's written agreement. We can design around it, box it more neatly, and provide access where the building wants access. What we will not do is take a shared service into our own hands to gain a few centimetres of floor.",
      },
      {
        q: "The flat is a leasehold ex-council flat. Is that different from a private conversion?",
        a: "In method, only where the construction differs — solid floors and designed risers rather than joists and a later waste. In process it is quite different. The freeholder may be the council or a housing association, with a formal alterations procedure, its own notice periods and rules about common parts. We ask who the landlord is at the first visit, because that answer sets the lead-in more than the room does.",
      },
    ],
  },
  "maida-vale": {
    scopeNotes: [
      "The W9 job is usually the original bathroom off the hall in a red-brick or terracotta block of the 1890s to 1910s: strip-out, a floor made ready for a documented waterproofing system, wastes reconnected to the existing duct, tiling, sanitaryware, extract, then the room decorated at the end. Two dimensions govern it — the build-up available above the neighbour's ceiling, and the route by which a bath and boards of tile reach the door.",
      "Left out is any change to the fabric that holds the flat up or keeps the weather out. Service ducts and stacks stay where the block put them; a long corridor plan is not re-cut to give a bathroom a better wall. Canal-side and mews properties bring their own limits on what may touch an elevation. Structural work of any kind — openings, floors, roofs — sits with Hampstead Renovations, and is not quietly folded into a bathroom scope.",
    ],
    processNote: "Before a date exists, two things are settled: what the lease requires, and how the materials get in. Porters' hours, the lift car and the turn of the stair are recorded at survey, and the delivery is broken into loads the building will accept rather than one pallet at the kerb. A date is offered only once the lease question is answered. Inside, isolation and testing precede tiling, because that floor is someone else's ceiling.",
    consent: "Westminster is the planning authority and the Maida Vale Conservation Area covers a substantial part of W9, so anything appearing on a mansion-block elevation — a vent, a duct terminal, a replacement window — is a council matter rather than a right [VERIFY the boundary for the address]. Renewing a bathroom inside its existing walls generally is not. The lease sits alongside that: the stacks and ducts are usually retained by the freeholder, so altering a connection needs a licence to alter from them. Canal-side frontages can add the Canal & River Trust. [VERIFY on the property.]",
    extraFaqs: [
      {
        q: "How long does a licence to alter usually add to the start date in a Maida Vale block?",
        a: "It varies by building, and we do not quote a figure we cannot control. What we can do is start it early: drawings, a method statement and the scope go to the managing agent while materials are still being chosen. Some blocks turn a pack round quickly; others work to a committee timetable. The programme is written around the date the licence is granted, not the date you enquired.",
      },
      {
        q: "Can the bathroom move out of the hall into a bedroom in a mansion flat?",
        a: "Rarely, and only where a waste can reach the existing duct at a fall without crossing outside your demise. These plans were drawn around a single service position and a long corridor; the further a WC travels from it, the worse the fall and the more boxing you live with. Where the drainage will not serve the new position, we say so instead of drawing it and hoping.",
      },
      {
        q: "Is a bathroom in a Little Venice house or a mews the same job as one in a block?",
        a: "No. A freehold house has its own drainage and no managing agent, which removes the licence step, but it brings a narrow stair, a close neighbour, and on some frontages a canal setting that constrains anything touching the outside [VERIFY on the frontage]. Mews buildings are a different construction, often with shallow floors. The survey treats them as separate stock, not as a flat that happens to sit at ground level.",
      },
    ],
  },
  "muswell-hill": {
    scopeNotes: [
      "A Muswell Hill instruction is usually the first-floor bathroom of an Edwardian house: a room with a window, deep sash reveals, and floorboards that have been lifted before for earlier plumbing. The constraint that decides the job is the existing waste run to the rear stack and how much fall it has left. We lift boards and confirm that before a layout is fixed, because a slope house rarely runs level under the finish.",
      "What sits outside it is anything structural. Slope houses often invite a request to take the wall between bathroom and box room down and make one larger room; that is not this service and sits with Hampstead Renovations. Nor do we assume the drop. Some streets here are steep and short of kerb space, and off-street parking is not universal, so the vehicle and the carry are settled on site rather than priced from a map. [VERIFY parking controls on the street.]",
    ],
    processNote: "The lead-in here carries two decisions before anything is ordered. Haringey's conservation map settles where a grille may sit — a rear elevation on the slope and a frontage on the Broadway are not the same question — and the street settles the vehicle. Long loads are staged rather than delivered in one drop. Only when both are answered do dates go against sanitaryware and tile, and only then does the room come out. In a one-bathroom house the wet weeks are sequenced to be continuous, not interrupted.",
    consent: "Replacing a bathroom inside an existing room is normally outside planning control. The envelope is not: a new extract grille, a relocated soil pipe or a changed window on a house inside Muswell Hill Conservation Area is a matter for Haringey, and the Fortis Green designation on the north-west side is a separate boundary again. [VERIFY which map the address sits on, and any Article 4.] Tenure is the other half. In a converted flat or a flat over a Broadway parade, a licence to alter is granted by the freeholder or managing agent, not by the council and not by us.",
    extraFaqs: [
      {
        q: "How long does a bathroom take in an Edwardian house on the hill?",
        a: "There is no fixed answer, and we do not give one before survey. What moves it: whether the waste run can be reused or has to be re-laid to reach the stack, whether a new extract route is needed, how much of the floor is sound once boards are up, and how materials are staged on a steep street. The written programme follows the survey.",
      },
      {
        q: "Our bathroom sits over the kitchen — does that change the method?",
        a: "It changes what a failure costs, so it changes the order of work. A waste run above a kitchen ceiling is tested and left visible until it has held, and waterproofing goes down as a system before tiling closes the floor. If a connection turns out to sit in the ceiling below, we open and make good that ceiling rather than work blind from above.",
      },
      {
        q: "Can the family bathroom and a small shower room be done in one programme?",
        a: "Often that is the sensible way to do it in a family house here, because the second room keeps the household washing while the first is out. It is one survey, one specification and one account. The sequence matters more than the total: we take the rooms in turn rather than opening both, so there is never a week with neither available.",
      },
    ],
  },
  "primrose-hill": {
    scopeNotes: [
      "A Primrose Hill instruction is usually one of two rooms. In a split terrace it is the bathroom carved out of a closet wing: shallow joists, one cold external wall in stock brick, and a door that already opens over the head of the stair. In a garden flat it is a lower-ground room where the wall condition has to be established and dried before any waterproofing is specified. Which it is decides how the survey opens.",
      "Excluded: enlarging the room by taking out the wall to the bedroom, forming a shower room in a space that has never had drainage, and anything that changes the rear elevation. Terraces here are shallow and closely built, so what looks like a minor rear alteration is visible from several neighbouring gardens at once. Work of that kind sits with Hampstead Renovations. We also make no assumption that a skip can stand outside; that is arranged, not presumed.",
    ],
    processNote: "The order of works is set by moisture, not by the calendar. Where a lower-ground room is involved, the survey opens the wall base first and the room is left to dry before waterproofing is specified; that reading sits in the lead-in alongside material dates. Above ground the constraint is different — the household is usually still in residence, so strip-out noise is agreed with the neighbours either side, and the drop is booked for a weekday morning rather than a weekend around the hill.",
    consent: "Nothing inside the room needs the council's permission in the ordinary case: replacing a bathroom within an existing room is not development. The Article 4 direction and the conservation-area designation bite on the outside — windows, rooflines, front gardens, and any new duct or grille that appears on an elevation. Tenure is the other half. In a split house the freeholder is often the flat owner upstairs or downstairs, so a licence to alter, where the lease requires one, is a neighbour conversation as much as a legal one. [VERIFY the designation and the lease terms for the address.]",
    extraFaqs: [
      {
        q: "What actually drives the cost of a bathroom here?",
        a: "We do not publish a price list, and a figure before a visit would be a guess. What moves it locally is the state of the substrate, whether the wastes stay where they are, whether a lower-ground room needs drying and moisture work first, and how much of the specification is stone or long-lead. We visit, then write a proposal against a defined scope, and variations after that are written.",
      },
      {
        q: "Can a macerator solve a bathroom the stack will not reach?",
        a: "Sometimes, and it is a decision to make with your eyes open rather than a default. A pumped waste adds a mechanical item, a power supply and a maintenance obligation to a room in a Victorian terrace, and it does not improve a poor fall elsewhere on the run. Where a gravity connection is achievable we specify it. Where it is not, we say plainly what the alternative asks of you in maintenance.",
      },
      {
        q: "Why does the survey start at the bottom of the wall, not the layout?",
        a: "Because in the lower-ground rooms around here the wall base tells you whether the rest of the drawing is worth doing. A room that reads dry in August can be carrying moisture behind a previous refit. We take readings, look at what the last installation concealed and record the condition in writing. Waterproofing is applied to a substrate we have understood, not over one we have covered up.",
      },
    ],
  },
  "queens-park": {
    scopeNotes: [
      "Two rooms recur. On the Brent terraces it is the bathroom above the rear return, reached off a half-landing, with the stack on the outside of the return wall and a floor that steps down from the bedroom level. On the Westminster Estate the room is smaller again and often a later insertion into a cottage that was not built with one [VERIFY on the property], so the survey is a question of what earlier work left behind under the floor and inside the boxing.",
      "Neither instruction extends to enlarging the room. On the Estate that would mean taking a slice out of a bedroom in a cottage that has little to spare, and the upstairs ceiling heights limit what a raised floor can do. On the terraces it would mean altering the return, an external change on what may be a designated street [VERIFY]. We form no new openings, and a level-access tray is not assumed before the boards come up. That work sits with Hampstead Renovations.",
    ],
    processNote: "Confirming the frontage comes before confirming the fixtures. Brent and Westminster issue skip and scaffolding licences separately and on their own timetables, so the borough is settled from the address before any application goes anywhere. After that the sequence divides by stock. In an Estate cottage, strip-out is planned around joinery that is being kept and around neighbours a single brick away, which pushes noisy work into a narrow band of the day. On the terraces, deliveries come off a residential street rather than Salusbury Road.",
    consent: "The borough decides the process; the lease decides the permission. Brent and Westminster maintain separate conservation areas here and separate application routes, though a renewed bathroom inside an existing room usually engages neither, because internal work to an unlisted house is not development. The envelope is where that changes — a new grille, an external waste, a window in a different design. Tenure is the parallel track: in a converted flat the freeholder or managing agent, not the council, grants the licence to alter that lets a waste move or a shared void be opened. [VERIFY the borough, the designation and the lease for the address.]",
    extraFaqs: [
      {
        q: "What makes one Queen's Park bathroom a bigger job than the next?",
        a: "Not the postcode. It is the state of what is under the floor, whether the stack will take the position you want without a new external run, how much original joinery is being kept and worked around rather than replaced, and the lead time on the finishes chosen. There is no price list. We visit, agree a defined scope, and write a proposal against it.",
      },
      {
        q: "The cottage has no room for a separate shower. What are the options?",
        a: "Usually a bath with a fixed screen and an overhead outlet, or a single tray occupying the bath footprint, depending on which the floor and the waste position support. What we do not do is push the fixtures into the doorway to claim a third item. Estate rooms are small and the honest layout is often the sparse one. We draw it to scale at survey so you see the clearance before anything is ordered.",
      },
      {
        q: "Our bathroom was put in during a 1990s conversion. Does that help or hurt?",
        a: "It usually means less archaeology and more surprises of a different kind. Conversion-era boxing often hides a shallow floor build-up, a waste run laid to minimal fall and insulation that stops where the plasterboard starts. We open a section before the layout is finalised rather than trusting what a previous contractor drew. What we find sets the waterproofing detail and the acoustic separation from the flat below.",
      },
    ],
  },
  "st-johns-wood": {
    scopeNotes: [
      "In the mansion blocks the job is a compact shower room or bathroom sitting on a riser the whole building shares. It covers strip-out with the common parts protected, waterproofing over a timber intermediate floor, new work tied back to that riser, tiling, sanitaryware, extract and making good. Villas and mews houses give a larger family room and a different problem: a driveway, a front boundary and a stair built for a household rather than for a trade.",
      "What it excludes is anything beyond your demise. The riser, the common stack and the structure belong to the building; we connect to them under the licence and do not re-route them to suit a layout. Structural alterations, and any project that changes the flat's plan by removing walls, are not this service and sit with Hampstead Renovations. Nor is lift access assumed: until the lift car and the stair have been measured, neither is treated as available.",
    ],
    processNote: "Everything here waits on the block. The licence pack is drawn and submitted first, and the agent's timetable, not ours, sets when work can begin. Once granted, the sequence is arranged around the building's working hours, the porter's booking sheet for the lift or the loading bay, and notice to the flats above and below before services are isolated. Waste leaves by an agreed route at agreed times. Match days at Lord's are checked against the delivery dates. [VERIFY with the building.]",
    consent: "Tenure leads here, not planning. Most flats are leasehold and most leases require a licence to alter before wastes, extract or electrical routes change; some blocks also run their own design rules, which can be stricter than anything the council would ask. That consent is the freeholder's or managing agent's to give. Westminster designated the St John's Wood Conservation Area in 1968 and controls the envelope — fenestration, roofs and anything visible on the outside — while a bathroom rebuilt within its existing walls generally falls outside planning. A small Camden conservation area adjoins on the borough edge. [VERIFY which applies.]",
    extraFaqs: [
      {
        q: "Why can you not give a price for a mansion-flat bathroom over the phone?",
        a: "Because two flats in the same block price differently. What the riser will accept, the condition of the floor over the flat below, whether the extract route already exists, the block's rules on hours and access, and the specification you choose all move the figure. We do not publish rates. We visit, define the scope in writing, and price that scope so you can hold us to it.",
      },
      {
        q: "What happens if strip-out finds an old leak into the flat below?",
        a: "It is reported the same day, to you and to the building, and the affected section is isolated before anything else continues. Historic staining under a bath is common in stacked blocks and often explains a neighbour's complaint from years earlier. Remedial work outside the agreed scope is priced as a written variation before it is carried out, not absorbed quietly and billed later.",
      },
      {
        q: "Can a second shower room be added to a flat in one of the blocks?",
        a: "Only where a waste can reach the existing riser at a workable fall inside your own demise, and where the block will licence it. Some flats have a former maid's room or a wide hall cupboard that will take one; many do not, because the drainage would have to cross a neighbour. We survey the riser positions first and say plainly if the answer is no.",
      },
    ],
  },
  "swiss-cottage": {
    scopeNotes: [
      "Most instructions here are single-room replacements rather than re-plans. In the inter-war blocks off Finchley Road the WC and basin back onto a boxed riser shared with the flats above and below, so the three fixture positions are effectively fixed before anything is drawn; the work is substrate, waterproofing, ducting and finishes. In the Victorian side-street conversions the same room sits over another household's ceiling, and the survey is as much about what the last refit concealed as about the layout you want.",
      "It does not include taking down the wall between bathroom and bedroom to make a larger room, or altering the communal riser itself. Those are the freeholder's asset, and in the inter-war blocks the duct is often built into the structure rather than boxed in later [VERIFY on the building]. Structural openings sit with Hampstead Renovations. A lift is not assumed to take a bath; on Avenue Road the goods route is confirmed with the building before sanitaryware is dated.",
    ],
    processNote: "The lead-in carries more here than the site weeks do. In the Avenue Road and Finchley Road blocks a managing agent's pack — drawings, method statement, working hours — is prepared and submitted before a single tile is ordered, and nothing is stripped while it is outstanding. On the South Hampstead side streets the check is a conservation one and the paperwork is thinner, so the sequence compresses. Either way the delivery slot is booked around the corridor, not around us.",
    consent: "The freeholder and the council answer different questions. A licence to alter is granted by the freeholder or the managing agent, not by Camden and not by us; it governs moving a waste, cutting into riser boxing, or working outside the block's stated hours. Planning and conservation sit with Camden, and internal work within an existing bathroom generally falls outside both — the envelope does not. A new grille on a Finchley Road frontage and one on a South Hampstead side street are different questions. [VERIFY which designation covers the address, and whether the tenure requires a licence.]",
    extraFaqs: [
      {
        q: "How long is a bathroom out of use in a Finchley Road flat?",
        a: "The site weeks are the smaller half of it. Where the block runs a licence-to-alter process, the lead-in absorbs the agent's turnaround, and we do not open the room until the pack is back. On site, a room whose wastes stay where they are moves faster than one where the floor has to be levelled and made good before waterproofing. The programme is written after the survey.",
      },
      {
        q: "The bathroom backs onto a boxed duct. Can it be opened up?",
        a: "Only with the freeholder's agreement, and only once we know what is inside it. In the inter-war blocks that boxing usually carries the stack and the branches from other flats, so it is common property rather than yours. We survey it, record what it serves and put any proposal to the agent in writing. Where the answer is no, the layout is drawn around it. [VERIFY the tenure and the duct's status on the building.]",
      },
      {
        q: "Does a low ceiling in an inter-war block limit what the room can take?",
        a: "It can. A concealed cistern, a recessed shower valve and a drop for extract ducting all borrow depth from somewhere, and in the later blocks there is less of it above the door head than in a Victorian house on the side streets. We measure the soffit and the floor build-up before the layout is drawn, and say plainly which items the room will not hold.",
      },
    ],
  },
  "west-hampstead": {
    scopeNotes: [
      "Most West Hampstead work is one half-landing room in a converted terrace: strip-out, a new floor build-up where the old one has dropped, tanking, wastes rerun to the existing stack, tiling, sanitaryware, extract and the room's decoration. The dimension that governs it is the fall from the WC branch to that stack, found inside a timber floor that also happens to be somebody's ceiling. The door swing usually decides where the shower can go.",
      "Excluded is anything that changes the structure to make the room easier: joists are not notched to win a fall, the half-landing is not enlarged, and a new rear addition is not formed to hold a second bathroom. That work belongs with Hampstead Renovations. Access is not assumed either — we do not plan on the basis that the shared hall is free all day, or that a skip can sit on West End Lane.",
    ],
    processNote: "Two things stretch the front end here: the neighbour below and the shared stair. Before a date is fixed we agree isolation and testing with the flat underneath, settle with the freeholder how the common hall is protected, and confirm whether the waste run needs a licence. Order of works follows from that — protection, then noisy work inside agreed hours. Sanitaryware arrives when the room can receive it, because a converted terrace has nowhere to store a bath.",
    consent: "Work inside the room is generally outside planning control. The outside of the building is not, and a converted flat is in a weaker position than a house: the permitted-development rights a householder relies on do not apply to flats, so a new vent or duct on an external wall is a planning matter for Camden rather than an automatic right [VERIFY for the address]. Conservation-area coverage in NW6 runs street by street, and Article 4 directions can bite on windows. Tenure is a separate track: a licence to alter comes from the freeholder or managing agent, on their timetable.",
    extraFaqs: [
      {
        q: "What actually drives the cost of a West Hampstead bathroom?",
        a: "There is no price list. On this stock the variables are the state of the floor once it is up, how far the wastes have to travel to reach the stack, whether the extract needs a new route, and the specification you choose for tiles, glass and brassware. We visit, agree a scope in writing, and price against that scope so the comparison is like for like.",
      },
      {
        q: "The freehold of our converted house is shared between the flats — who grants consent?",
        a: "Whoever the lease names, which in a share-of-freehold house is usually the company the flat owners jointly own. In practice that means your neighbours agree the work, often at a meeting rather than through an agent. We prepare the layout and method statement for that decision; we do not treat a friendly conversation on the stairs as consent.",
      },
      {
        q: "We only wanted new tiles — why does the floor have to come up?",
        a: "Because a tanked floor is only as good as what it sits on. Half-landing decks in these terraces have usually moved, and boards that flex will crack a tiled finish and eventually the waterproofing under it. Lifting the deck also shows the waste runs and any earlier leak. If the floor turns out sound, we say so and the scope is reduced in writing.",
      },
    ],
  },
};
