// Generated by scripts/build-detail-data.mjs — edit the copy here directly;
// re-running the generator overwrites this file.
import type { ComboDetailMap } from "./combo-detail";

export const kitchenDetail: ComboDetailMap = {
  "belsize-park": {
    scopeNotes: [
      "Much of what we replace here was inserted by somebody else: a kitchen in a former bedroom or service room of a converted stucco house, cornice still running round it, a chimney breast standing in the middle of the only long wall. The instruction covers that room and the floor under it, because the waste has to travel to a stack never meant to serve a kitchen in that position. On the avenues the same job appears as a mansion-flat galley on original risers.",
      "It stops where the structure begins. Taking out the chimney breast, joining two rooms of a lateral conversion, or cutting into a floor to win drainage fall are not part of a kitchen instruction; they sit with Hampstead Renovations. Stucco repair and window design belong to the outside of the building and to a different conversation. Where a previous owner has already removed a breast on an upper floor, we check what remains before anything is hung from it.",
    ],
    processNote: "Ceiling height decides what happens first here. In a room of that height, filling and finishing overhead is done from a clear floor, before a run of units makes access equipment impractical. The paperwork decides the rest: whether the building is a managed block on the avenues or a small converted house with a shared freehold sets how long consent runs, and that is settled before anything is ordered rather than alongside delivery.",
    consent: "Camden deals with the outside of a Belsize house. The Belsize Conservation Area covers much of the neighbourhood, Article 4 directions apply to parts of it, and stucco, windows and any new grille are read against that; a kitchen fitted within an existing room generally is not planning's business at all. The lease deals with the inside. A licence to alter comes from the freeholder or managing agent, and holding a share of the freehold changes who signs rather than whether a signature is needed. [VERIFY the boundary, any Article 4 and the lease terms.]",
    extraFaqs: [
      {
        q: "We hold a share of the freehold. Is a licence to alter still needed?",
        a: "Usually, yes. A share of the freehold makes you one of the people granting consent, not a reason consent can be skipped. The lease still governs what may be altered, and the freehold company gives permission in writing, which in a converted Belsize house means your neighbours, formally. We prepare drawings and a method statement for that process. We do not grant it. [VERIFY the lease terms.]",
      },
      {
        q: "The chimney breast has already been cut about. Can you still fit around it?",
        a: "We fit to what is there, once we know what is there. A breast a previous owner opened up or partly removed is a structural question before it is a kitchen one, and nothing is hung from it or loaded onto it until that has been understood. If work to the structure is needed, it is not this service; that sits with Hampstead Renovations.",
      },
      {
        q: "The kitchen sits in a former bedroom. Where does the waste actually run?",
        a: "Across the floor, in most cases, to reach a stack that was never positioned for a kitchen in that room. That run sets the layout: sink and machines go where the fall works, and the floor build-up has to carry it, often above another household's ceiling. It is the first thing surveyed in an inserted Belsize kitchen and the first thing that rules a plan out.",
      },
    ],
  },
  "crouch-end": {
    scopeNotes: [
      "Most instructions here are for a converted house: a garden or first-floor flat where the kitchen occupies the rear room, sometimes a former scullery already inside the envelope, with a shared front door and a tiled hall between the street and the work. The fixed point is the soil stack on the rear elevation. Cabinet runs, the sink and the washing machine are set out from it, and the room is planned around what that stack will take.",
      "Excluded is anything that changes the structure or the shared fabric: no opening between the kitchen and the room next to it, no work to the stack beyond the demise it serves, and no redecoration of the communal hall unless the freeholder instructs that separately. In a house split between two or three households, the hall is somebody else's floor. We protect it, and we leave it as we found it.",
    ],
    processNote: "In a converted house the lead-in is mostly other people's diaries. A leasehold flat needs the freeholder's pack agreed before anything is ordered, and the other households behind the same front door need notice of the noisy weeks. That fixes the order: paperwork and protection first, then strip-out on a day the skip has a licensed side-street position, because the Broadway is not a place to stand a lorry. Second fix follows the worktop template, not the calendar.",
    consent: "Haringey and the freeholder answer different questions, and it is worth keeping them apart. The council is the planning authority; its conservation-area designation of 25 October 1974 covers the Broadway and a ring of residential streets, so anything visible on the elevation — a new extract terminal, a replaced window — is decided there. [VERIFY whether the address sits inside the boundary.] A licence to alter comes from the freeholder or managing agent instead, and in a converted house that is often a neighbour holding a share of the freehold. Re-fitting an existing kitchen internally usually needs neither.",
    extraFaqs: [
      {
        q: "What decides the cost of a kitchen in a Crouch End conversion?",
        a: "We do not publish a price list. The variables are scope, not postcode: how much of the existing services survives, whether the stack position lets the layout stand still, the worktop material, whether appliances are supplied by you, and how much making-good the rear room needs once it is stripped. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "The flat below us is somebody's bedroom — how do you manage the noise?",
        a: "Working hours are written into the programme before the start date, and the neighbours are told which weeks are noisy: strip-out, chasing and first fix. Quiet trades are grouped where the sequence allows. We do not run percussive work early or late to make up time, and we do not lift a floor over someone's ceiling without telling them first.",
      },
      {
        q: "There is a bricked-up range recess in the back wall — is it any use?",
        a: "Often, yes. A recess of that kind gives depth for a cooker or a tall unit without stealing floor, provided the flue above it is sound and either capped or ventilated properly. It is also where surprises live: old registers, soot staining and unsupported brickwork. We open it at strip-out and confirm the specification then, rather than drawing a hob into it in advance.",
      },
    ],
  },
  "golders-green": {
    scopeNotes: [
      "The rooms here are larger, so the constraint is rarely space. It is what is already on the walls: a boiler and its flue on the rear elevation, an aged gas run from a meter in the hall, and a consumer unit that will not carry a full set of new kitchen circuits without attention. An inter-war ground floor is often solid rather than suspended, so new services are chased or run high rather than dropped under the boards.",
      "What sits outside it is the ask this stock generates most often: knocking the kitchen through to the dining room, or building out into the side return. Both are structural, both belong with Hampstead Renovations. Nor does a kitchen instruction become a house rewire. We take the kitchen circuits back to the board and report what we find there; replacing a board or the wiring beyond the room is a separate piece of work, quoted separately.",
    ],
    processNote: "Consent takes up less of the lead-in here than household logistics do. Where there is a driveway the skip stands off the highway and no Barnet licence is needed, which removes a step that a Camden street would have added. [VERIFY the licence position with Barnet.] What replaces it is sequencing around a family that is staying put: a temporary sink and a working route to the back door, and the gas isolation booked so the house is not without hot water for longer than the changeover needs.",
    consent: "Most of this stock is undesignated, which is not the same as unregulated. Barnet is the planning authority, and selected streets — including some near Golders Hill Park — sit in conservation areas, so a new flue terminal or extract grille on a visible elevation is checked before it is drawn. [VERIFY Barnet's map for the address.] The Hampstead Garden Suburb Trust does not reach here unless the address is inside its boundary, which is a separate map again. In the mansion flats on the main roads a freeholder's licence to alter still applies.",
    extraFaqs: [
      {
        q: "The boiler is on the kitchen wall. Does it have to move?",
        a: "Not necessarily, and moving it is a decision with consequences beyond the units. A relocated boiler means a new flue position on the elevation, a longer gas run and a condensate route, and the work is carried out by a Gas Safe registered engineer. Where the run can be planned around the existing position, that is usually the cleaner answer. We set it out at survey rather than after strip-out.",
      },
      {
        q: "Can the skip go on our own driveway rather than the road?",
        a: "Where there is room for it, yes, and that avoids a Barnet highway licence altogether. It also keeps the strip-out off a residential crescent that fills with cars in the evening. We check the standing surface and the access width at survey, because a drive that will take two cars will not always take a skip lorry. [VERIFY the licence position with Barnet.]",
      },
      {
        q: "Our house still has a larder and a back scullery. Can they be brought into the kitchen?",
        a: "Taking out the wall between them is a structural question, and that sits with Hampstead Renovations rather than here. What we can do within this service is re-fit the rooms as they stand, and a larder is often more useful kept than lost: it takes tall storage and appliances off the main run and leaves the working wall clear. We will show both options at survey.",
      },
    ],
  },
  "hampstead": {
    scopeNotes: [
      "A Hampstead kitchen usually arrives as one room in a converted house: a first-floor rear room or a half-landing galley, behind lath and plaster, on boards that have dropped toward the party wall. Family houses toward Frognal give a larger version of the same job. What decides the work is the waste position and the extract route; both are set by the building, and in this conservation area the elevation is not available as a solution.",
      "Nothing in that scope removes a wall. Joining the kitchen to the room beside it is the usual village temptation, where two small rear rooms sit side by side, and it is not this service; nor is a new or widened opening in an external wall, a replacement sash, an extension or a loft. That work sits with Hampstead Renovations. We also do not assume a lane will hold a skip for the duration.",
    ],
    processNote: "Two checks sit ahead of everything else here: what the address is actually designated as, and whether a converted house's freeholder has to agree anything. Both belong before the order goes in, not before handover. The extract route is settled while the old kitchen is still standing, because the elevation decides it and a lane off Heath Street gives one delivery window rather than several. The strip-out date is booked to that window, not to a convenient Monday.",
    consent: "Listing is the question that matters most on this stock. Where the house is listed, internal alterations can need listed building consent, so the entry is read before anything is priced in detail. Otherwise a kitchen replaced inside an existing room sits outside planning; the elevation does not, and a new opening, a grille on a principal front or a replacement window in the Hampstead Conservation Area is a Camden matter. Permission to alter a leasehold flat is the freeholder's or managing agent's to give, never ours. [VERIFY the designation, the listing and the lease terms on the address.]",
    extraFaqs: [
      {
        q: "The floors slope and the walls are lime plaster. Will the room be squared up first?",
        a: "No. A village-house floor that has settled over a century is levelled locally, where a unit or an appliance needs it, rather than made flat end to end. The run is scribed to the wall instead of the wall being rebuilt to the run, and lime plaster is made good in a compatible material. Both are recorded at survey, so the tolerance is agreed rather than discovered.",
      },
      {
        q: "What tends to appear when an old Hampstead kitchen comes out?",
        a: "Redundant gas runs, wiring that serves something else, lath and plaster behind the units, and boards rather than a level subfloor. None of that is unusual in this stock. What matters is the handling: findings are recorded while the room is open, priced as a written variation against the agreed scope, and put to you before anything is done about them.",
      },
      {
        q: "Three other households share our stair. Can the work still run?",
        a: "Yes, with the common parts treated as part of the site: dust screens, protected treads, an agreed route in and out, and hours the other households have been told about. Deliveries on a village lane are timed so that material does not stand in a shared hall. Decoration of those parts belongs to the freeholder and is not inside a flat's kitchen scope.",
      },
    ],
  },
  "hampstead-garden-suburb": {
    scopeNotes: [
      "A Suburb kitchen is almost always the third or fourth version of that room. The plan is small by modern standards, the window is more often a casement than a sash, and there is frequently a larder or former scullery already absorbed into the space. Ceiling heights in the cottages are modest, so wall units and any extract housing have to be set out carefully. The instruction is a fit-out inside those walls, scribed to them.",
      "Outside the room, nothing is touched. No new opening in an external wall, no rooflight, no replacement window, no soil pipe or grille on an elevation, and no change to a front boundary or hardstanding to ease a delivery. Internally, the wall between the kitchen and the hall stays. The Suburb is a planned composition, and a kitchen may be modern behind it without becoming visible on it.",
    ],
    processNote: "Two boundaries are checked at the very start, because they are not the same line: the conservation-area map and the Trust's Scheme of Management area. [VERIFY both for the property.] If any part of the brief touches the outside, that element goes for written Trust consent and Barnet planning before drawings are finalised, and the internal programme waits rather than starting hopefully. Delivery planning is its own item; a close or a green takes a small vehicle and a short, agreed standing time.",
    consent: "Consent here comes from two independent bodies with different powers. Barnet is the local planning authority and decides planning applications; the long-standing Article 4 direction means alterations that would be permitted development elsewhere are not assumed to be here. Separately, the Hampstead Garden Suburb Trust administers a Scheme of Management under its own Act and gives written consent as a landowner interest, which is not planning permission and does not replace it. [VERIFY whether the property is inside the Trust area and what its current guidelines require.] Replacing a kitchen inside the room, changing nothing outside, generally engages neither.",
    extraFaqs: [
      {
        q: "If the Trust consents, do we still need Barnet planning permission?",
        a: "They are separate decisions. Trust consent is given under the Scheme of Management as a landowner interest; planning permission is a Barnet matter under the planning acts. One does not carry the other, and an external item can require both. [VERIFY which applies to the specific work.] For an internal kitchen that leaves the elevation untouched, ordinarily neither is engaged.",
      },
      {
        q: "The kitchen ceiling is low and the window is a casement — does that matter?",
        a: "It sets the vertical dimensions. Wall units, cooker hoods and any extract housing are dimensioned against the real head height and the window reveal, not a standard elevation. Where a recirculating unit avoids breaking the outside wall it is often the sensible answer here, though it is not equivalent to ducted extract and we will say so rather than present it as the same thing.",
      },
      {
        q: "Are Suburb houses listed as well as being in the conservation area?",
        a: "Some are. Listing is a separate national designation from the conservation area and from the Trust, and it applies to individual buildings and groups rather than to the Suburb as a whole. Where a house is listed, interior work can require listed building consent even when nothing shows outside. We check the entry for the address before anything is opened up. [VERIFY listing on the property.]",
      },
    ],
  },
  "highgate": {
    scopeNotes: [
      "N6 produces two different kinds of job. In a Village house, particularly a listed one, the kitchen is usually a later insertion into a basement or a rear service wing, and listed status reaches inside the building as well as outside it. On the slopes the more common job is a family kitchen at the back of a raised ground floor in an unlisted villa, where the deciding constraint is the gradient rather than the fabric.",
      "The line is drawn at taking down the wall behind the kitchen to make one room, which is the request the slope villas most often generate and is structural work sitting with Hampstead Renovations. In a listed Village house we also stop where historic fabric would have to go — a chimney breast, panelling, an original partition — because that needs consent from the council in its own right, not a decision on site. [VERIFY listing and the correct borough.]",
    ],
    processNote: "Which borough holds the frontage is settled before anything is applied for, because Camden, Haringey and Islington each run their own licensing and each takes its own time. A listing check runs alongside it. On the steeper plots the drop point then decides the shape of strip-out: where a skip cannot stand, waste is bagged and carried, which is slower and is priced and programmed as such rather than discovered on the day.",
    consent: "The useful distinction here is between two designations that behave differently. Conservation-area control, which covers much of the Village and the slopes, bears on what can be seen — grilles, windows, rooflines — and is administered by whichever of Camden, Haringey or Islington holds the frontage. Listing is separate and reaches the interior, so an internal alteration in a listed Village house can need consent even though the same work elsewhere would not. Tenure adds a third layer: a converted flat may need the freeholder's licence to alter. [VERIFY all three on the address.]",
    extraFaqs: [
      {
        q: "What actually moves the number on a Highgate kitchen?",
        a: "We do not publish a price list, and we will not put a range against a house we have not seen. What moves it is the state of the services behind the units, whether the room is listed, how the materials reach the plot on a steep street, and the specification you choose for cabinetry, worktop and appliances. We visit, then write a proposal against a defined scope. 020 7101 3168.",
      },
      {
        q: "Does listing stop us replacing a kitchen in a Village house?",
        a: "No, but it changes what can be touched. Replacing units, services and finishes in a room that has already been altered is ordinary work. Removing historic fabric to make the run fit is not, and listed building consent covers interiors as well as elevations. We identify what is original at survey and say plainly which parts of a layout would need consent before anything is priced in detail.",
      },
      {
        q: "We are on the Holly Lodge Estate. Is that treated differently?",
        a: "It is a separate conservation designation from Highgate Conservation Area, so the appraisal that applies to your building is not the Village one, and the estate's own arrangements may sit on top of the council's. [VERIFY the designation and any estate covenants for your address.] Inside the property the work is an ordinary kitchen fit-out; the checks we run beforehand are the part that differs.",
      },
    ],
  },
  "kentish-town": {
    scopeNotes: [
      "Lower-ground rooms account for much of the work here. A terrace split into flats leaves the kitchen against retained ground at the back, part solid floor and part suspended timber, with masonry that has never been dry in the way a modern wall is dry. Moisture readings and the state of the existing plaster decide the specification before any layout question is settled, and they decide whether the room is ready for units at all.",
      "What we will not do is bury the problem. Units are not hung on a wall that is still taking water, and no decoration is signed off over it. Nor does the scope reach the structure: no wall between the return and the front room comes out, no lintel work, no lowering of a lower-ground floor. Where the cause sits outside the flat — a blocked gully, a neighbour's gutter — it is reported, not absorbed.",
    ],
    processNote: "The sequence here gains a step before it starts. Where the room is below ground, we want the fabric looked at and the cause of any damp identified before cabinetry is ordered, because a drying period cannot be compressed once the programme is running. The Camden skip licence goes in against a side street, never the corridor, and the neighbours either side are given the noisy dates. Strip-out follows the drop, not the other way round.",
    consent: "Tenure matters more than designation on most of these addresses. A flat in a split terrace is leasehold, so if a waste run moves or a duct passes through anything outside the demise, the freeholder or managing agent grants the licence to alter; Camden has no part in that. Camden's part is the elevation. Conservation-area coverage runs street by street through Kentish Town and up toward Dartmouth Park rather than following the High Street, so a rear grille may be an ordinary detail on one road and a planning question on the next. [VERIFY the designation for the address.]",
    extraFaqs: [
      {
        q: "Why does a lower-ground kitchen take longer than the same room upstairs?",
        a: "Because the fabric has to be right before anything is fixed to it. Finding the cause of damp, taking off failed plaster and letting a wall dry are not stages that run in parallel with a cabinet fit. The same room above ground might be a straightforward replacement. We set out both at survey and programme the one the readings support.",
      },
      {
        q: "Our flat is in a converted workshop building — is that different?",
        a: "It can be. Those buildings were not laid out for domestic services, so waste runs, floor construction and ventilation are often improvised rather than original. We survey what is there before drawing anything, and we say plainly where a proposed sink or hob position cannot be served without work that falls outside a kitchen renovation. The fit-out itself follows the same sequence.",
      },
      {
        q: "Who arranges the skip licence and the parking for the delivery?",
        a: "We do. The skip licence and any parking bay suspension are applied for through Camden against a named side street and a stated date window, and those dates go into the programme rather than being assumed. Permit-holder bays fill by mid-morning, so the delivery is booked to the window rather than hoped for. If a permit slips, the delivery moves with it, and nothing is left on the pavement.",
      },
    ],
  },
  "kilburn": {
    scopeNotes: [
      "Instructions divide by which side of the High Road the address sits on. East, toward West Hampstead, the room is usually a Victorian conversion galley with a party wall and a single rear window. West, in Brent, the range widens: inter-war and post-war flats where the kitchen is a purpose-built compartment with ducting already in the plan. The layout question in the first is the stack; in the second it is what the block's ventilation will accept.",
      "The scope stops at the flat. We do not take out walls, we do not work in the shop below, and we do not treat a commercial ground floor as an access route without the occupier's written agreement and a method statement. Nor is a grille through a shopfront elevation assumed: on the High Road that frontage may carry its own design guidance [VERIFY for the address]. Where extract has no honest route, we say so before anything is ordered.",
    ],
    processNote: "Nothing is applied for until the borough is settled, because Camden and Brent run separate licensing and a permit from the wrong one is worthless. That check sits at the front of the lead-in alongside the access measurement: stair width, turns, door openings and, above a shop, the hours the occupier will accept a delivery. Carcasses are ordered against those dimensions. Strip-out is booked only once the route and the waste collection are confirmed for the same days.",
    consent: "Three parties can be involved and none of them is us. The council — Camden east of the High Road, Brent west of it — decides planning and conservation matters, and designation here covers selected streets rather than the neighbourhood as a whole. [VERIFY both maps for the address.] The freeholder or managing agent grants any licence to alter, which is ordinary in a leasehold flat where services move. Above a shop, the commercial leaseholder controls access and sometimes the frontage. Replacing a kitchen inside the existing room normally engages none of them.",
    extraFaqs: [
      {
        q: "Do I need my freeholder's permission to replace a kitchen in a Kilburn flat?",
        a: "Read the lease first. A like-for-like replacement inside the demise often needs nothing. Consent is usually triggered by movement: a waste run relocated, a new circuit, a duct crossing a common void, or work to a party wall. Where it applies, we prepare drawings and a method statement for the pack. The freeholder or managing agent grants it, and no strip-out starts while it is outstanding.",
      },
      {
        q: "What happens if a stone worktop will not go up the stair?",
        a: "It is measured before anything is ordered. Where a single slab cannot make the turn, the worktop is templated in sections with a joint placed where it is least visible, or a different material is specified. That decision belongs at survey, not on delivery day with a lorry held on the High Road. Narrow stairs above the shops are the usual reason it arises.",
      },
      {
        q: "We are on the Brent side in a purpose-built block — is that easier?",
        a: "Not automatically. A purpose-built kitchen has ducting and services designed into the plan, which helps, but it also means the block decides what can change, and the managing agent sets working hours and lift use. Brent issues the licences on that side. The gain is a squarer room; the constraint is a building with rules. Both are recorded before the specification is written.",
      },
    ],
  },
  "maida-vale": {
    scopeNotes: [
      "In a W9 mansion flat the room is where the block put it: the back kitchen of a purpose-built plan, reached along a corridor that has not changed since the 1890s. It is re-planned within its own walls — the run, the services inside it, the finishes and the floor. Drainage is the fixed point. Stack and duct stay where they are, and the layout is drawn to reach them rather than drawn first and then asked to fit.",
      "Opening the kitchen into the reception, or removing the corridor wall to make one space, is not this service in any of these blocks. It is Hampstead Renovations' work, and in a leasehold flat it is a consent question as well as a structural one. Repainting previously painted brick, balcony work and window replacement belong to the outside of the building and to Westminster. Little Venice houses meet the same boundary at a larger scale.",
    ],
    processNote: "The measurement that governs the order is not the wall. It is the turn of the stair and the width of the corridor inside the flat, both recorded before a carcass is specified, because a unit that will not come round a corner has to be reordered and the programme, not the fitting week, absorbs the wait. The licence pack runs alongside that, the porter's hours decide which days can take the noise, and deliveries are split so nothing stands in a communal hall.",
    consent: "The lease is usually the document that decides a Maida Vale kitchen. A licence to alter is granted by the freeholder or the managing agent, on their timescale, and we prepare drawings and a method statement for it rather than issue it. Westminster is the second question and a narrower one: fitting a kitchen inside an existing room is not normally asked of the council, while window replacement, balcony work and the repainting of previously painted brick are ordinary consent topics in the Maida Vale Conservation Area. A canal-side frontage can add a third party. [VERIFY the conservation area, the lease and any Canal & River Trust interest.]",
    extraFaqs: [
      {
        q: "Two flats in the same block: why can they not carry the same price?",
        a: "Because the price follows the scope and the building, and neither is identical between two demises. What sits behind the plaster differs, so does the condition of the waste run, whether the licence needs drawings, and whether carcasses go up a stair. There is no price list here. We visit, define the scope in writing, and price that scope. 020 7101 3168.",
      },
      {
        q: "Will the units fit round the corridor and through the doors?",
        a: "That is measured before anything is ordered. A Maida Vale flat is a long corridor with original doorways and at least one turn, and a tall unit that cannot be carried round it is a delay rather than an inconvenience. Where the route defeats a carcass, we specify a size that will make the journey, or a unit that can be assembled in the room.",
      },
      {
        q: "Can the kitchen window be replaced while the room is stripped?",
        a: "Repairing an original sash while the room is open is sensible, and we do it. Replacing it is a different question. Window replacement is a common consent topic in the Maida Vale Conservation Area, and it is usually an alteration under the lease as well, so it involves Westminster and the freeholder on their timescales. It is a separate instruction from the kitchen. [VERIFY the designation and the lease.]",
      },
    ],
  },
  "muswell-hill": {
    scopeNotes: [
      "Edwardian houses on the slopes supply the ordinary instruction here: a rear ground-floor kitchen, usually enlarged once already by a previous owner, with a garden door in the run, a flank chimney breast, and floorboards over joists that have moved since the house was built. What decides the job is where the back door and the existing waste sit, because those two fixed points set the sink, the appliance wall and the length of usable worktop.",
      "It does not include taking out the wall between the kitchen and the room in front of it, and it does not include a side return. Those are structural and sit with Hampstead Renovations. Nor do we assume the garden elevation can carry a new grille, or that a long-wheelbase vehicle can stand on a steep street while carcasses come off it. Both are recorded at survey. Making good stops at the kitchen envelope, not at the hall.",
    ],
    processNote: "Here the lead-in carries two things the sequence cannot start without: confirmation of which Haringey designation the address sits in, and a drop point that a steep street will actually take. [VERIFY the conservation-area boundary for the address.] Extract is settled before carcasses are ordered, because a grille over a Broadway parade follows a different path from one on a rear garden wall. Where the family stays in the house, strip-out is timed to the delivery, not to a convenient morning.",
    consent: "Many Muswell Hill kitchens are in houses held freehold, so there is no landlord in the picture, and replacing units, services and finishes inside an existing room ordinarily falls outside planning control as well. The envelope is a different matter. Haringey's conservation-area designation reaches the Broadway and many of the residential streets around it, and a new grille, duct terminal or altered window on a designated elevation is a council question. [VERIFY the boundary and any Article 4 for the address.] Flats above the parade are usually leasehold, and there the freeholder or managing agent grants a licence to alter, not us.",
    extraFaqs: [
      {
        q: "How long will our kitchen be out of use in an Edwardian house here?",
        a: "We give a programme in writing after survey rather than a number on the phone. What moves it is the state of the floor once boards come up, whether the waste and the back door allow the layout you want without new drainage, and the lead time on worktops. A house where the family stays in occupation runs slower than an empty one, by design.",
      },
      {
        q: "Our kitchen still has its original timber sash — does it have to come out?",
        a: "No. A sound sash is treated as joinery: cords, beads and putty repaired, then redecorated as part of the kitchen envelope. Replacing it is a separate decision, and on a designated Muswell Hill elevation it is a Haringey question rather than an assumption. [VERIFY whether the address is in the conservation area.] We record its condition at survey so the worktop and any splashback are set out around the reveal that exists.",
      },
      {
        q: "The room is big enough for an island — will you fit one?",
        a: "Possibly. Muswell Hill rear rooms are larger than a Camden conversion galley, so the footprint is sometimes there. Whether it happens depends on the services: a sink or hob in the island means drainage and extract crossing the floor, and on suspended timber that means lifting boards and working within what the joists will allow. We answer that at survey, not on a drawing.",
      },
    ],
  },
  "primrose-hill": {
    scopeNotes: [
      "Most instructions are one flat in a split house: a garden-level kitchen under the front steps, or an upper-floor room that began as a closet. Below ground the waste usually leaves the building into a yard gully rather than a stack, so the gully's position, not the plan, decides where the sink and the machine can sit. Head height under a rear closet is the second limit, and it is measured before a tall unit is drawn.",
      "Deliberately outside it: a new opening to the garden, a wider rear door, or any change to the elevation the park side can see. Under the Article 4 direction those are permission questions before they are building questions, and they belong with Hampstead Renovations in any case. We also stop short of the causes of damp that sit outside the room — defective gullies, a raised path, a failed rear wall — which we report rather than tile over.",
    ],
    processNote: "On a lower-ground job the order of works is set by drying, not by convenience. Anything wet is opened, established and left to read stable before plaster goes back, which pushes cabinetry and worktop templating to the back of the programme and lengthens the gap between them. Above ground that gap disappears. Deliveries are booked for weekday mornings, away from the park traffic, and the shared front steps and hall are protected for the whole run rather than on fitting day.",
    consent: "In a split house the freeholder is often the flat upstairs. Where the freehold is shared, a licence to alter means a written agreement with a neighbour rather than a managing agent, and it is worth starting that conversation early. Camden is the separate authority, and only for the envelope: the Article 4 direction in force here since 3 March 1983 removes permitted-development rights on windows, rooflines and front boundaries, so a new grille or door is a planning question. A kitchen inside an existing room is not. [VERIFY the lease and the conservation-area map.]",
    extraFaqs: [
      {
        q: "How long should we expect a lower-ground kitchen here to take?",
        a: "There is no fixed figure, and the honest variable is moisture. A dry upper-floor room runs as a continuous sequence. A garden-level room that needs a wall opened up, established and monitored adds a wait that no programme can compress, and worktop templating cannot start until the units are set. We write a dated programme after survey and revise it in writing if the readings say so.",
      },
      {
        q: "Our upstairs neighbours share the freehold. Do they need to agree?",
        a: "If your lease requires consent for alterations, then yes, and the person granting it lives above you. That is common in the split houses here. We can give them the same drawings and method statement a managing agent would receive, so the request is specific rather than a conversation on the steps. We do not start strip-out while the agreement is outstanding. [VERIFY your lease.]",
      },
      {
        q: "Can we lay stone or large-format tiles on a garden-level kitchen floor?",
        a: "Only once we know what is underneath. A suspended timber floor over a shallow void moves, and rigid finishes crack unless the deck is upgraded or an uncoupling layer is used; a solid floor with an old asphalt or bitumen layer is a different question again. The survey opens a section rather than guessing, and the floor build-up is written into the specification before ordering.",
      },
    ],
  },
  "queens-park": {
    scopeNotes: [
      "Two grains, two different first questions. On the Brent terraces the kitchen sits in a rear return with a bathroom on the half-landing above, so the soil pipe and the bath waste come down through the room, and how they are boxed and where the wall units can go follows from that. On the Westminster Estate the cottages are small and most have no side route, so every carcass comes in at the front door and along the hall.",
      "Not in it: building out over the yard, or taking down the return wall to make a wider room. That is the usual NW6 terrace ambition and it is structural work, which sits with Hampstead Renovations. On the Estate we also draw the line at original internal joinery — a dresser recess, a door, an architrave — which is specified and worked around rather than removed for a longer run of units. Decorative brickwork outside the room is not ours to alter.",
    ],
    processNote: "What runs above the kitchen sets the sequence here. Where the bathroom on the half-landing drains through the room, that pipework is opened and closed inside one agreed window, so the bathroom is not out of use across the whole fit-out. The paperwork runs in parallel and has to name the right authority — Brent and Westminster license separately and appraise separately, and the wrong form is time lost. Drops are booked to a residential street, never the spine. [VERIFY the frontage.]",
    consent: "Which council you are dealing with is settled by the frontage, not by the postcode: Brent's Queen's Park Conservation Area and Westminster's Queen's Park Estate Conservation Area are separate designations with separate appraisals. [VERIFY which one covers the address.] Either way, replacing a kitchen inside an existing room is not normally a planning matter, while anything landing on the elevation is. Tenure runs on a different track again — the converted flats on the larger roads usually need the freeholder's licence to alter, whereas an Estate cottage in single ownership will not.",
    extraFaqs: [
      {
        q: "The bathroom is directly above our kitchen. What does that mean for the work?",
        a: "It means the soil pipe and the bath waste pass through your room, and the ceiling and the boxing come down with the units. We plan that pipework as one operation rather than returning to it, and we tell you the window during which the bathroom above will be off. Where the pipe is old cast iron, replacing it while the ceiling is open is usually the sensible moment.",
      },
      {
        q: "How do kitchen units get into an Estate cottage on a narrow street?",
        a: "Through the front door and along the hall, in sections, on a timed drop. The Estate grid is tight and there is rarely a side route, so we measure the door, the hall width and the turn at the back before anything is ordered, and we protect the floor for the whole run rather than on delivery day. Where a unit will not turn, it is specified differently.",
      },
      {
        q: "Our rear-return kitchen has one small window. Can that be improved?",
        a: "Within this service, not by making the opening bigger — that is a change to the elevation and to the structure, and it sits with Hampstead Renovations. What can change inside the room is the lighting layout, the colour and reflectance of the finishes, and where the tall units sit so the window is not blocked. Mechanical extract is specified for the room, not left to the window.",
      },
    ],
  },
  "st-johns-wood": {
    scopeNotes: [
      "A mansion-block kitchen as leased is the ordinary NW8 scope: a short galley or an L on a riser that also serves the flats above and below, inside a building whose managing agent has a view on working hours, floor coverings and almost everything between. What sizes the job is not taste but the route. A stair, a doorway and an internal corridor decide between them the largest carcass that can arrive in one piece.",
      "The scope does not extend into the common parts beyond protecting them, and it does not touch the riser, the block's services, or any wall dividing one demise from another. In the villas, the extension, the basement and the opening between reception rooms are a different firm's work, and that firm is Hampstead Renovations. We also do not stand as the applicant for a building's consent: we produce drawings and a method statement, and the leaseholder signs.",
    ],
    processNote: "The building's calendar, not ours, gives the programme its shape. Deliveries arrive in booked slots through a door the porter controls, so a kitchen comes in as several loads rather than one, and fitting is sequenced against what has actually landed. Noisy hours are banded, which spreads the same quantity of work over more days without adding any to it. Match days at Lord's are read into the plan before dates are given, not explained afterwards. [VERIFY event restrictions with the building.]",
    consent: "Consent here arrives in two layers that are easily confused. Westminster is the planning authority, and it designated the St John's Wood Conservation Area in 1968; fenestration, front boundaries and roof alterations are controlled, while a kitchen fitted within an existing room usually is not. The freeholder is the second layer, and in the mansion blocks the design guide and the licence to alter are frequently stricter than anything the council would ask for. Some addresses also sit under an estate scheme of management. [VERIFY the designation, the lease and any scheme of management on the address.]",
    extraFaqs: [
      {
        q: "The block restricts working hours. Does that make the job longer?",
        a: "On the calendar, yes; in content, no. The same quantity of work spreads over more days when noisy operations are confined to a band the building sets and deliveries arrive only in booked slots. That is built into the programme before dates are given, so the finish date reflects the block's rules rather than an optimistic run at them.",
      },
      {
        q: "We are in a villa rather than a mansion flat. Is it a simpler job?",
        a: "Different, rather than simpler. Access is usually easier and there may be no managing agent to satisfy, though some addresses sit under an estate scheme of management. The interior is where the complication moves to: a villa kitchen has often been altered several times, and the services follow those alterations rather than any original logic. That is surveyed, not assumed. [VERIFY the tenure.]",
      },
      {
        q: "We want to drop gas and move to induction. Is that straightforward?",
        a: "It is a real change rather than a swap. The gas supply is capped by a Gas Safe registered engineer, and induction wants its own circuit, so in an older mansion block the incoming supply and the consumer unit are checked before anything is specified. New circuits are notified where the regulations require it, and the lease may treat the change as an alteration. [VERIFY the supply and the lease.]",
      },
    ],
  },
  "swiss-cottage": {
    scopeNotes: [
      "A Swiss Cottage kitchen is usually one room inside one demise: a kitchen off a hall in an inter-war or post-war block on Finchley Road or Avenue Road, or a converted first-floor room a street back toward Belsize. In the later blocks the floor is often solid rather than timber, so waste runs cannot drop into a void and the sink stays close to the existing stack. That single fact decides most of the layout before anything is drawn.",
      "The wall between the kitchen and the reception room is not part of it. In a block it is a structural question and a demise question at once, and it sits with Hampstead Renovations rather than here. Nor do we assume a new duct can be cut through an Avenue Road elevation, or that the service entrance and goods route are ours to use. Those are the building's to grant, and we ask before we programme.",
    ],
    processNote: "The lead-in carries more weight here than the fit-out does. In the larger blocks off Avenue Road the managing agent's paperwork, working-hours clause and any porter arrangement are settled before a cabinet is ordered, and nothing is stripped while that sits open. Conversions a street back need neighbour notice and a protected communal stair instead. Either way the delivery slot is booked against a Finchley Road corridor restriction rather than assumed, which is what usually sets the start date. [VERIFY the highway authority for the frontage.]",
    consent: "Consent here comes from two places that are easy to confuse. Replacing a kitchen inside an existing room is normally outside planning control; the moment a duct, grille or window touches the elevation, Camden becomes the decision-maker, and many streets off Finchley Road and Avenue Road remain inside the South Hampstead Conservation Area [VERIFY the map for the address]. Separately, the lease may require the freeholder or managing agent to grant a licence to alter before wet areas or circuits are moved. We prepare that pack; we do not grant it. [VERIFY the lease.]",
    extraFaqs: [
      {
        q: "Who actually signs off a kitchen change in an Avenue Road block?",
        a: "The freeholder or the managing agent acting for them, through a licence to alter under your lease. Camden only enters if something breaks the elevation. We can assemble drawings, a method statement and the trade details the agent usually asks for, and we will attend their process, but the signature is theirs. Timescales vary by building. [VERIFY with the agent.]",
      },
      {
        q: "Can a Swiss Cottage flat take a ducted extractor, or is recirculation the answer?",
        a: "It depends on what the block will accept as a termination and whether there is a route to it. Where a new grille on an Avenue Road or Finchley Road elevation is not available, a recirculating hood on carbon filters is the honest answer rather than a duct drawn to nowhere. We establish which one applies at survey, before the hood is specified. [VERIFY the block's position.]",
      },
      {
        q: "Our flat has neighbours above and below — how is the noisy work handled?",
        a: "In the blocks along Finchley Road and Avenue Road the working hours are usually written into the lease or the agent's conditions, not left to us, and percussive work carries a long way through a solid floor. We programme cutting and lifting into the permitted window and warn the flats either side beforehand. In a converted house it is the party wall and the shared stair that set the same limits.",
      },
    ],
  },
  "west-hampstead": {
    scopeNotes: [
      "The rear return is where most West Hampstead kitchens sit: a run set between one window and a door that opens into it, with the waste leaving through the back wall to a yard stack. The width of that return decides the job. It sets worktop depth, whether a dishwasher and a tall fridge can both stand in the run, and whether a hood can be ducted at all. Everything else is arranged around that measurement.",
      "What it excludes is the move most people have seen next door: opening the return into the reception, or filling in the side return. Neither is kitchen renovation on this site, and both sit with Hampstead Renovations. The shared hallway and stair are outside the instruction too. We protect them for the duration, but redecorating common parts is the freeholder's business, not a flat's kitchen scope. Street-elevation windows are a separate question again.",
    ],
    processNote: "Here the lead-in is mostly logistics rather than designation. A licensed drop on a residential side street has to be booked before a strip-out date is fixed, because three stations on West End Lane make a same-day decision unworkable. Noisy first fix is banded into hours the neighbour through the party wall has been told about. Carcasses are ordered only once the return has been measured out of square, which is later than most clients expect and earlier than the fitters need.",
    consent: "Camden is the authority for every address here, so the variable is the street rather than the borough. Some streets sit in a conservation area, and an Article 4 direction can remove a permitted-development right that would otherwise apply to a window. A kitchen fitted inside the existing room is not usually a planning matter; the moment work reaches the outside wall it becomes one, whether that is a new grille, an enlarged opening or a replacement sash. Tenure is the other half: most flats here are leasehold, and the licence to alter is granted by the freeholder or their managing agent. [VERIFY the conservation area, any Article 4 and the lease terms for the address.]",
    extraFaqs: [
      {
        q: "How long is a rear-return kitchen out of use?",
        a: "Four things move it: whether the room is emptied before we start, whether services shift position, the lead time on cabinetry, and whether shared-building hours restrict noisy work. A replacement in the same footprint runs shorter than one that moves services; one waiting on a freeholder's consent runs longer, because the wait sits in the lead-in rather than on site. A written programme follows the survey, not a figure over the telephone.",
      },
      {
        q: "Could the kitchen move to the front room instead?",
        a: "Rarely, and drainage is the reason. Waste in these terraces leaves at the back to a yard stack, and a run forward across the flat needs fall it usually cannot find without lifting the floor. Ventilation is the second obstacle: a front elevation in a conservation area is not somewhere a grille is assumed. We say at survey which of the two rules it out.",
      },
      {
        q: "Can a rear return take a properly ducted extractor?",
        a: "Sometimes. A short duct through the return's rear or side wall is the honest option, and the answer depends on where it lands: a neighbour's window a few feet away changes it, and so does a conservation-area elevation. Where no acceptable route exists we say so and specify a recirculating hood instead, at survey, not after the ceiling has been closed. [VERIFY the designation for the address.]",
      },
    ],
  },
};
