// Generated by scripts/build-detail-data.mjs — edit the copy here directly;
// re-running the generator overwrites this file.
import type { ComboDetailMap } from "./combo-detail";

export const refurbDetail: ComboDetailMap = {
  "belsize-park": {
    scopeNotes: [
      "A large share of Belsize flats are lateral conversions spanning two former houses, and that inheritance sets the brief. There are two sets of floor levels meeting somewhere in the middle, two original service positions, and doors punched through what used to be a party wall. The instruction covers replacing the kitchen and bathroom on whichever service position they were given, decorating rooms whose walls carry more area than the plan suggests, and levelling floors between the halves.",
      "What we do not take on is the stucco, the roofscape, the communal hall of a converted villa, or a further opening through the wall that still separates the two halves. That is structural and belongs with Hampstead Renovations. External repair is outside the brief as well: on this stock a rendered front is a consent matter and a maintenance liability shared with other flat owners, not an item to fold into an interior programme.",
    ],
    processNote: "On the avenues the managing agent's timetable sets the start date, and nothing is stripped until the pack is back. In a converted house the lead-in is shorter, but the room heights have to be planned for: towers and platforms are booked, and somewhere in the flat has to store them. That pushes ceilings, cornices and high-level preparation to the front of the works. Floors are laid afterwards, because a floor laid first is only covered up again.",
    consent: "The Belsize Conservation Area is a Camden designation and a separate one from Hampstead's, with Article 4 directions over parts of it [VERIFY the boundary and any Article 4 for the address]. Interior replacement within the rooms as they stand ordinarily sits outside planning; the elevation, the windows and the roofscape do not. Consent under the lease is a different matter altogether. In blocks it comes from the managing agent; in a share-of-freehold conversion it comes from the other flat owners, and it still has to be given in writing.",
    extraFaqs: [
      {
        q: "Our flat runs across two houses. Does the join cause problems?",
        a: "It usually shows in the floors and the joinery. Levels rarely match exactly where the two houses meet, skirting and architrave profiles differ either side, and services were installed twice. A refurbishment can bring the finishes to one standard and ease the transition between levels. It cannot make two Victorian houses into one, and we will not pretend otherwise at survey.",
      },
      {
        q: "The kitchen was inserted around a chimney breast. Can the extract go up the flue?",
        a: "Sometimes, and only after the flue is checked for condition, for what else is connected to it, and for whether the lease or the freeholder permits the use [VERIFY]. Old flues in this stock are often shared or partly blocked. Where the flue will not serve, the alternative is an external terminal, which is a conservation question rather than an assumption.",
      },
      {
        q: "Can an ensuite be added to a bedroom in a Belsize conversion?",
        a: "Only where the drainage will reach it without cutting into another flat, and where the lease allows a wet room over a habitable room below. Both are checked at survey rather than assumed from a floor plan. If the answer is no, we say so at the first visit. Forming a new door opening in a structural wall is a separate matter and not this service.",
      },
    ],
  },
  "crouch-end": {
    scopeNotes: [
      "Most Crouch End instructions are one flat in a house that was split decades ago: a kitchen in the former rear room, a bathroom fitted wherever the plan allowed, high rooms decorated with their mouldings intact, floors made good. The deciding constraint is what sits above and below you. A waste run crosses a neighbour's ceiling and a strip-out shares their stair, so it is the demise, not the building, that we are pricing.",
      "The stair, the roof, the front elevation and the garden sit outside that scope unless the freeholder instructs them separately. Nor do we take the wall out between front and rear reception, or build the rear addition the flat below already has. Where a house is held on share of freehold, the line between one flat and the building blurs, so the written scope names rooms rather than leaving it to be argued later.",
    ],
    processNote: "Before anything is ordered we establish who the freeholder actually is, because in a split house it is often the other flat owners, and their written agreement takes longer to gather than a managing agent's decision. Haringey licences a skip on a residential side street. Stair and hallway protection goes in on day one. Breaking out over an occupied flat is blocked into agreed hours, and the shared parts are made good before handover rather than after it.",
    consent: "Two different permissions are involved and they come from different people. Haringey grants planning permission and holds the conservation-area designation [VERIFY whether the address sits inside it]; that bears on windows, elevations and anything visible, not on replacing a kitchen inside a room that already exists. The lease decides the rest. A licence to alter for work touching structure, wastes or common services is granted by the freeholder, and in a share-of-freehold house that means your co-owners acting in that capacity [VERIFY the tenure]. We can prepare drawings and a method statement; the consent itself is not ours to give.",
    extraFaqs: [
      {
        q: "What actually drives the cost of refurbishing a conversion flat here?",
        a: "The number of wet rooms, the condition found once floors come up, the level of the fittings you choose, and how much protection a shared stair needs. Occupied work costs time. We publish no price list and we do not quote from photographs. We visit, define the scope in writing, then price that scope, with real unknowns listed as provisional rather than buried.",
      },
      {
        q: "We have share of freehold — who signs off a licence to alter?",
        a: "Your co-owners, acting as the freeholder. It is a formal written consent, not a conversation over the fence, and it usually takes longer to gather than an agent's decision because everyone has to agree. We can prepare drawings and a method statement to support it. We do not strip a kitchen or bathroom while it is outstanding. [VERIFY the tenure.]",
      },
      {
        q: "The flat below is occupied — how does that change a bathroom replacement?",
        a: "It sets the hours and the method. The waste runs sit over their ceiling, so isolation, testing and making good are planned rather than improvised, and noisy breaking is confined to agreed times. Neighbour notice goes out before the strip-out. If there is a history of leaks, we would rather see it at survey than find it through their plaster.",
      },
    ],
  },
  "golders-green": {
    scopeNotes: [
      "A typical instruction covers more rooms than a flat brief does. Kitchen at the back, one bathroom and often a second, halls and landings, the receptions and the bedrooms, and floors throughout. Because the houses are large enough to live in around the work, the deciding question is usually not the fabric but the phasing: which rooms come out of use, in what order, and for how long.",
      "Knocking the kitchen through to the dining room is the request we most often have to decline. It is a structural opening, and it is not this service — Hampstead Renovations does that work. Nor do we replace the back addition, raise the roof or convert the garage. One more exclusion is worth stating plainly: textured ceiling coatings and old floor tiles are not disturbed until a specialist has tested them, because materials of that age can contain asbestos.",
    ],
    processNote: "Barnet issues the licences, and on the crescents behind the main road a drive often removes the need for one altogether — though a drive is used as a drop point only if the survey says the crossover and the paving will take the weight. The bigger variable is you. In an occupied house the sequence is built around keeping a kitchen and a bathroom alive, which means the second bathroom, if there is one, is finished before the first is touched.",
    consent: "Most Golders Green addresses are ordinary Barnet planning: no Trust, no scheme of management, and no conservation constraint on an interior that leaves the outside as it was. Selected streets and the ground near Golders Hill Park are designated, and there the elevation matters again — a new extract terminal or a flue on a front or flank wall is checked before it is drawn [VERIFY Barnet's conservation-area map for the address]. Where the property is a flat in one of the blocks on the main roads, the licence to alter is granted by the freeholder or managing agent, not the council.",
    extraFaqs: [
      {
        q: "Can a family-house refurbishment be split into phases rather than done in one run?",
        a: "It can, and in an occupied house it sometimes should. The cost of doing it that way is repetition: protection goes up and comes down twice, and a decorator returns to a house that has been lived in since. Wet rooms are the sensible thing to group, because they carry the services. We will set out both options after the survey and let you choose against a written scope.",
      },
      {
        q: "What is behind the walls in a 1930s Golders Green house?",
        a: "Rarely what the drawing says. Later partitions, hardboard nailed over panelled doors, a ground floor that is solid in one room and suspended timber in the next, and services replaced piecemeal over ninety years are all ordinary findings. The survey records what can be seen and lists the rest as provisional. If something is found once the room is open, it is written up as a variation before it is done.",
      },
      {
        q: "Do you work on the mansion flats along the main roads as well as the houses?",
        a: "Yes, and they are a different job in everything except the definition. A flat brings a lease, a managing agent, agreed working hours and common parts that have to be protected rather than walked through. Loading is the other difference: a house behind the crescents usually has a drive, while a block on the main road has a peak-hour kerb and a timed window. The four items in scope do not change.",
      },
    ],
  },
  "hampstead": {
    scopeNotes: [
      "Most Hampstead instructions land in a flat carved out of one house, so the kitchen sits in a former bedroom or rear closet and the bathroom sits over the original stack. What decides the job is rarely the finish schedule. It is where the soil pipe already runs, whether the ceilings are lath and plaster rather than board, and how far the floors have dropped away from level since the house was divided.",
      "Left out are the roof, the parapet gutters, the sash boxes on the front elevation and anything that changes the plan of a listed interior. Village terraces share roofs and rainwater goods with neighbours, and the listed count around the High Street is high enough that internal alteration cannot be assumed. Structural openings, lofts and rear additions are not this service either; that work sits with Hampstead Renovations. We make no assumption about a van reaching the door.",
    ],
    processNote: "The lead-in here carries more than materials. Listing and conservation status are checked against the address before anything is ordered, and in a converted house the freeholder's position on wet-room work is settled in the same period. Loading is timed for the lane, and a whole-flat strip is broken into drops rather than one delivery. On site that means the shared stair carries one trade at a time, and the flat is worked back to front so the entrance is finished last.",
    consent: "Planning, conservation-area and listed-building matters all sit with Camden. Replacing a kitchen or bathroom inside the rooms that already exist usually falls outside planning control, though in a listed building internal work affecting the special interest can need listed-building consent in its own right [VERIFY on the specific property]. The envelope is different: an extract terminal, a replacement sash or external decoration is a Camden question. A licence to alter, where the lease requires one, is granted by the freeholder or managing agent, not the council.",
    extraFaqs: [
      {
        q: "How long does a Hampstead conversion flat take once work starts?",
        a: "The rooms set the baseline and the building moves it. Lath-and-plaster ceilings, floors that need levelling before anything is laid, and a stair that only one trade can use at a time all add days. Listing checks and a freeholder's consent sit ahead of the start rather than inside it. We date the programme after survey and against the written scope.",
      },
      {
        q: "The walls are original lime plaster — do you skim everything?",
        a: "Not as a default. Sound lime plaster is repaired and prepared rather than covered, because a modern skim over a soft background tends to fail at the edges. Where a wall has blown or been patched badly it is taken back and rebuilt. Which walls fall into which category is recorded at survey, room by room, not decided with a roller in hand.",
      },
      {
        q: "The flat was altered before we bought it and we think it is listed — what then?",
        a: "We check the listing and the conservation-area position against the address before pricing anything [VERIFY]. If earlier work was carried out without consent, that is a matter for you and Camden, and we will not build over it as though it had been approved. Our scope stays inside kitchen, bathroom, decoration and floors in the rooms as found.",
      },
    ],
  },
  "hampstead-garden-suburb": {
    scopeNotes: [
      "Work in the Suburb stays inside the house: a small cottage kitchen refitted in the room it has always occupied, a bathroom renewed on the waste already there, decoration through rooms with original doors and panelling, floors made good. Because the outside is unavailable, appliance and extract choices are made to suit a route that exists. Cabinetry is scribed rather than dropped in, since these walls were not built square and have not become square since.",
      "Anything that shows on the elevation is out: a new grille or flue, a rooflight, a dormer, replacement windows, a wider hardstanding. So are structural openings and loft rooms. The reason is local rather than general. The Trust's Scheme of Management and Barnet's controls both reach items owners assume are theirs alone, and a freehold title does not lift them. We would rather name that at the first visit than meet it after strip-out. [VERIFY.]",
    ],
    processNote: "The lead-in asks one question ahead of any other: does the brief hide an item that breaks the envelope. An extractor terminal is the usual one, and finding it after the kitchen is out stops a job rather than delaying it. Where two approvals are needed they are started in parallel, not one behind the other. On site, materials are stored inside rather than on a green or a verge, and deliveries reach a close in small staged loads.",
    consent: "The Suburb answers to Barnet and to the Trust, and they are not interchangeable. Barnet grants planning permission and administers the conservation area and the Article 4 direction that limits permitted-development rights here [VERIFY its scope]. The Hampstead Garden Suburb Trust separately administers a Scheme of Management under its own Act, and its written consent is required for many external items even where the house is freehold, which is exactly where owners are caught out [VERIFY whether the property falls inside the Scheme]. Leasehold flats are not the local type, so a licence to alter is rarely the question. The Trust usually is.",
    extraFaqs: [
      {
        q: "We own our house freehold — why does the Trust still have a say?",
        a: "Because the Scheme of Management runs under the Trust's own Act of Parliament and binds properties inside its boundary regardless of tenure. Freehold removes a landlord, not the Scheme. For an internal kitchen, bathroom, decoration and floors that changes little in practice. For anything visible from outside it changes a great deal. [VERIFY whether the property falls inside the Scheme.]",
      },
      {
        q: "Can leaded casements and panelled doors be made good internally?",
        a: "Yes, as internal joinery. Doors, panelling, architraves and stair joinery are repaired and decorated within the rooms in the brief, and easing or repairing a casement in its existing opening sits inside that. Replacing a window is an envelope decision needing Barnet and, in most cases, written Trust consent, so it stays out of an interior programme. [VERIFY.]",
      },
      {
        q: "What makes a Suburb programme take longer than the same rooms elsewhere?",
        a: "The lead-in, not the trades. If any part of the brief touches the outside, two written consents have to be in hand before work starts, and neither runs to our diary. Cottage rooms are also small enough that trades cannot overlap the way they do in a larger house, so the sequence runs closer to single file.",
      },
    ],
  },
  "highgate": {
    scopeNotes: [
      "Three building types account for most of the work. A Village house gives small, tall rooms, original joinery and, often, a listed interior [VERIFY the listing for the address]. A slope villa gives a family kitchen already in a rear room, two or three bathrooms and long decorating runs. A conversion toward Archway gives a stacked wet room and a shared hallway. The brief is the same four items in each; the fabric they sit in is not.",
      "Nothing here involves cutting or digging. No opening is formed between rooms, no storey is added under the roof, and no ground is broken — steep plots and mature trees make groundwork a specialist and often a protected matter [VERIFY any TPO or conservation-area tree notice with the correct borough]. That work belongs to Hampstead Renovations. We also do not assume a skip can stand where the van stopped.",
    ],
    processNote: "The first task is administrative, not practical: establishing which borough the address belongs to, because that determines the skip and scaffolding licence, the conservation appraisal that applies and, if the house is listed, whose conservation officer takes the enquiry. Village lanes then decide the vehicle and the number of drops. Only once those are fixed do wet rooms start; on a listed interior, nothing is opened up until the position on the fabric is written down.",
    consent: "Highgate is where the usual rule of thumb breaks down. Elsewhere, planning looks outward and an interior is nobody's business but the owner's and the lease's. In a listed building that is not true: listed-building consent can be required for internal alterations as well as external ones, and it comes from the borough the address sits in — Camden, Haringey or, on some streets, Islington. A licence to alter, where a lease exists, is the freeholder's or agent's decision and separate from either. [VERIFY the listing, the designation and the authority for the address.]",
    extraFaqs: [
      {
        q: "Does internal work in a Highgate house need consent from the council?",
        a: "Usually not. Planning is concerned with what the building shows to the street, so a new kitchen, a re-fitted bathroom, floors and paint inside existing rooms are generally outside it. Two exceptions apply here more than most places: a listed building, where internal alterations can need listed-building consent, and a leasehold flat, where the freeholder's licence is required regardless of what the council thinks. [VERIFY both for the address.]",
      },
      {
        q: "Is Holly Lodge Estate treated the same as the rest of Highgate?",
        a: "No. Holly Lodge Estate is a conservation designation of its own, with its own appraisal, and it is not covered by reading the Highgate Conservation Area document [VERIFY which designation and which borough apply to the address]. Inside the flat or house, the work is the same four items. Outside it — the elevation, the setting, the estate's own arrangements — the reading has to be done separately.",
      },
      {
        q: "Can uneven floors in a Village house be levelled as part of the work?",
        a: "Within limits. A self-levelling compound or a ply overlay will take out a gentle fall, but it adds height, and that height has to be paid for at the door thresholds, the skirtings and the bottom stair riser. A floor that has moved because something structural has moved is a different problem, and one we will identify rather than bury under a new finish.",
      },
    ],
  },
  "kentish-town": {
    scopeNotes: [
      "The ordinary Kentish Town brief is a whole demise in a converted terrace: rear-return galley, a bathroom squeezed in where the split allowed, decoration, floors. In a garden flat the lower-ground rooms come with it, and they are what sets the order of works. Moisture in a half-buried wall decides when units can be hung and when plaster can be painted, so the survey reads the fabric before anyone discusses finishes.",
      "Height is the exclusion that matters here. Digging a lower-ground floor down, underpinning, or opening the wall between front and back is not part of this. It is a common request in NW5 garden flats, and it is structural work for Hampstead Renovations. A rear addition that already exists can be refitted as a room; a new one cannot be built under this heading. Nor do we treat a shared hallway as ours to use without a written method.",
    ],
    processNote: "Two things sit in the lead-in here more heavily than elsewhere: the moisture picture in any lower-ground room, and the freeholder's position where the flat is leasehold. Both are settled before materials are dated. Drying and remedial time is written into the programme rather than left to compress the decoration at the end. Camden licences the skip on a side street. Neighbours on two party walls are given notice before the noisiest phase, not during it.",
    consent: "Camden is the planning authority, and designation here is patchwork rather than uniform: some streets are covered, others are not, so it is read for the address rather than for the postcode [VERIFY the named conservation area]. Interior replacement within existing rooms is normally outside planning; a new extract terminal, soil pipe or window on a rear elevation is not. Leasehold flats add a licence to alter, granted by the freeholder or managing agent where wastes, structure or common services are touched. Notifiable electrical and drainage work is notified to building control in the ordinary way.",
    extraFaqs: [
      {
        q: "Can you lower the lower-ground floor while the flat is stripped out?",
        a: "No. Taking a floor down for headroom means underpinning and structural design, which is not light refurbishment however convenient the timing looks. We will say so at the first visit and introduce you to Hampstead Renovations. What we can do is refit the rooms as they stand, once the moisture in those walls has been dealt with properly.",
      },
      {
        q: "Does damp in a garden flat add weeks to the programme?",
        a: "It can. Remedial work and drying time sit before finishes, not alongside them, and a wall that is still wet will not hold units or paint that lasts. We would rather date the programme after the survey has read the fabric than promise a handover and then compress the decoration at the end. Provisional items are listed openly.",
      },
      {
        q: "Neighbours on both sides work from home — how do you plan the noise?",
        a: "By front-loading it. Strip-out and chasing are the loud phases, so they are blocked into agreed hours early in the programme and neighbours are told beforehand rather than afterwards. Quieter trades follow. Terraces here sit close together and shared hallways carry sound, so working hours belong in the written method rather than in a courtesy conversation.",
      },
    ],
  },
  "kilburn": {
    scopeNotes: [
      "What a Kilburn instruction covers depends on what is behind the plaster. East of the High Road it is usually a Victorian conversion demise: rear-return kitchen, bathroom, decoration, floors. West of it, a flat in a later purpose-built or former local-authority block is just as likely, and there the walls are concrete or dry-lined, the heating may be communal, and services take boxed or surface routes instead of deep chases.",
      "Cutting into structural concrete, opening the compartment floor between a shop and the flat above it, or altering a shopfront to land a duct all sit outside this service, as do extensions and loft rooms. The mixed construction here is why we say it plainly: a flat is not automatically a flat, and a fit-out drawn for a period conversion does not transfer to a concrete-framed block without being redrawn. [VERIFY the construction of the block.]",
    ],
    processNote: "The first thing the lead-in settles is the borough, because Camden and Brent licence skips and scaffolding separately and the High Road is the line [VERIFY the borough for the address]. The second is who the freeholder is. A council or housing-association landlord runs its own alterations process on its own timetable [VERIFY], so that application starts earlier than a private agent's. Access is measured before cabinetry is ordered, and where the route passes a trading shop, deliveries follow its hours rather than ours.",
    consent: "Consent here can come from three directions. The council — Camden east of the High Road, Brent west of it — grants planning permission and holds the conservation-area maps, which do not follow the neighbourhood name, so designation is checked frontage by frontage [VERIFY both maps]. Replacing a kitchen or bathroom inside an existing room is not usually a planning matter; a grille, a soil pipe or a window on an upper storey above a parade is. The lease supplies the third: a licence to alter from the freeholder, whether that is a private landlord, a managing agent or a public one.",
    extraFaqs: [
      {
        q: "Our freeholder is the council — does that change the licence to alter?",
        a: "In timing and paperwork, yes. A public landlord runs a formal alterations process with its own forms and its own queue, and it does not move faster because the flat happens to be empty. We can prepare drawings and a method statement to go with the application, but the consent is theirs. Nothing is stripped while it is outstanding. [VERIFY the process for the block.]",
      },
      {
        q: "Does concrete construction rule out fitting a new bathroom?",
        a: "No — not within the room that exists. Wastes and pipework take boxed or surface routes rather than deep chases, and we do not cut structural concrete to hide a pipe. Fixings, floor build-up and the existing soil position are recorded at survey, so the layout is drawn to what the slab allows rather than to a period plan. [VERIFY the construction.]",
      },
      {
        q: "The block has communal heating — does that limit a kitchen and bathroom refit?",
        a: "It shapes both. There is no boiler to swap, hot water comes from the block's system, and any change at the heat interface or to a towel rail is the freeholder's call rather than a fitting choice. Isolation and drain-down are booked with the managing agent before first fix, because they affect other flats. [VERIFY the arrangement for the block.]",
      },
    ],
  },
  "maida-vale": {
    scopeNotes: [
      "The 1890s and Edwardian blocks here hand you a fixed plan: a compact kitchen at the back, a bathroom off the hall, a corridor connecting everything, and rooms of good proportion at the front. A typical instruction replaces the two wet rooms in place, decorates the corridor and principal rooms, and renews floors. The timber intermediate floor decides most of it, since tanking, falls and build-up all have to work within existing door heights.",
      "Not included: the block's windows, its balconies, its previously painted brickwork, or any attempt to open the corridor into the reception rooms. The first three are Westminster's and the freeholder's; the last is structural work and belongs with Hampstead Renovations. Nor is a wet room moved off the service duct to a more fashionable position, because the drainage in these blocks was laid for the plan the building already has.",
    ],
    processNote: "Two dates govern the programme and neither is ours. The licence to alter has to be back, and water isolation for the riser has to be booked with the porter or managing agent, which fixes the day the bathroom opens rather than leaving it flexible. Deliveries follow the building's hours and usually the stair. Tanking and screed then need drying time before floors and skirtings, so the hall is decorated last because everything is carried along it.",
    consent: "The Maida Vale Conservation Area covers a substantial part of W9, and Westminster is the authority for it [VERIFY the boundary for the frontage]. Replacing a kitchen or a bathroom inside the rooms that exist generally sits outside planning; repainting previously painted brickwork, changing windows and altering balconies do not. The lease is a separate track: a licence to alter is granted by the freeholder or the managing agent, and it commonly reaches flooring and anything touching shared services. On canal-side frontages the Canal & River Trust can be a further party [VERIFY].",
    extraFaqs: [
      {
        q: "Do I need planning permission to replace the kitchen and bathroom in a mansion flat?",
        a: "Usually not for the rooms themselves. Internal replacement within an existing layout generally sits outside planning control, and Westminster's interest starts at the elevation: windows, balconies, painted brickwork and anything that terminates on the outside face [VERIFY]. What you are more likely to need is a licence to alter from the freeholder or managing agent. That is a lease matter, granted by them, and it belongs in the lead-in.",
      },
      {
        q: "Why does a bathroom over a timber floor need tanking?",
        a: "Because the floor moves and the flat below is somebody's ceiling. A tanked and correctly detailed floor is the difference between a tiled bathroom that lasts and water finding the ceiling downstairs in three winters' time. It also raises the finished level, which is why door heights, thresholds and the corridor floor are measured before any tile is chosen.",
      },
      {
        q: "Can the flat's electrics be brought up to date as part of the work?",
        a: "The circuits serving the rooms in scope, yes, coordinated with the installation that already exists. Blocks of this age often have limited spare capacity at the flat's own board, and shared rising mains that belong to the building rather than to you. What can be improved inside the demise is recorded at survey; anything on the building side is the freeholder's.",
      },
    ],
  },
  "muswell-hill": {
    scopeNotes: [
      "A whole family house on the slope is the usual Muswell Hill instruction: the kitchen in the original back addition, a bathroom above it on the same waste run, decoration through the hall, stair and landing, and boards lifted or refinished. What decides the job is where the drainage already runs and how many rooms have to stay usable, because the hall is the only route from the front door to everything in the scope.",
      "It does not include taking the wall out between the two receptions, forming a dormer or a loft room, or building a new rear addition. That work sits with Hampstead Renovations. Neighbouring houses have often had all three, which makes them look like part of an ordinary refresh. They are not. We also do not price the roof, the chimneys or the sash windows into an interior programme; those are elevation items with their own consent path.",
    ],
    processNote: "Access is settled first here. Haringey licences the skip, and on a controlled street a bay may need suspending before material can be dropped [VERIFY the parking arrangement for the road]. Where extract or a window would show on an elevation inside the conservation area, that question is answered while the old wet rooms are still standing. The hall and stair are protected before the first strip-out and decorated last, and materials arrive in staged loads rather than in one delivery.",
    consent: "Replacing a kitchen or bathroom inside rooms that already exist normally sits outside planning. The envelope is a separate matter. Haringey holds the conservation-area designations covering the Broadway and much of the slope, with a second designation adjoining on the Fortis Green side, and window replacement, dormers or a new grille on a visible elevation are council decisions, not ours [VERIFY the boundary and any Article 4 for the address]. Most houses on the slope are freehold, so no licence to alter arises. A converted flat or a flat behind the Broadway is leasehold, and there the freeholder or managing agent grants that licence.",
    extraFaqs: [
      {
        q: "What decides how long a whole-house programme takes here?",
        a: "The number of wet rooms, whether you stay in the house, and what the survey finds under the floors. Failed subfloor, old wiring and a bathroom on a long waste run all add days. Material dates matter as much as labour. We write the programme after survey against the defined scope, and we do not date a finish from photographs.",
      },
      {
        q: "Can you add an ensuite to a bedroom in an Edwardian house on the slope?",
        a: "Only where the existing stack will serve it. In this stock the bathroom usually sits over the back addition, and the further a new waste has to travel the less likely the fall becomes. We measure the run and the floor build-up at survey and answer then. Cutting new structure to gain a route is not this service.",
      },
      {
        q: "Do you repair original sashes and internal joinery as part of the work?",
        a: "Internal joinery, yes: doors, architraves, shutters and skirtings are repaired and decorated within the rooms in scope, and sash repair inside the existing opening sits with us as well. Replacing the windows themselves is an elevation decision that can need council consent in a conservation area, so it is kept out of an interior programme rather than slipped into one. [VERIFY.]",
      },
    ],
  },
  "primrose-hill": {
    scopeNotes: [
      "Most briefs here fall into two shapes. A single-family terrace takes the kitchen, one or two bathrooms, the floors and the decoration of the principal rooms in one run. A garden or upper flat in a split house takes the same list on half the building, with the kitchen sitting in a rear closet or a lower-ground room. What usually decides the job is the condition of the lower-ground walls and how far the drainage has to travel.",
      "The brief will not carry structure. No wall comes out between the front and back receptions, no floor is dropped to win height in a lower ground, and no rear addition is built to make the kitchen work — those are Hampstead Renovations projects, not this one. We also make no promise about the front elevation. Steps, railings, stucco and sashes on a park-side street are conservation matters before they are decorating ones [VERIFY the designation].",
    ],
    processNote: "Two things stretch the front of the programme. The first is moisture: a lower-ground kitchen or bathroom gets tested and, where necessary, isolated and left to dry before any lining, tiling or paint is even ordered. The second is access — narrow streets, resident bays and weekend visitor pressure around the hill mean the skip and the deliveries are booked to fixed windows. Everything wet therefore runs early and unhurried; decoration is deliberately the last thing to arrive.",
    consent: "Camden is the planning authority; the licence to alter, where one is needed, comes from the freeholder or managing agent — and in a split house that is often the owner of the other flat [VERIFY the tenure]. The council's interest starts at the front door and the rear wall, so new units, tiling, floors and paint inside existing rooms are not usually a planning matter at all. The elevation is where that changes: an Article 4 direction has been in force in the conservation area since 3 March 1983, so a grille, a flue or a window is checked before it is drawn.",
    extraFaqs: [
      {
        q: "How long does a whole-house programme take on a Primrose Hill terrace?",
        a: "There is no standard figure, and the honest answer is that the drying decides it more often than the fitting does. A lower-ground room that has to be isolated and left before it is lined will add weeks that no amount of labour shortens. Occupancy, the number of wet rooms and the lead times on ordered materials do the rest. The written programme follows the survey.",
      },
      {
        q: "Our kitchen is on the upper floor of a split house. Is the drainage run a problem?",
        a: "It is the first thing measured. A sink or a machine waste set a long way from the stack needs continuous fall, and the run cannot cross into the demise below without the other owner's agreement. Where the existing route will not give the fall, we say so at survey and price the position that works, rather than fitting the layout you drew and hoping.",
      },
      {
        q: "Do original shutters and sash boxes sit inside a light-refurbishment scope?",
        a: "Internally, yes — shutters, boxes and beads are programmed as joinery, stripped and made good where the build-up of old coatings has stopped them closing. Failed cords, split staff beads and perished putty are listed as repairs at survey; they are not absorbed into a painting line. Anything that changes the window itself, rather than its finish, is a conservation question first.",
      },
    ],
  },
  "queens-park": {
    scopeNotes: [
      "On the terrace streets the work is usually a converted flat: the kitchen in the back addition, a bathroom next to it or above it, decoration through the reception and bedrooms, and floors. On the Estate the same list arrives in a smaller building — narrow rooms, a modest stair, and joinery that is part of the character rather than an obstacle to the units. Room size, not ambition, sets the layout in both.",
      "The exclusions here are mostly about the back of the building. Extending the closet wing, taking the ground floor into one room, or lifting the roof over a cottage are all structural projects and all sit with Hampstead Renovations. Inside a converted terrace we work to one demise only: a single stack often serves both flats, so the waste that runs through your neighbour's ceiling is not a line we treat as ours to move.",
    ],
    processNote: "Everything downstream of the first visit depends on one answer: Brent or Westminster. The two authorities licence skips and scaffolds separately, run their own parking controls, and hold different conservation appraisals, so the paperwork is started as soon as the frontage is confirmed. Deliveries are then planned off the commercial spine and onto a residential street with a permit. Wet rooms open only when the licence, the agreed working hours and the drop point are all in place, not before.",
    consent: "Consent here is read twice, from two maps. Brent's conservation area covers streets around the park; Westminster's Queen's Park Estate is a separate designation with its own appraisal, and neither document describes the other's streets [VERIFY which applies to the address]. For the work itself the line falls in the same place on both sides: what happens within the four walls of a room is generally the owner's business and the lease's, while anything that appears on the elevation is the council's. Leasehold flats need the freeholder's or managing agent's licence to alter — that is never the council's to give.",
    extraFaqs: [
      {
        q: "Does an Estate cottage have room for the kitchen you would fit in a terrace?",
        a: "Rarely. The cottages are narrow, and the length of run available decides how many appliances the kitchen can hold before the room stops working as a room. We measure and specify to what the wall gives, rather than shrinking a layout drawn for a wider house. Original joinery is retained and worked around where it is sound, not boxed in to gain a few millimetres.",
      },
      {
        q: "What happens to the original tiled path and the front door when materials come in?",
        a: "They are covered before anything is carried past them. A patterned path and an original front door are the two things most easily damaged on these streets, and neither is repaired convincingly afterwards. Boards go down over the path, the door is protected or taken off its hinges and stored, and larger deliveries are broken into loads a person can carry rather than barrowed through.",
      },
      {
        q: "Our flat is one of two in a converted terrace. Do the neighbours need to agree anything?",
        a: "Not consent in a planning sense, but there are three practical points. Working hours are agreed and communicated before the first strip-out day. The shared stair and hallway are covered and protected before they are used as the route in. And where the freehold is shared, the other owner is also, in effect, your freeholder for a licence to alter [VERIFY the tenure]. We give notice as a matter of course rather than on request.",
      },
    ],
  },
  "st-johns-wood": {
    scopeNotes: [
      "A St John's Wood instruction is normally the leased demise exactly as it stands: the compact rear kitchen, the bathroom on its original stack, principal-room decoration, floors, internal doors and ironmongery. The riser is what decides the job. It was sized for the plumbing of a century ago, it serves flats above and below, and isolating it for a bathroom strip is an event for the whole block rather than a morning in one flat.",
      "Excluded are the windows, the front elevation, the common parts and the block's structure, all of which belong to the freeholder and, in the conservation area, to Westminster as well. We do not move a wet room over a neighbour's bedroom, and we do not form openings; that sits with Hampstead Renovations. The lift, the porter and the loading bay are treated as matters to confirm with the building rather than facilities that come with the job.",
    ],
    processNote: "Nothing is stripped until the agent's pack is signed and the building's own contractor requirements are met. Access is measured in the same period, and it changes what is bought: where the lift will not take long lengths, worktops and carcasses are specified in sizes that go up the stair and assembled inside the flat, which moves part of the fit-out later than it would sit elsewhere. Water isolation is booked with the building, so the wet rooms run to the block's date.",
    consent: "Westminster is the planning authority for most of the residential core and designated the St John's Wood Conservation Area in 1968 [VERIFY the boundary for the address]. Replacing a kitchen or bathroom inside the existing rooms generally falls outside planning; fenestration, front boundaries and roof alterations do not. Lease consent is separate and is granted by the freeholder or managing agent, not the council. Some blocks apply design guides stricter than planning, and some streets sit under an estate scheme of management, which is a third consent again [VERIFY].",
    extraFaqs: [
      {
        q: "The lease says the floors must stay carpeted. Does that stop new flooring?",
        a: "It constrains it. Many mansion-block leases specify floor coverings or an acoustic standard for the benefit of the flat below, and a hard finish laid without consent is the kind of thing that surfaces at sale. We read the clause before specifying, and where an acoustic build-up is acceptable it is designed into the floor level and the door heights from the start.",
      },
      {
        q: "Our soil stack is shared with other flats. What does that mean during the bathroom works?",
        a: "It means the strip-out is scheduled, not spontaneous. Isolation and any stack work are agreed with the managing agent so that neighbours have notice and services are down for the shortest sensible period. It also means new sanitaryware is planned to the stack positions that exist; relocating a soil connection through the building is not part of this service.",
      },
      {
        q: "We own a villa rather than a flat. Is there still a consent to worry about?",
        a: "Possibly. Some streets sit under an estate scheme of management, which operates alongside Westminster planning rather than instead of it [VERIFY for the address]. Internal replacement in the rooms as they stand is normally the least constrained part of the work; anything reaching the elevation, the boundary or the roof is where both the scheme and the council arrive.",
      },
    ],
  },
  "swiss-cottage": {
    scopeNotes: [
      "Here the brief usually names one demise and four things inside it: the kitchen, the bathroom, the floors and the decoration. In the inter-war and later blocks on the main roads, the deciding constraint is rarely the room — it is the boxed riser the bathroom hangs off and the entrance hall that everything has to be carried through. In the Victorian conversions a street back, it is the chimney breast and a subfloor that has moved.",
      "Excluded, deliberately: anything that changes the shell. A spine wall between a conversion's front and back rooms stays. A new soil connection or a duct driven into a common void is not assumed because a drawing shows one — in a block that void belongs to the freeholder, not to the flat. Openings, lofts and extensions sit with Hampstead Renovations. A whole-flat rewire is not assumed inside a brief that named two rooms.",
    ],
    processNote: "The lead-in carries more weight here than the fit-out. A managing agent on Avenue Road wants the pack, the hours and the method statement settled before a demise is opened; a conversion toward Frognal wants the neighbours told and the stair covered. Neither is instant. Wet rooms are dated from the day consent lands rather than the day the proposal is signed, and where you are staying the sequence keeps one working tap and one working bathroom for as long as the fabric allows.",
    consent: "Two consents are worth separating. Camden grants planning and conservation-area consent; the freeholder or managing agent grants a licence to alter. Replacing a kitchen or a bathroom inside the rooms that already exist usually sits outside planning altogether, because nothing changes on the outside of the building. The moment an extract grille, a soil pipe or a window is involved, the envelope is in play and the council's position matters — many of the residential streets off Finchley Road and Avenue Road sit in the South Hampstead Conservation Area [VERIFY the designation for the address]. The lease is a separate test again.",
    extraFaqs: [
      {
        q: "What actually drives the cost of a Swiss Cottage flat refurbishment?",
        a: "There is no price list, and a figure before a visit would be a guess. What moves it is the number of wet rooms, whether the services in those rooms are being renewed or reused, what the subfloor turns out to be, whether an agent's pack is required, and whether you are living in the flat while we work. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "Our lease says hard floors need consent. Does that change the programme?",
        a: "It changes what can be specified and when the decision has to be made. Leases in purpose-built blocks commonly restrict hard floors or require an acoustic underlay above a certain performance [VERIFY the wording of your lease]. We read that clause before flooring is priced, not after the boards are ordered, and it sits in the lead-in alongside any licence to alter.",
      },
      {
        q: "Does an inter-war block off Finchley Road behave like a Victorian conversion inside?",
        a: "Not inside. A conversion gives you chimney breasts, a party wall and timber floors that have moved; a purpose-built block gives you boxed risers, a tighter hall, and in some cases communal heating or hot water that is not ours to re-plan [VERIFY the arrangement for the block]. The four items in the brief are the same. What decides the layout is not.",
      },
    ],
  },
  "west-hampstead": {
    scopeNotes: [
      "Which floor of the house you own decides the West Hampstead brief more than the postcode does. A ground or garden demise keeps its rear-return kitchen and a full-height bathroom; a top-floor flat has no return at all, so the kitchen occupies a former bedroom and the bathroom is tucked into the eaves with limited height above the trap. Waste from both runs to a stack the flat above is also using.",
      "Out of scope are the common stair, the front door, the roof and the rear elevation, all of which belong to the freeholder rather than to your demise. Widening the opening between reception and kitchen is out too; that is structural, and sits with Hampstead Renovations. Nor do we assume the hallway can be used for storage. One front door serves three or four flats here, and the neighbours did not order the work.",
    ],
    processNote: "The programme here starts with two conversations rather than one. The freeholder's position on a bathroom sitting above another demise is settled first, and neighbours are told the working hours before a skip is licensed on a side street. Materials then arrive in the order they are fitted, because there is nowhere to stack them. The consequence is that the wet room finishes before the hall is decorated, since every board and bag passes through the hall.",
    consent: "Camden decides planning and conservation-area matters, and parts of the neighbourhood are designated, with Article 4 directions removing some permitted-development rights on windows [VERIFY the designation and any Article 4 for the address]. Replacing a kitchen or bathroom within the existing rooms generally sits outside planning; a new extract terminal or a replacement window on the rear elevation does not. Separately, the lease governs the work, and consent for a wet room over another flat comes from the freeholder. Notifiable electrical and drainage work is dealt with through building control.",
    extraFaqs: [
      {
        q: "What actually drives the cost of refurbishing a conversion flat here?",
        a: "There is no price list on this site, and there will not be one. What moves a West Hampstead figure is the condition of the existing services, whether the floors need levelling, how much of the fit-out has to be handled through a single shared front door, and the specification you choose for the two wet rooms. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "Our bathroom sits directly above the neighbours' bedroom. Does that change anything?",
        a: "It changes the detailing and the consent. The floor is tanked and the build-up checked against door heights before tiling is ordered, and the lease is likely to have something to say about a wet room above another demise [VERIFY]. It also changes the sequence: isolation is agreed with the flat below rather than announced to them on the morning.",
      },
      {
        q: "The bay sashes stick and the cords have gone. Is that part of a refurbishment?",
        a: "Repair is. Easing, re-cording, replacing failed sections of a sash box and redecorating the joinery all sit inside light refurbishment. Replacement is a different question, because an Article 4 direction may remove the permitted-development right to change windows on some of these streets [VERIFY]. We check the address before anyone talks about new windows.",
      },
    ],
  },
};
