// Generated by scripts/build-detail-data.mjs — edit the copy here directly;
// re-running the generator overwrites this file.
import type { ComboDetailMap } from "./combo-detail";

export const paintingDetail: ComboDetailMap = {
  "belsize-park": {
    scopeNotes: [
      "Principal rooms are what the instruction usually covers: a tall reception with cornice, ceiling rose and picture rail, sometimes two of them run together in a lateral conversion, plus the joinery that comes with that scale — full-height shutters, deep architraves, tall doors. Height decides the rest. Rooms at that scale cannot be cut in from a leaning ladder, so the access tower, the room it stands in and the day it comes up the stair are written into the scope rather than borrowed.",
      "Enriched plasterwork is where the line falls. Cornice that is sound is cleaned back and coated; cornice that has lost its detail under a century of paint, or that is broken, needs a plasterwork specialist and is reported rather than absorbed. Nothing is done above the ceiling line, no wall between the two halves of a lateral is touched, and access equipment is not left standing overnight in a shared hall without the agent's agreement.",
    ],
    processNote: "Access is the first thing fixed, not the last. The tower is sized to the room and to the stair that has to carry it, which on the tighter Village streets can decide the week the work starts. Ceilings and enrichment go before anything below them, so no finished skirting is worked over twice. On the avenues, the block's hours and the porter's rules narrow the working day, and a lateral conversion runs as one programme even though it was once two flats.",
    consent: "Two consents are often confused here. The council decides conservation matters on the outside — stucco colour, windows, the roofscape — and parts of Belsize also sit under an Article 4 direction, which removes rights a homeowner elsewhere would take for granted [VERIFY the boundary and the direction with Camden]. The freeholder or managing agent decides everything to do with the building: hours, access equipment in common parts, and the licence a lateral conversion was granted under, which may still carry conditions on how the flat is kept and decorated. Redecorating the rooms as they stand engages neither.",
    extraFaqs: [
      {
        q: "What makes one Belsize room take twice as long as another?",
        a: "Enrichment and height, mostly. A plain-ceilinged bedroom is a different quantity of work from a reception with a run of moulded cornice, a rose and full-height shutters, where every profile is cut in by hand. Moving and re-setting a tower eats days across a flat. Whether the household stays in occupation decides the rest, because half a room at a time is slower than a whole one.",
      },
      {
        q: "Is damaged or clogged cornice repaired as part of the decorating?",
        a: "Cleaning a clogged profile back is decorating work where the plaster underneath is sound. Recasting a broken section, or running a length to match an existing pattern, is fibrous plasterwork and a separate trade. We report what we find and say plainly which of the two it is, rather than filling a lost detail flat and calling it prepared.",
      },
      {
        q: "Is a lateral conversion decorated as one flat or as the two it used to be?",
        a: "As one flat, with one specification. The join usually shows anyway: the two sides rarely have matching skirting heights, cornice patterns or wall build-ups, and a single colour across both halves makes those differences more visible, not less. We record where the two meet at survey and agree how the change is handled before any of it is coated.",
      },
    ],
  },
  "crouch-end": {
    scopeNotes: [
      "Most Crouch End work is one flat inside a larger converted house. The first-floor pair of rooms often still reads as one composition: a ceiling rose at each end, a continuous cornice, and double doors or an arch where the division was. How much of that enrichment survives under earlier coats decides the specification. A cornice softened by decades of emulsion is prepared and coated honestly; it is not restored by another coat.",
      "Two things sit outside the brief. Running new mouldings or re-forming lost enrichment is fibrous plasterwork and a separate trade, so it is not folded into a decorating price. And taking out the wall between the reception rooms, however tempting the plan looks, is structural work that belongs with Hampstead Renovations. The shared hall and stair stay outside the instruction as well, unless the freeholder is the one instructing us.",
    ],
    processNote: "The tiled hall is treated as a route rather than a work area, so the ground-floor rooms run before anything on the stair, and protection is laid on the first morning and lifted last. Before a date is offered, the lead-in settles what is demise and what is common, since a house of three flats has three interested parties. Haringey licensing for a skip on a residential side street is arranged in the same window; the Broadway is not the fallback.",
    consent: "Decorating the inside of the rooms you have does not usually engage planning. Windows, front doors and the elevation do, and the Crouch End designation takes in the Broadway and much of the residential grid behind it, so external colour and any joinery change are checked against Haringey's map first [VERIFY whether the address falls inside it]. In a converted house the freeholder or the managing agent grants a licence to alter for anything past decoration. Where the freehold is shared between the flats, that means the other owners in practice.",
    extraFaqs: [
      {
        q: "What actually drives the cost of decorating a Crouch End conversion?",
        a: "We do not publish a price list, because the same floor area behaves differently from one house to the next. The drivers are the state of the substrate, whether lining is specified, how much enriched cornice and original joinery sits in scope, and whether you are living there while we work. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "Our cornice has lost its detail under old paint. Can it be brought back?",
        a: "Partly, and only sometimes. Careful cleaning back in the recesses can recover some depth where the build-up is soft, and we will try a small area first so you can see the result before committing to it. Full recovery of a lost profile is not a paint job; it is fibrous plaster work, and we will say so rather than sell a coat as a cure.",
      },
      {
        q: "The rear room was added long before we bought the house. Does that change the decorating?",
        a: "Sometimes. Older rear additions are often thinner in construction than the main house, and the staining that shows in a corner is condensation at a cold junction rather than a tired coating. We record it at survey and say what a coating will and will not do about it. Painting a cold corner does not warm it.",
      },
    ],
  },
  "golders-green": {
    scopeNotes: [
      "The usual brief is a whole house rather than a flat: four or five rooms, a landing, a stairwell that is taller than anything else in the building, and inter-war joinery in quantity — doors, architraves, skirtings, casement windows [VERIFY the window type on the property]. Plaster is generally sound and generally not square. Volume of joinery, not wall area, is what sets the length of an ordinary Golders Green decorate.",
      "What we are not doing is the alteration that larger plots tempt: no knocking two rooms together, no rear addition, no loft — that work sits with Hampstead Renovations. Rooms we decorate are rooms that already exist, finished as they stand. Outside, previously painted masonry is in scope where access and weather allow, but rendering repairs, bare pebbledash and roofline timber are separate work with a separate specification.",
    ],
    processNote: "Many houses here have off-street parking, so the lead-in is shorter than in a Camden conversion: no porter, no lift booking, often no skip licence at all if the skip stays on the property. What replaces it is a room plan agreed with the household. We check the Barnet map first in case the street is one of the designated ones, then set a sequence — bedrooms and landing before the ground floor — so a family keeps somewhere to sleep throughout.",
    consent: "The residential streets are largely freehold houses, so there is no managing agent and no licence to alter — the decision is the owner's. Barnet is the planning authority. Selected streets and the setting of Golders Hill Park sit in conservation areas, while much of the inter-war stock is undesignated [VERIFY Barnet's map for the address]. Being close to Hampstead Garden Suburb does not bring a house under the Trust; that is a different boundary. Interior decoration in existing rooms is ordinary work either way. A new external colour is not.",
    extraFaqs: [
      {
        q: "Do you paint the timbering on a mock-Tudor front?",
        a: "Where it has been painted or stained before and access is safe, yes, as an external joinery item with its own preparation. Bare or decayed boards are a repair question first, and we will say so rather than coat over them. Weather decides when it happens: external work here is booked to a realistic window, not squeezed onto the end of an interior programme.",
      },
      {
        q: "Our inter-war windows are metal — can they be painted?",
        a: "Steel casements do take paint, but they are a different preparation from timber: rust is treated back and primed for metal, and glazing putty that has gone hard is a repair rather than a coat [VERIFY the frame type before it is priced]. Condensation on the inside face is common in this stock, so we look at what the surface has been doing before we specify anything.",
      },
      {
        q: "We are having a rear extension built — can you decorate it afterwards?",
        a: "Yes, once it is finished and dry. We do not form it: extensions, openings and loft conversions sit with Hampstead Renovations, not with this service. New plaster needs a mist coat and time before a finish goes on, and joining a new room to older ones usually means the adjoining spaces come into the scope so the change is not visible at the doorway.",
      },
    ],
  },
  "hampstead": {
    scopeNotes: [
      "Village work is normally taken a floor at a time: the walls and ceilings of one or two principal rooms, the panelled doors, shutters and window boards that came with them, and the deep skirtings behind furniture that has not moved in years. The joinery decides the job. A panelled door in a village house can carry decades of coating, and whether it is rubbed down and re-coated or taken further back is settled at survey, not on the first morning.",
      "It does not include opening up the plan. Taking out a chimney breast or forming a wider opening between village reception rooms is structural work and sits with Hampstead Renovations, not here. Nor does it include replacing sash boxes, re-plastering a whole ceiling, or a scaffolded elevation assumed into the programme: a front on a village lane needs a highway licence, and on a listed building it raises a consent question as well [VERIFY], so external work is priced on its own.",
    ],
    processNote: "The lead-in here is mostly checking and access. Listing and, in a converted house, the freeholder's rules are confirmed before dates are offered, and the drop point is agreed with a vehicle that fits the lane, which usually means smaller loads more often. Joinery is settled early, because a door taken back to bare timber changes both the drying time and the order of the rooms. Where an elevation is in scope, the inside is completed first and the outside waits on a licence and a weather window.",
    consent: "Redecorating the rooms you already have is not usually a planning matter; the elevation is. Camden holds the conservation-area and listed-building maps, and the council is the body that grants consent for external change. On a listed building the inside is not automatically outside that: taking historic joinery back, altering panelling or removing an original coating can engage listed building consent, so listing is checked on the address first [VERIFY]. In a converted house the hall and stair belong to the freeholder, and their written agreement, not ours, governs anything done there.",
    extraFaqs: [
      {
        q: "How long does redecorating one floor of a Hampstead village house take?",
        a: "The programme is written after the survey, because the variables here are large. Stripping and rebuilding a paint finish on original doors and shutters takes far longer than coating sound joinery. Lime plaster that needs repair adds days before anything is coated. Working around a household, and carrying materials up a lane in small loads, both stretch the calendar rather than the labour.",
      },
      {
        q: "Can decades of paint be taken off original doors in a village house?",
        a: "Sometimes, and it is a decision made on the door rather than on the house. Where mouldings have lost their profile under repeated coats, taking the joinery back gives a better result and a longer one. Where the existing film is sound and adhering, it is prepared and re-coated. On a listed building this is a consent question before it is a technique [VERIFY].",
      },
      {
        q: "Is there anywhere to store paint and materials in a converted village house?",
        a: "Not the shared hall, unless the freeholder has agreed it in writing. Village conversions rarely have spare space, so materials are held in the room being worked on and kept to what that room can take without becoming a store. Where a listed or original stair is the only route, protection for it is written into the method before anything is carried up.",
      },
    ],
  },
  "hampstead-garden-suburb": {
    scopeNotes: [
      "Because the Trust's interest is in the outside, Suburb instructions are often whole interiors. The recurring question is joinery: doors, stair strings and deep window boards that were stained or oiled and never painted. Deciding to paint them is a one-way choice, and we put that in writing before a brush is loaded. Cottage rooms are low and small-windowed, so the joinery finish, more than the wall colour, sets how the room reads.",
      "Glazing is a separate trade. Where casements hold leaded lights, repair and re-leading are a glazier's work rather than a decorator's [VERIFY the glazing type on the house]. Nor does the instruction alter fabric: no openings between rooms and no change to the plan, both of which would sit with Hampstead Renovations. External items enter scope only once the consent route is settled, and roughcast at high level is quoted from an agreed platform or not at all.",
    ],
    processNote: "Whether the instruction touches the outside at all is settled first, because if it does, a Barnet application and a separate written Trust consent both run before any programme date can be offered [VERIFY the route for the item of work]. Internal-only instructions can be programmed straight off the survey. Joinery colours and sheens are agreed and sampled before wall coatings are ordered, since in these rooms the joinery sets the reading. Deliveries are arranged with the household, not left to the close.",
    consent: "Two bodies, two different things. The Hampstead Garden Suburb Trust administers a Scheme of Management under its own Act and consents to matters covered by the freehold covenants; the London Borough of Barnet grants planning permission and handles conservation-area control, with an Article 4 direction removing permitted-development rights on the envelope. One external item can require both, and neither substitutes for the other [VERIFY the current requirement for the specific property]. Redecorating rooms behind an unchanged elevation generally engages neither.",
    extraFaqs: [
      {
        q: "Why does one Suburb house cost more to decorate than another of the same size?",
        a: "Because the joinery differs more than the floor area does. A house that has kept its original doors, stairs and window boards carries far more preparation than one refitted more recently, and a stained finish being taken to paint is more work again. There is no price list to quote from. We look at the house, settle what is in and what is out, and put the proposal in writing against that scope.",
      },
      {
        q: "Our doors and stairs have never been painted. Should we paint them?",
        a: "That is your decision, but it should be made knowing it does not reverse easily. Stripping paint back off original stained joinery is slow, uncertain, and rarely gives back the surface you had. If you want to try painted joinery, we would suggest one room first, and living with it before the rest of the house follows.",
      },
      {
        q: "Are the original casement windows part of a decorating instruction?",
        a: "The frames and opening lights can be, as joinery. Ironmongery is taken off and refitted rather than painted around, and stays and fasteners that have seized are reported rather than coated stuck. What is not included is the glass and, on some houses, the leading [VERIFY the glazing type], which is a glazier's work.",
      },
    ],
  },
  "highgate": {
    scopeNotes: [
      "A Village house gives us small rooms with a lot of joinery in them: panelled doors, window linings, a staircase that is more surface than the plan suggests. On the slope the villas reverse that — fewer, taller rooms and a hall that runs the full height of the house. In both, what is behind the last coat decides the specification, because Village walls are often lime under later gypsum patches.",
      "It does not include scaffolding a Village elevation on the assumption that a licence will follow, and it does not include work that changes the house: no openings between rooms, no roof or window replacement. Steep plots and protected trees mean external access is a separate conversation with the correct borough before anything is priced [VERIFY the tree position with that borough]. Stripping historic joinery back on a listed interior is not assumed either; that is checked, not decided on site.",
    ],
    processNote: "Nothing is ordered until the address has been matched to a borough and, in the Village, to a listing entry. That check sits at the front of the programme because it decides whose licence any external element needs and whether joinery can be treated at all [VERIFY listing on the property]. Access follows: a steep or narrow street sets the vehicle, and the vehicle sets how much material comes at once, which is why rooms are started in the order the stair can serve.",
    consent: "Highgate has more than one planning authority, so the first answer is always the address rather than the postcode: Camden, Haringey or, on some streets, Islington [VERIFY]. That council grants planning permission and handles conservation-area and listed-building matters; a freeholder or managing agent grants a licence to alter in a converted villa flat, and the two are not interchangeable. Redecorating rooms that are not changing usually sits outside planning. Listed interiors are the exception worth checking, and anything on the elevation — colour, windows, a scaffold — is the council's question, not ours.",
    extraFaqs: [
      {
        q: "Does a flat in a converted Highgate villa need a licence to alter?",
        a: "For decoration inside your own rooms, usually not. A licence to alter is for work that touches the structure, the services or the common parts, and it is granted by the freeholder or managing agent rather than by the council [VERIFY the lease]. What the lease often does control is hours, access to the shared stair and how the hall is protected. We ask to see those terms at survey.",
      },
      {
        q: "Is Holly Lodge Estate covered by the same rules as the rest of Highgate?",
        a: "It is a separate conservation-area designation, not part of the Highgate boundary, and estate covenants can sit alongside the council's controls [VERIFY both for the address]. For interior decorating the practical effect is usually small. For anything on the outside — a colour, a window, a scaffold standing on estate land — we check the designation and any covenant before it goes in a proposal.",
      },
      {
        q: "What happens if nobody knows what the walls were last painted with?",
        a: "That is the normal position in an older Village interior. We test small areas rather than guess: whether the surface is lime or gypsum, whether an old oil-bound coating is still sound, whether a wash will lift. The result goes into the written prep specification before any product is ordered. Where a coating cannot be made to hold, we say so and price the remedy separately.",
      },
    ],
  },
  "kentish-town": {
    scopeNotes: [
      "In a Kentish Town conversion the rooms have usually been re-drawn. A stud partition dropped in at conversion runs under one original ceiling, cutting the cornice at an angle and leaving old lath-and-plaster meeting new board on the same wall plane. That junction is what the preparation is really about: two backgrounds that move at different rates behind one finish. Former workshop interiors add painted brick and higher volumes to the same problem.",
      "The instruction stops at the finish. Moving or removing that partition is building work and belongs with Hampstead Renovations, not with a decorating programme. Where a lower-ground room reads as damp, the remedial cause, whether drainage, ventilation or a failed floor, is not taken on as a paint item either. We isolate it, report it, and leave it out of scope rather than coat it and hand the room back looking solved.",
    ],
    processNote: "Lower-ground rooms are opened up and looked at first, so the decision about whether they are in scope is taken at the start rather than discovered once the upper floors are done. On a terrace with no front garden, everything comes through the front door and up a shared stair, so the protection route and the hours for noisy preparation are agreed with the neighbours on both party walls before Camden licensing is arranged.",
    consent: "Internal decoration inside the rooms you already have is ordinary work in NW5 and does not normally need planning permission. Conservation coverage here is granular: several Camden designations touch this neighbourhood and the ground rising toward Dartmouth Park, while the High Street is less uniformly covered, so external joinery colour is checked street by street [VERIFY the named area for the address]. In a leasehold flat, the freeholder grants a licence to alter for anything touching common structure. Camden grants planning permission. They are not interchangeable.",
    extraFaqs: [
      {
        q: "Do we need the freeholder's permission to have our flat decorated?",
        a: "For decoration inside your own demise, usually not, though many leases still require notice and set the hours for noisy work. Anything that touches common structure, such as a partition on a party wall or a cut into a shared void, needs a licence to alter from the freeholder. We read the clause rather than assume it. Consent is theirs to give, not ours.",
      },
      {
        q: "Old lath and plaster next to new plasterboard: how do you deal with that?",
        a: "By treating them as two backgrounds rather than one wall. The joint is raked out, filled and reinforced where it has already opened, and where the movement is likely to keep showing through paint we specify lining on the proposal rather than adding it quietly on site. Sometimes the honest answer is that a hairline will return.",
      },
      {
        q: "Our flat is a former workshop conversion. Is painted brick decorated the same way?",
        a: "No. Painted brick takes a different system from skimmed plaster: the existing coating is tested for adhesion, loose material is taken off, and suction is dealt with before anything decorative goes on. Volumes are larger too, so access is written into the programme. What we will not do is roll a wall emulsion over a failing coat.",
      },
    ],
  },
  "kilburn": {
    scopeNotes: [
      "A Kilburn instruction is usually a whole flat rather than a single room: hall, reception and two bedrooms taken together. West of the High Road the later blocks bring skimmed plasterboard, flush doors and a corridor the landlord decorates on its own cycle. The item that most often decides the work is a north-facing corner where condensation has marked the coating. Washing down and treating that comes before any colour is chosen.",
      "What the price cannot include is the reason the corner marked in the first place. Ventilation, a failed extract or a cold junction is a building matter, and a coating over it buys a season. Removing a wall between rooms is structural and sits with Hampstead Renovations. The communal corridor and stair sit outside the instruction as well, on the landlord's own cycle and its own contractor, unless we are separately instructed.",
    ],
    processNote: "In a managed block the lead-in absorbs the building's rules before it absorbs the paint: hours, whether the lift can be used or has to be protected, and whether a materials drop through the main entrance is allowed at all at that time of day. In a house conversion it absorbs a conversation with the neighbours about the shared stair. Either way, the room used to store materials is the last one decorated.",
    consent: "Redecorating inside existing rooms is not a planning matter on either side of the High Road. What changes with the boundary is who you deal with for everything else: two councils administer planning and conservation-area control, and the designated streets are selective on both maps [VERIFY]. Above a shop, the freehold is often held with the commercial ground floor, so a licence to alter for anything beyond decoration comes from that owner. Shopfronts, fascias and upper-floor windows may also carry separate frontage guidance [VERIFY].",
    extraFaqs: [
      {
        q: "Our flat is over a shop and the freeholder owns the shop. Does that hold things up?",
        a: "Only if the work goes past decoration. Painting inside your own demise rarely needs their consent, though the lease may set the hours for access through or past the shop. Anything cutting into shared structure needs a licence to alter, and that is theirs to grant. We ask the question early rather than at the point of starting.",
      },
      {
        q: "Can condensation staining simply be painted over?",
        a: "Not as a finish. The marking is washed down, any growth treated, and the surface allowed to dry before a coating goes anywhere near it. That deals with what you can see. It does not deal with the moisture, which is a ventilation and heating question, and we will tell you that at survey rather than afterwards.",
      },
      {
        q: "How long should a two-bedroom flat take here?",
        a: "Days rather than months, but the range is wide and the survey sets it. Preparation is the variable: sound walls in a later block move quickly, while a conversion with opened joints, old lining and original joinery does not. Living in the flat while we work extends it, because rooms are handed back one at a time.",
      },
    ],
  },
  "maida-vale": {
    scopeNotes: [
      "Whole-flat redecoration is the norm in the blocks, and the hall is the largest single surface in the job — a long corridor with doors down both sides, deep reveals where the terracotta elevation comes through, and picture rails running past every doorway. That corridor is also the only route to the front door, so it cannot be shut for a day. It is worked in halves, and it sets the order of everything else.",
      "Losing that corridor is not on offer. Taking a wall out to open the plan is a structural question before it is a decorating one, and sits with Hampstead Renovations; we decorate the rooms as they are drawn. The block's own corridors, stairs and lift lobby need the managing agent and a different specification. External brickwork and balconies are not folded into a flat's decorate, and no assumption is made that a lift in a 1900s block will take a full delivery.",
    ],
    processNote: "The lift is measured before anything is ordered, because in these blocks it often decides that materials come up the stairs instead, which changes both the delivery size and the hour it can happen. Porters' hours narrow the day. Work starts at the rooms furthest from the entrance and moves back toward it, with the hall split so a route always stays open. Canal-side houses replace all of that with a loading problem of their own.",
    consent: "Inside your own front door the lease governs, and the planning system does not: no one needs to be asked about the colour of a bedroom in W9. Outside it, Westminster's conservation controls reach the envelope, so previously painted brick, window frames and balcony metalwork are matters for the council, and the designation that applies to a particular frontage is checked rather than assumed [VERIFY]. Between the two sits the managing agent, who controls access, hours and anything touching common parts. Canal-side frontages can bring a further party into external work [VERIFY].",
    extraFaqs: [
      {
        q: "What decides the cost of decorating a Maida Vale mansion flat?",
        a: "There is no price list, because two flats in the same block are rarely the same job. The length of that corridor, the number of original doors and their condition, whether walls need lining, and how much of the day the porter's hours allow all move it. We visit, write a prep specification against a defined scope, and price that. 020 7101 3168.",
      },
      {
        q: "Can the long hall be decorated without cutting off the front door?",
        a: "Yes, by halves. One side is prepared and coated while the other stays walkable, then the sequence reverses. It takes longer than closing the whole run for two days, which is why it appears in the programme rather than as a surprise. Doors off the hall are coated with the leaf open so nothing is stuck shut overnight.",
      },
      {
        q: "Does the block's own external redecoration cycle affect work inside the flat?",
        a: "It can. When a block redecorates its elevations, scaffold, sheeting and window access arrive on a timetable set by the freeholder, and that is a poor moment to have your windows freshly finished inside. If a cycle is due, we ask the agent for dates before we programme the flat, and sequence the window joinery around them rather than against them.",
      },
    ],
  },
  "muswell-hill": {
    scopeNotes: [
      "Work in the slope houses usually starts with the staircase hall. The well runs through two or three storeys, and the landing ceiling sits above a flight rather than a floor, so the access decision governs the job before a single wall is filled. Around it sit deep cornices, picture rails and panelled doors carrying decades of coats. The rooms are decorated as they stand, and the hall is priced as its own piece of work.",
      "Excluded, and deliberately: the wall between the two front rooms. Knocking an Edwardian double reception into one space is structural work, and it sits with Hampstead Renovations rather than here. Nor does the price assume a scaffold. On a steep street with a sloping front garden, external items at height are quoted only once a safe platform has been agreed. Roof, render and gable work above that line fall outside a decorating instruction.",
    ],
    processNote: "Because the hall governs access, the tower goes up before the bedrooms are touched and comes down before the ground floor is finished, which puts the stairwell out of the usual room-by-room order. Ahead of that, Haringey licensing for anything standing on the highway carries a lead time, the van is chosen for the gradient rather than the load, and the frontage is checked against the Muswell Hill and Fortis Green maps before an external item is priced. [VERIFY which map applies.]",
    consent: "Redecorating the rooms you already have is not usually a planning matter in N10. The envelope is. Haringey administers both planning permission and conservation-area control, and the designation reaches the Broadway and a good deal of the residential slope, so a colour change on a street-facing window or door is settled with the council before it appears on a proposal [VERIFY the boundary for the address]. Where the property is a flat in a converted house, consent for anything beyond decoration inside the demise is the freeholder's or the managing agent's, granted through a licence to alter, not by the council.",
    extraFaqs: [
      {
        q: "How long does a whole-house decorate take in one of the slope houses?",
        a: "The survey produces the programme, not a standard figure. What moves it is the number of rooms carrying cornice and picture rails, whether the stairwell needs a tower and for how long, whether lining is specified anywhere, and whether the house is occupied. An occupied house runs longer than an empty one, because rooms are handed back in sequence.",
      },
      {
        q: "Does the stairwell need a tower, and where does it stand?",
        a: "In most of the taller houses, yes. A ladder set across a flight is not a working platform. The tower is built off the treads with a proper stair frame, which needs the hall clear for the days it is up. We record the well height and the landing at survey so the equipment is booked, not improvised on the morning.",
      },
      {
        q: "Should the picture rails come off to decorate properly?",
        a: "No. Taking a rail down usually damages the plaster line above and below it, and the reveal is rarely as clean as the client expects. The rail is prepared as joinery: filled, caulked at the wall, rubbed down and coated to the specified sheen. If it has been over-painted to the point of losing its profile, that is recorded at survey and stated plainly.",
      },
    ],
  },
  "primrose-hill": {
    scopeNotes: [
      "Instructions here divide between whole-house decoration in a terrace that is still one family's, and a garden flat where the lower-ground rooms carry the risk. The rooms themselves are straightforward — stock-brick walls, plaster that has been patched, original sashes on the front. What decides the job is what a hand and a meter find on the rear wall of a lower-ground room before anything is filled.",
      "Damp is reported, not painted over. Where a lower-ground wall is wet, we say so and leave the room until the cause is dealt with, which sometimes means the programme pauses mid-house. Tanking, underpinning, a new rear opening or any change to the elevation is outside this service and sits with Hampstead Renovations. External colour on a park-facing front is not added at the end of an interior job as a courtesy.",
    ],
    processNote: "Order of works here is set by the sashes and the lower ground. We look at both before a programme is written, because a window that needs cords and putty is joinery time, not a cut-in, and a wet rear wall can take a room out of the sequence altogether. Deliveries are booked away from weekend park traffic. In an occupied house we usually work downwards, so the rooms in daily use at ground and lower-ground level are disturbed last.",
    consent: "Primrose Hill Conservation Area covers the core streets and the setting of the park, and Camden's Article 4 direction has applied since 3 March 1983 [VERIFY the boundary for the address]. That direction bites on windows, front boundaries and elevations — the things visible from the street and from the park — rather than on emulsion inside a room that is not changing shape. Where a house has been split, the flat is one demise and the communal hall is the freeholder's: hall decoration needs their instruction, not the leaseholder's good intentions.",
    extraFaqs: [
      {
        q: "How long does decorating a Primrose Hill house take?",
        a: "The survey produces the programme. What moves it here is the joinery and the lower ground: original sashes prepared properly take joinery time, and a wet rear wall can hold a room back until the cause is dealt with. An occupied family house runs longer than an empty one because rooms are handed back and forth. We give a sequence and dates in the proposal, not a number over the phone.",
      },
      {
        q: "We are in the garden flat — does the upstairs household affect the work?",
        a: "It affects hours and access more than method. Preparation is noisy through a timber party floor, so rubbing down is programmed into agreed hours rather than run all day. The shared front door and stair are protected whether or not they are in the scope, and the neighbour is told when the noisy days fall. None of that changes what the wall needs.",
      },
      {
        q: "The front room faces the park — does that change the colour?",
        a: "It changes what the colour does. A first floor facing the park takes a lot of reflected daylight and a strong colour can read colder there than on a card. The rear rooms below take much less. We paint samples on the actual wall in both, look at them at different times of day, and only then write the colour into the specification.",
      },
    ],
  },
  "queens-park": {
    scopeNotes: [
      "On the Brent side a typical instruction is a bay-fronted terrace or the flat carved out of one: front room, rear return, and a hall with an original tiled floor that stays as it is. On the Westminster Estate the rooms are cottage-scale and the ratio changes — proportionally more door, frame and skirting per square metre of wall than a larger terrace room carries, which is what the specification has to account for.",
      "Original tiled dados, encaustic hall floors and decorative brick are not surfaces we cover to save preparation, and we will not paint them because a room reads dark. Nothing structural is in scope either: knocking through to the return, opening a chimney or altering the roof sits with Hampstead Renovations. External joinery colour on an Estate cottage is left out of an interior proposal until the conservation position has been confirmed in writing.",
    ],
    processNote: "The first hour of the lead-in goes on paperwork that is not ours: which council the frontage sits in, and who holds the freehold of a converted house, because in this stock it is often the neighbours upstairs. After that the constraint is space. A cottage has nowhere to stack materials and little room to stand a ladder outside, so deliveries are split into smaller drops on a residential street and rooms are finished one at a time rather than opened up together.",
    consent: "Two authorities meet here, and they are not interchangeable: Brent's Queen's Park Conservation Area covers streets around the park, while Westminster's Queen's Park Estate Conservation Area is a separate designation with its own appraisal [VERIFY which applies to the address]. Whichever it is, the council deals with planning, conservation and the licence for anything standing on the pavement. Consent to touch a shared hall comes from the freeholder — in a converted terrace that is frequently the other leaseholders. Painting rooms inside an unchanged flat is ordinary work; the front door and the elevation are not.",
    extraFaqs: [
      {
        q: "Who signs off decorating the shared hall in a converted house?",
        a: "The freeholder does, and in a converted Queen's Park terrace that is often you and your neighbours jointly. One leaseholder cannot instruct the common parts alone, so we ask for a written instruction from whoever holds the freehold before the hall goes in a proposal [VERIFY the title]. Until then the hall is protected as an access route while we work in the flat, not decorated.",
      },
      {
        q: "Can a painted brick front be repainted on the Brent side?",
        a: "Where the brickwork has been painted before, repainting is usually a maintenance question rather than a new alteration, but in a conservation area the colour and the decision to keep the paint at all are worth checking with the council first [VERIFY]. Unpainted decorative brick is different — we do not recommend covering it, and we will not put it in a proposal as an easy way to tidy a frontage.",
      },
      {
        q: "Why does a small Estate cottage take longer than its size suggests?",
        a: "Because the work is in the joinery, not the wall area. A cottage room can have two doors, a window, deep skirtings and a boxed stair in the same few square metres, and each of those is prepared and coated separately. Small rooms also take one person at a time. The survey counts the joinery rather than the floor area, and the programme follows that count.",
      },
    ],
  },
  "st-johns-wood": {
    scopeNotes: [
      "In the blocks, the instruction is usually the whole demise at once — reception, hall, bedrooms and the inside face of the flat entrance door — because a single approved period of works is simpler for a building to administer than several across a season. Villa and mews interiors run larger: principal rooms, a staircase, more original joinery. What decides the mansion-flat job is the building's own timetable, since materials, protection and waste all move through parts the agent inspects.",
      "Common parts are never inside it. The corridor, the lift lobby, the stair and — in most leases — the outward face of your entrance door belong to the freeholder, and painting them is a separate instruction with the agent's specification behind it [VERIFY the lease]. Fire doors keep their seals, their closers and their labels unpainted. Windows on a mansion elevation are usually the block's cyclical item, not something added to a flat's decorate.",
    ],
    processNote: "Nothing is booked until the agent's paperwork is back: approved working hours, evidence of insurance, and in most blocks a named contact and a method for protecting the route from the lift to the door. Delivery days are checked against fixtures at Lord's, which can restrict access on surrounding streets [VERIFY with the building]. Protection goes down before a tin arrives. The flat's own hall is finished last, because until then it is the corridor everyone and everything crosses.",
    consent: "The council's interest here stops at the elevation. Westminster is not consulted about the colour of a reception room, and the St John's Wood Conservation Area governs the outside — external joinery colour, windows, front boundaries [VERIFY the boundary on the address]. What governs the inside is the lease, and in several blocks a freeholder design guide stricter than planning, covering anything visible from the corridor. Evidence of insurance is usually asked for before contractors are admitted; we are fully insured [INSURANCE_TBC].",
    extraFaqs: [
      {
        q: "What does the managing agent need before decorating starts in a block?",
        a: "Typically approved working hours, evidence of insurance, a method for protecting the common route, and sometimes a deposit held against damage to the corridor. Some buildings ask for notice even where nothing is being altered. We ask the agent directly at survey rather than assuming one block runs like the last, because these rules are written building by building [VERIFY].",
      },
      {
        q: "Is the outside of our flat's entrance door ours to repaint?",
        a: "Often it is not. In many mansion-block leases the corridor face of the door forms part of the common parts, and its colour and finish are set by the building rather than by the flat. The inside face is normally yours. We check the lease and ask the agent before either side is prepared, because getting that wrong is the kind of thing an agent notices immediately [VERIFY the lease].",
      },
      {
        q: "Do you paint fire doors and their ironmongery in a mansion flat?",
        a: "The door face is decorated; the parts that make it a fire door are not. Intumescent seals, closers, hinges and the certification label on the door edge are left clear, because coating them can compromise how the door performs and removes the evidence that it was ever tested. Where a flat entrance door is involved, the agent's specification comes first [VERIFY].",
      },
    ],
  },
  "swiss-cottage": {
    scopeNotes: [
      "A Swiss Cottage instruction is usually one of two jobs. In an inter-war block off Finchley Road it is walls, ceilings, the internal hall and the flat's own doors, with the building's working-hours rule deciding how much of a day is usable. In a converted Victorian house toward Belsize or Frognal it is principal rooms where the chimney breast has moved and the filling has to be honest before any colour is discussed.",
      "It does not include opening up between rooms, moving a wall to make a through reception, or anything that changes the block's structure: that work sits with Hampstead Renovations. Nor does it assume a lift, a loading bay outside the door, or that a Finchley Road frontage can be loaded like a side street. Common parts stay a separate instruction until the freeholder or the agent gives them to us in writing.",
    ],
    processNote: "The lead-in here is usually spent on the building rather than the paint. Larger blocks on Avenue Road commonly want notice, hours and a protection method before anyone carries a tin through the entrance hall, and that sets the start date more often than our diary does. Materials for a Finchley Road frontage are booked to a timed drop, so the first room started is the one nearest the stair, not the one you most want finished.",
    consent: "Flats in the blocks here are generally leasehold, so the first question is tenure, not planning. Redecorating inside your own demise rarely needs a licence to alter; the freeholder or managing agent still sets the rules for the stair, the lift and the hours, and those rules are theirs to grant, not ours. Camden is the planning authority, and its South Hampstead Conservation Area covers many of the residential streets off Finchley Road and Avenue Road [VERIFY which designation applies to the address]. Interior colour sits outside that. Window and elevation work does not.",
    extraFaqs: [
      {
        q: "What decides the cost of decorating a Swiss Cottage flat?",
        a: "There is no price list. Cost follows the amount of preparation the walls need, the quantity of joinery, the access the building allows and whether the flat is occupied. An inter-war block with sound plaster and one hall is not the same work as a Victorian conversion with a moved chimney breast. We visit, then write a proposal against a defined scope.",
      },
      {
        q: "Does the managing agent need to know before decorating starts?",
        a: "In the larger blocks, usually. Notice, working hours and a protection method for the entrance and the lift are commonly required even when only your own rooms are being painted [VERIFY the rules for the building]. We ask for them at survey so the programme is built around them rather than interrupted by them on the first morning.",
      },
      {
        q: "Does being on Finchley Road change how a room is decorated?",
        a: "It changes ventilation and dust. A flat on the corridor cannot be aired the way a room on a side street can, so windows often stay shut for much of the day and drying time is planned rather than assumed. Protection is heavier at the entrance because grit comes in on boots. The prep specification itself still follows the wall in the room.",
      },
    ],
  },
  "west-hampstead": {
    scopeNotes: [
      "Most work here is a converted flat redecorated while the household stays in it: a bay-fronted front room, a rear-return kitchen wall that has been patched more than once, bedrooms off a half-landing, and the flat's own hall. The constraint is space rather than fabric. In a one- or two-bedroom demise there is nowhere to stack a household, so rooms are worked in halves and furniture moves twice rather than once.",
      "Outside the demise, nothing is assumed. The communal front door, the entrance hall and the stair are the freeholder's, and they are quoted only when the freeholder instructs them. Blown ceiling plaster and a bay that needs joinery repair are reported, not painted over. Nothing structural is offered — an opening between the front room and the rear return is not this service and belongs with Hampstead Renovations — and no van is assumed to stand on West End Lane.",
    ],
    processNote: "Before a date is offered, three things are settled: who owns the hall, where the vehicle stands, and what hours the flats above and below can live with. Once those are fixed, the order is dictated by the route in. Bedrooms and the rear return come first, the hall and half-landing last, so the way through the flat stays protected until the end. Noisy rubbing down sits in the middle of the day, not at either edge of it.",
    consent: "Decorating inside a leasehold flat alters nothing, so a licence to alter is rarely the right instrument; the lease is. Leases commonly carry a decorating covenant and a clause on contractors, and some require the freeholder or managing agent to be told before work starts. That is the freeholder's process, not the council's. Camden's role begins at the elevation: repainting previously painted joinery in the same colour is ordinary maintenance, while a change of external appearance in a conservation area, or under an Article 4 direction on windows, is not [VERIFY the designation for the street].",
    extraFaqs: [
      {
        q: "Do we need the freeholder's permission to redecorate a converted flat?",
        a: "Usually not permission, but often notice. Decorating changes nothing structural, so a licence to alter — the document a freeholder issues when a demise is altered — is rarely engaged. What the lease may require is that the managing agent is told, that contractors are insured, and that the shared parts are protected. We are fully insured [INSURANCE_TBC], and we read the clause before we start.",
      },
      {
        q: "Can the outside of the bay be painted at the same time as the inside?",
        a: "Only as a separate item. External joinery on a terrace front needs safe access, a settled weather window and, on some streets here, a check against the conservation-area map or an Article 4 direction before a colour is agreed [VERIFY]. Where the flat is one of three in a house, the elevation is usually a freeholder matter rather than yours, which changes who instructs it.",
      },
      {
        q: "What happens to our furniture while a two-bedroom conversion is decorated?",
        a: "It moves twice in most rooms: to the centre and covered, then back against a finished wall so the other half can be worked. Larger pieces that cannot be lifted safely are worked around, and we say which those are at survey rather than on the first morning. Nothing is stored on the shared landing, because that is not ours to fill.",
      },
    ],
  },
};
